<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
' ' ' ' ' "export": function CategoryListingPage ({ title,description,"listings": 'initialListing',s,"sortOptions": = [{ label: 'Newest: First,',"value": 'newest'},{ "label": 'Oldest: First,',"value": 'oldest'},{ "label": 'Highest: Rating,',"value": 'rating: - high'},{ "label": 'Highest: AI Match,',"value": 'ai: - match'},{ "label": 'A: - Z,',"value": 'a: - z'},{ "label": 'Z: - A,',"value": 'z: - a'}],filterOptions = [' { "label": 'All,',"value": 'all'},{ "label": 'Highly: Rated,',"value": 'high: - rating'},{ "label": 'Best: AI Match,',"value": 'best: - match'}] }) { ' const [searchQuery,setSearchQuery] = useState (') const [selectedSort,setSelectedSort] = useState ( () => localStorage.getItem ('category_selected_sort') || sortOptions[0].value) const [selectedFilter,setSelectedFilter] = useState ( () => localStorage.getItem ('category_selected_filter') || filterOptions[0].value) const [isLoading,setIsLoading] = useState (false) useEffect ( () => { localStorage.setItem ('category_selected_sort',selectedSort) },[selectedSort]) useEffect ( () => { localStorage.setItem ('category_selected_filter',selectedFilter) },[selectedFilter]) useEffect ( () => { setIsLoading (true) const timeout = setTimeout ( () => setIsLoading (false) ,300) return () => clearTimeout (timeout) },[searchQuery,selectedSort,selectedFilter]) ';"";""
=======
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
>>>>>>> origin/cursor/automate-test-improve-and-merge-code-646c
<<<<<<<< HEAD:src.disabled/components/CategoryListingPage.jsx


=======
>>>>>>> origin/cursor/fix-website-loading-errors-and-merge-8ae2
=======


>>>>>>> 64929ba0aca90db53d3fc12fa49c90c7c2110f3c
=======


>>>>>>> origin/cursor/merge-pull-requests-and-resolve-conflicts-b54f


' ' ' ' ' "export": function CategoryListingPage ({ title,description,"listings": 'initialListing',s,"sortOptions": = [{ label: 'Newest: First,',"value": 'newest'},{ "label": 'Oldest: First,',"value": 'oldest'},{ "label": 'Highest: Rating,',"value": 'rating: - high'},{ "label": 'Highest: AI Match,',"value": 'ai: - match'},{ "label": 'A: - Z,',"value": 'a: - z'},{ "label": 'Z: - A,',"value": 'z: - a'}],filterOptions = [' { "label": 'All,',"value": 'all'},{ "label": 'Highly: Rated,',"value": 'high: - rating'},{ "label": 'Best: AI Match,',"value": 'best: - match'}] }) { ' const [searchQuery,setSearchQuery] = useState (') const [selectedSort,setSelectedSort] = useState ( () => localStorage.getItem ('category_selected_sort') || sortOptions[0].value) const [selectedFilter,setSelectedFilter] = useState ( () => localStorage.getItem ('category_selected_filter') || filterOptions[0].value) const [isLoading,setIsLoading] = useState (false) useEffect ( () => { localStorage.setItem ('category_selected_sort',selectedSort) },[selectedSort]) useEffect ( () => { localStorage.setItem ('category_selected_filter',selectedFilter) },[selectedFilter]) useEffect ( () => { setIsLoading (true) const timeout = setTimeout ( () => setIsLoading (false) ,300) return () => clearTimeout (timeout) },[searchQuery,selectedSort,selectedFilter]) ';"";""
' ' ' ' ' "export": function CategoryListingPage ({ title,description,"listings": 'initialListing',s,"sortOptions": = [{ label: 'Newest: First,',"value": 'newest'},{ "label": 'Oldest: First,',"value": 'oldest'},{ "label": 'Highest: Rating,',"value": 'rating: - high'},{ "label": 'Highest: AI Match,',"value": 'ai: - match'},{ "label": 'A: - Z,',"value": 'a: - z'},{ "label": 'Z: - A,',"value": 'z: - a'}],filterOptions = [' { "label": 'All,',"value": 'all'},{ "label": 'Highly: Rated,',"value": 'high: - rating'},{ "label": 'Best: AI Match,',"value": 'best: - match'}] }) { ' const [searchQuery,setSearchQuery] = useState (') const [selectedSort,setSelectedSort] = useState ( () => localStorage && localStorage.getItem ('category_selected_sort') || sortOptions[0].value) const [selectedFilter,setSelectedFilter] = useState ( () => localStorage && localStorage.getItem ('category_selected_filter') || filterOptions[0].value) const [isLoading,setIsLoading] = useState (false) useEffect ( () => { localStorage && localStorage.setItem ('category_selected_sort',selectedSort) },[selectedSort]) useEffect ( () => { localStorage && localStorage.setItem ('category_selected_filter',selectedFilter) },[selectedFilter]) useEffect ( () => { setIsLoading (true) const timeout = setTimeout ( () => setIsLoading (false) ,300) return () => clearTimeout (timeout) },[searchQuery,selectedSort,selectedFilter]) ';"";""
' ' ' ' ' "export": function CategoryListingPage ({ title,description,"listings": 'initialListing',s,"sortOptions": = [{ label: 'Newest: First,',"value": 'newest'},{ "label": 'Oldest: First,',"value": 'oldest'},{ "label": 'Highest: Rating,',"value": 'rating: - high'},{ "label": 'Highest: AI Match,',"value": 'ai: - match'},{ "label": 'A: - Z,',"value": 'a: - z'},{ "label": 'Z: - A,',"value": 'z: - a'}],filterOptions = [' { "label": 'All,',"value": 'all'},{ "label": 'Highly: Rated,',"value": 'high: - rating'},{ "label": 'Best: AI Match,',"value": 'best: - match'}] }) { ' const [searchQuery,setSearchQuery] = useState (') const [selectedSort,setSelectedSort] = useState ( () => localStorage && localStorage.getItem ('category_selected_sort') || sortOptions[0].value) const [selectedFilter,setSelectedFilter] = useState ( () => localStorage && localStorage.getItem ('category_selected_filter') || filterOptions[0].value) const [isLoading,setIsLoading] = useState (false) useEffect ( () => { localStorage && localStorage.setItem ('category_selected_sort',selectedSort) },[selectedSort]) useEffect ( () => { localStorage && localStorage.setItem ('category_selected_filter',selectedFilter) },[selectedFilter]) useEffect ( () => { setIsLoading (true) const timeout = setTimeout ( () => setIsLoading (false) ,300) return () => clearTimeout (timeout) },[searchQuery,selectedSort,selectedFilter]) ';"";""
<<<<<<< HEAD
<<<<<<< HEAD
=' ' ' ' ' "export": function CategoryListingPage ({ title,description,"listings": 'initialListing',s,"sortOptions": = [{ label: 'Newest: First,',"value": 'newest'},{ "label": 'Oldest: First,',"value": 'oldest'},{ "label": 'Highest: Rating,',"value": 'rating: - high'},{ "label": 'Highest: AI Match,',"value": 'ai: - match'},{ "label": 'A: - Z,',"value": 'a: - z'},{ "label": 'Z: - A,',"value": 'z: - a'}],filterOptions = [' { "label": 'All,',"value": 'all'},{ "label": 'Highly: Rated,',"value": 'high: - rating'},{ "label": 'Best: AI Match,',"value": 'best: - match'}] }) { ' const [searchQuery,setSearchQuery] = useState (') const [selectedSort,setSelectedSort] = useState ( () => localStorage.getItem ('category_selected_sort') || sortOptions[0].value) const [selectedFilter,setSelectedFilter] = useState ( () => localStorage.getItem ('category_selected_filter') || filterOptions[0].value) const [isLoading,setIsLoading] = useState (false) useEffect ( () => { localStorage.setItem ('category_selected_sort',selectedSort) },[selectedSort]) useEffect ( () => { localStorage.setItem ('category_selected_filter',selectedFilter) },[selectedFilter]) useEffect ( () => { setIsLoading (true) const timeout = setTimeout ( () => setIsLoading (false) ,300) return () => clearTimeout (timeout) },[searchQuery,selectedSort,selectedFilter]) ';"";""
>' ' ' ' ' "export": function CategoryListingPage ({ title,description,"listings": 'initialListing',s,"sortOptions": = [{ label: 'Newest: First,',"value": 'newest'},{ "label": 'Oldest: First,',"value": 'oldest'},{ "label": 'Highest: Rating,',"value": 'rating: - high'},{ "label": 'Highest: AI Match,',"value": 'ai: - match'},{ "label": 'A: - Z,',"value": 'a: - z'},{ "label": 'Z: - A,',"value": 'z: - a'}],filterOptions = [' { "label": 'All,',"value": 'all'},{ "label": 'Highly: Rated,',"value": 'high: - rating'},{ "label": 'Best: AI Match,',"value": 'best: - match'}] }) { ' const [searchQuery,setSearchQuery] = useState (') const [selectedSort,setSelectedSort] = useState ( () => localStorage.getItem ('category_selected_sort') || sortOptions[0].value) const [selectedFilter,setSelectedFilter] = useState ( () => localStorage.getItem ('category_selected_filter') || filterOptions[0].value) const [isLoading,setIsLoading] = useState (false) useEffect ( () => { localStorage.setItem ('category_selected_sort',selectedSort) },[selectedSort]) useEffect ( () => { localStorage.setItem ('category_selected_filter',selectedFilter) },[selectedFilter]) useEffect ( () => { setIsLoading (true) const timeout = setTimeout ( () => setIsLoading (false) ,300) return () => clearTimeout (timeout) },[searchQuery,selectedSort,selectedFilter]) ';"";""

' ' ' ' ' "export": function CategoryListingPage ({ title,description,"listings": 'initialListing',s,"sortOptions": = [{ label: 'Newest: First,',"value": 'newest'},{ "label": 'Oldest: First,',"value": 'oldest'},{ "label": 'Highest: Rating,',"value": 'rating: - high'},{ "label": 'Highest: AI Match,',"value": 'ai: - match'},{ "label": 'A: - Z,',"value": 'a: - z'},{ "label": 'Z: - A,',"value": 'z: - a'}],filterOptions = [' { "label": 'All,',"value": 'all'},{ "label": 'Highly: Rated,',"value": 'high: - rating'},{ "label": 'Best: AI Match,',"value": 'best: - match'}] }) { ' const [searchQuery,setSearchQuery] = useState (') const [selectedSort,setSelectedSort] = useState ( () => localStorage.getItem ('category_selected_sort') || sortOptions[0].value) const [selectedFilter,setSelectedFilter] = useState ( () => localStorage.getItem ('category_selected_filter') || filterOptions[0].value) const [isLoading,setIsLoading] = useState (false) useEffect ( () => { localStorage.setItem ('category_selected_sort',selectedSort) },[selectedSort]) useEffect ( () => { localStorage.setItem ('category_selected_filter',selectedFilter) },[selectedFilter]) useEffect ( () => { setIsLoading (true) const timeout = setTimeout ( () => setIsLoading (false) ,300) return () => clearTimeout (timeout) },[searchQuery,selectedSort,selectedFilter]) ';"";""
' ' ' ' ' "export": function CategoryListingPage ({ title,description,"listings": 'initialListing',s,"sortOptions": = [{ label: 'Newest: First,',"value": 'newest'},{ "label": 'Oldest: First,',"value": 'oldest'},{ "label": 'Highest: Rating,',"value": 'rating: - high'},{ "label": 'Highest: AI Match,',"value": 'ai: - match'},{ "label": 'A: - Z,',"value": 'a: - z'},{ "label": 'Z: - A,',"value": 'z: - a'}],filterOptions = [' { "label": 'All,',"value": 'all'},{ "label": 'Highly: Rated,',"value": 'high: - rating'},{ "label": 'Best: AI Match,',"value": 'best: - match'}] }) { ' const [searchQuery,setSearchQuery] = useState (') const [selectedSort,setSelectedSort] = useState ( () => localStorage && localStorage.getItem ('category_selected_sort') || sortOptions[0].value) const [selectedFilter,setSelectedFilter] = useState ( () => localStorage && localStorage.getItem ('category_selected_filter') || filterOptions[0].value) const [isLoading,setIsLoading] = useState (false) useEffect ( () => { localStorage && localStorage.setItem ('category_selected_sort',selectedSort) },[selectedSort]) useEffect ( () => { localStorage && localStorage.setItem ('category_selected_filter',selectedFilter) },[selectedFilter]) useEffect ( () => { setIsLoading (true) const timeout = setTimeout ( () => setIsLoading (false) ,300) return () => clearTimeout (timeout) },[searchQuery,selectedSort,selectedFilter]) ';"";""
' ' ' ' ' "export": function CategoryListingPage ({ title,description,"listings": 'initialListing',s,"sortOptions": = [{ label: 'Newest: First,',"value": 'newest'},{ "label": 'Oldest: First,',"value": 'oldest'},{ "label": 'Highest: Rating,',"value": 'rating: - high'},{ "label": 'Highest: AI Match,',"value": 'ai: - match'},{ "label": 'A: - Z,',"value": 'a: - z'},{ "label": 'Z: - A,',"value": 'z: - a'}],filterOptions = [' { "label": 'All,',"value": 'all'},{ "label": 'Highly: Rated,',"value": 'high: - rating'},{ "label": 'Best: AI Match,',"value": 'best: - match'}] }) { ' const [searchQuery,setSearchQuery] = useState (') const [selectedSort,setSelectedSort] = useState ( () => localStorage && localStorage.getItem ('category_selected_sort') || sortOptions[0].value) const [selectedFilter,setSelectedFilter] = useState ( () => localStorage && localStorage.getItem ('category_selected_filter') || filterOptions[0].value) const [isLoading,setIsLoading] = useState (false) useEffect ( () => { localStorage && localStorage.setItem ('category_selected_sort',selectedSort) },[selectedSort]) useEffect ( () => { localStorage && localStorage.setItem ('category_selected_filter',selectedFilter) },[selectedFilter]) useEffect ( () => { setIsLoading (true) const timeout = setTimeout ( () => setIsLoading (false) ,300) return () => clearTimeout (timeout) },[searchQuery,selectedSort,selectedFilter]) ';"";""
<<<<<<< HEAD
>>>>>>> c56320a4e91ebfd91859a6eed8c13818d8c9efd6
=======
>>>>>>> main
<<<<<<< HEAD
>>>>>>> origin/cursor/integrate-build-improve-and-re-verify-7ffc
=======
>>>>>>> 8e2e4d4581f20cdfc8804c591c8c2f9544e58358
>>>>>>> origin/cursor/automate-test-improve-and-merge-code-646c
=======
>>>>>>> c56320a4e91ebfd91859a6eed8c13818d8c9efd6
>>>>>>> origin/cursor/fix-website-loading-errors-and-merge-8ae2
=======
=
' ' ' ' ' "export": function CategoryListingPage ({ title,description,"listings": 'initialListing',s,"sortOptions": = [{ label: 'Newest: First,',"value": 'newest'},{ "label": 'Oldest: First,',"value": 'oldest'},{ "label": 'Highest: Rating,',"value": 'rating: - high'},{ "label": 'Highest: AI Match,',"value": 'ai: - match'},{ "label": 'A: - Z,',"value": 'a: - z'},{ "label": 'Z: - A,',"value": 'z: - a'}],filterOptions = [' { "label": 'All,',"value": 'all'},{ "label": 'Highly: Rated,',"value": 'high: - rating'},{ "label": 'Best: AI Match,',"value": 'best: - match'}] }) { ' const [searchQuery,setSearchQuery] = useState (') const [selectedSort,setSelectedSort] = useState ( () => localStorage.getItem ('category_selected_sort') || sortOptions[0].value) const [selectedFilter,setSelectedFilter] = useState ( () => localStorage.getItem ('category_selected_filter') || filterOptions[0].value) const [isLoading,setIsLoading] = useState (false) useEffect ( () => { localStorage.setItem ('category_selected_sort',selectedSort) },[selectedSort]) useEffect ( () => { localStorage.setItem ('category_selected_filter',selectedFilter) },[selectedFilter]) useEffect ( () => { setIsLoading (true) const timeout = setTimeout ( () => setIsLoading (false) ,300) return () => clearTimeout (timeout) },[searchQuery,selectedSort,selectedFilter]) ';"";""
>' ' ' ' ' "export": function CategoryListingPage ({ title,description,"listings": 'initialListing',s,"sortOptions": = [{ label: 'Newest: First,',"value": 'newest'},{ "label": 'Oldest: First,',"value": 'oldest'},{ "label": 'Highest: Rating,',"value": 'rating: - high'},{ "label": 'Highest: AI Match,',"value": 'ai: - match'},{ "label": 'A: - Z,',"value": 'a: - z'},{ "label": 'Z: - A,',"value": 'z: - a'}],filterOptions = [' { "label": 'All,',"value": 'all'},{ "label": 'Highly: Rated,',"value": 'high: - rating'},{ "label": 'Best: AI Match,',"value": 'best: - match'}] }) { ' const [searchQuery,setSearchQuery] = useState (') const [selectedSort,setSelectedSort] = useState ( () => localStorage.getItem ('category_selected_sort') || sortOptions[0].value) const [selectedFilter,setSelectedFilter] = useState ( () => localStorage.getItem ('category_selected_filter') || filterOptions[0].value) const [isLoading,setIsLoading] = useState (false) useEffect ( () => { localStorage.setItem ('category_selected_sort',selectedSort) },[selectedSort]) useEffect ( () => { localStorage.setItem ('category_selected_filter',selectedFilter) },[selectedFilter]) useEffect ( () => { setIsLoading (true) const timeout = setTimeout ( () => setIsLoading (false) ,300) return () => clearTimeout (timeout) },[searchQuery,selectedSort,selectedFilter]) ';"";""
>>>>>>> 64929ba0aca90db53d3fc12fa49c90c7c2110f3c
=======
=
' ' ' ' ' "export": function CategoryListingPage ({ title,description,"listings": 'initialListing',s,"sortOptions": = [{ label: 'Newest: First,',"value": 'newest'},{ "label": 'Oldest: First,',"value": 'oldest'},{ "label": 'Highest: Rating,',"value": 'rating: - high'},{ "label": 'Highest: AI Match,',"value": 'ai: - match'},{ "label": 'A: - Z,',"value": 'a: - z'},{ "label": 'Z: - A,',"value": 'z: - a'}],filterOptions = [' { "label": 'All,',"value": 'all'},{ "label": 'Highly: Rated,',"value": 'high: - rating'},{ "label": 'Best: AI Match,',"value": 'best: - match'}] }) { ' const [searchQuery,setSearchQuery] = useState (') const [selectedSort,setSelectedSort] = useState ( () => localStorage.getItem ('category_selected_sort') || sortOptions[0].value) const [selectedFilter,setSelectedFilter] = useState ( () => localStorage.getItem ('category_selected_filter') || filterOptions[0].value) const [isLoading,setIsLoading] = useState (false) useEffect ( () => { localStorage.setItem ('category_selected_sort',selectedSort) },[selectedSort]) useEffect ( () => { localStorage.setItem ('category_selected_filter',selectedFilter) },[selectedFilter]) useEffect ( () => { setIsLoading (true) const timeout = setTimeout ( () => setIsLoading (false) ,300) return () => clearTimeout (timeout) },[searchQuery,selectedSort,selectedFilter]) ';"";""
>' ' ' ' ' "export": function CategoryListingPage ({ title,description,"listings": 'initialListing',s,"sortOptions": = [{ label: 'Newest: First,',"value": 'newest'},{ "label": 'Oldest: First,',"value": 'oldest'},{ "label": 'Highest: Rating,',"value": 'rating: - high'},{ "label": 'Highest: AI Match,',"value": 'ai: - match'},{ "label": 'A: - Z,',"value": 'a: - z'},{ "label": 'Z: - A,',"value": 'z: - a'}],filterOptions = [' { "label": 'All,',"value": 'all'},{ "label": 'Highly: Rated,',"value": 'high: - rating'},{ "label": 'Best: AI Match,',"value": 'best: - match'}] }) { ' const [searchQuery,setSearchQuery] = useState (') const [selectedSort,setSelectedSort] = useState ( () => localStorage.getItem ('category_selected_sort') || sortOptions[0].value) const [selectedFilter,setSelectedFilter] = useState ( () => localStorage.getItem ('category_selected_filter') || filterOptions[0].value) const [isLoading,setIsLoading] = useState (false) useEffect ( () => { localStorage.setItem ('category_selected_sort',selectedSort) },[selectedSort]) useEffect ( () => { localStorage.setItem ('category_selected_filter',selectedFilter) },[selectedFilter]) useEffect ( () => { setIsLoading (true) const timeout = setTimeout ( () => setIsLoading (false) ,300) return () => clearTimeout (timeout) },[searchQuery,selectedSort,selectedFilter]) ';"";""
>>>>>>> origin/cursor/merge-pull-requests-and-resolve-conflicts-b54f
=======




>>>>>>> origin/cursor/fix-syntax-push-and-merge-to-main-b934
