<<<<<<< HEAD
import React from \'react\'; import Head from \'next/head\'; export default function HomePage() { return ( <div className=\"min-h-screen\"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name=\"description\" content=\"AI services,IT solutions,and micro SaaS products by Zion Tech Group.\" /> <link rel=\"canonical\" href=\""https\": </Head> <main className=\"max-w-5xl mx-auto p-6\"> <h1 className=\"text-3xl font-bold\">Zion Tech Group</h1> <p className=\"mt-4 text-gray-700\">AI services,IT solutions,and micro SaaS products.</p> <ul className=\"list-disc pl-6 mt-6 space-y-2\"> <li><a className=\"text-blue-600 \"hover\": underline\" href=\"/services.page\">Services</a></li> <li><a className=\"text-blue-600 hover:underline\" href=\"/ai-services.page\">AI Services</a></li> <li><a className=\"text-blue-600 hover:underline\" href=\"/contact.page\">Contact</a></li> </ul> </main> </div> )}
import _React from 'react'; import Head from 'next/head'; export default function HomePage() { return ( <div className="min-h-screen"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name="description" content="AI services,IT solutions,and micro SaaS products by Zion Tech Group." /> <link rel="canonical" href=""https": </Head> <main className="max-w-5xl mx-auto p-6"> <h1 className="text-3xl font-bold">Zion Tech Group</h1> <p className="mt-4 text-gray-700">AI services,IT solutions,and micro SaaS products.</p> <ul className="list-disc pl-6 mt-6 space-y-2"> <li><a className="text-blue-600 "hover": underline" href="/services.page">Services</a></li> <li><a className="text-blue-600 hover:underline" href="/ai-services.page">AI Services</a></li> <li><a className="text-blue-600 hover:underline" href="/contact.page">Contact</a></li> </ul> </main> </div> )}


import _React from 'react'; import Head from 'next/head'; export default function HomePage() { return ( <div className="min-h-screen"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name="description" content="AI services,IT solutions,and micro SaaS products by Zion Tech Group." /> <link rel="canonical" href=""https": </Head> <main className="max-w-5xl mx-auto p-6"> <h1 className="text-3xl font-bold">Zion Tech Group</h1> <p className="mt-4 text-gray-700">AI services,IT solutions,and micro SaaS products.</p> <ul className="list-disc pl-6 mt-6 space-y-2"> <li><a className="text-blue-600 "hover": underline" href="/services.page">Services</a></li> <li><a className="text-blue-600 hover:underline" href="/ai-services.page">AI Services</a></li> <li><a className="text-blue-600 hover:underline" href="/contact.page">Contact</a></li> </ul> </main> </div> )}







import React from \'react\'; import Head from \'next/head\'; export default function HomePage() { return ( <div className=\"min-h-screen\"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name=\"description\" content=\"AI services,IT solutions,and micro SaaS products by Zion Tech Group.\" /> <link rel=\"canonical\" href=\""https\": </Head> <main className=\"max-w-5xl mx-auto p-6\"> <h1 className=\"text-3xl font-bold\">Zion Tech Group</h1> <p className=\"mt-4 text-gray-700\">AI services,IT solutions,and micro SaaS products.</p> <ul className=\"list-disc pl-6 mt-6 space-y-2\"> <li><a className=\"text-blue-600 \"hover\": underline\" href=\"/services.page\">Services</a></li> <li><a className=\"text-blue-600 hover:underline\" href=\"/ai-services.page\">AI Services</a></li> <li><a className=\"text-blue-600 hover:underline\" href=\"/contact.page\">Contact</a></li> </ul> </main> </div> )}
import _React from 'react'; import Head from 'next/head'; export default function HomePage() { return ( <div className="min-h-screen"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name="description" content="AI services,IT solutions,and micro SaaS products by Zion Tech Group." /> <link rel="canonical" href=""https": </Head> <main className="max-w-5xl mx-auto p-6"> <h1 className="text-3xl font-bold">Zion Tech Group</h1> <p className="mt-4 text-gray-700">AI services,IT solutions,and micro SaaS products.</p> <ul className="list-disc pl-6 mt-6 space-y-2"> <li><a className="text-blue-600 "hover": underline" href="/services.page">Services</a></li> <li><a className="text-blue-600 hover:underline" href="/ai-services.page">AI Services</a></li> <li><a className="text-blue-600 hover:underline" href="/contact.page">Contact</a></li> </ul> </main> </div> )}
import _React from 'react'; import Head from 'next/head'; export default function HomePage() { return ( <div className="min-h-screen"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name="description" content="AI services,IT solutions,and micro SaaS products by Zion Tech Group." /> <link rel="canonical" href=""https": </Head> <main className="max-w-5xl mx-auto p-6"> <h1 className="text-3xl font-bold">Zion Tech Group</h1> <p className="mt-4 text-gray-700">AI services,IT solutions,and micro SaaS products.</p> <ul className="list-disc pl-6 mt-6 space-y-2"> <li><a className="text-blue-600 "hover": underline" href="/services.page">Services</a></li> <li><a className="text-blue-600 hover:underline" href="/ai-services.page">AI Services</a></li> <li><a className="text-blue-600 hover:underline" href="/contact.page">Contact</a></li> </ul> </main> </div> )}

import _React from 'react'; import Head from 'next/head'; export default function HomePage() { return ( <div className="min-h-screen"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name="description" content="AI services,IT solutions,and micro SaaS products by Zion Tech Group." /> <link rel="canonical" href=""https": </Head> <main className="max-w-5xl mx-auto p-6"> <h1 className="text-3xl font-bold">Zion Tech Group</h1> <p className="mt-4 text-gray-700">AI services,IT solutions,and micro SaaS products.</p> <ul className="list-disc pl-6 mt-6 space-y-2"> <li><a className="text-blue-600 "hover": underline" href="/services.page">Services</a></li> <li><a className="text-blue-600 hover:underline" href="/ai-services.page">AI Services</a></li> <li><a className="text-blue-600 hover:underline" href="/contact.page">Contact</a></li> </ul> </main> </div> )}

import React from \'react\'; import Head from \'next/head\'; export default function HomePage() { return ( <div className=\"min-h-screen\"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name=\"description\" content=\"AI services,IT solutions,and micro SaaS products by Zion Tech Group.\" /> <link rel=\"canonical\" href=\""https\": </Head> <main className=\"max-w-5xl mx-auto p-6\"> <h1 className=\"text-3xl font-bold\">Zion Tech Group</h1> <p className=\"mt-4 text-gray-700\">AI services,IT solutions,and micro SaaS products.</p> <ul className=\"list-disc pl-6 mt-6 space-y-2\"> <li><a className=\"text-blue-600 \"hover\": underline\" href=\"/services.page\">Services</a></li> <li><a className=\"text-blue-600 hover:underline\" href=\"/ai-services.page\">AI Services</a></li> <li><a className=\"text-blue-600 hover:underline\" href=\"/contact.page\">Contact</a></li> </ul> </main> </div> )}
import _React from 'react'; import Head from 'next/head'; export default function HomePage() { return ( <div className="min-h-screen"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name="description" content="AI services,IT solutions,and micro SaaS products by Zion Tech Group." /> <link rel="canonical" href=""https": </Head> <main className="max-w-5xl mx-auto p-6"> <h1 className="text-3xl font-bold">Zion Tech Group</h1> <p className="mt-4 text-gray-700">AI services,IT solutions,and micro SaaS products.</p> <ul className="list-disc pl-6 mt-6 space-y-2"> <li><a className="text-blue-600 "hover": underline" href="/services.page">Services</a></li> <li><a className="text-blue-600 hover:underline" href="/ai-services.page">AI Services</a></li> <li><a className="text-blue-600 hover:underline" href="/contact.page">Contact</a></li> </ul> </main> </div> )}

=======
<<<<<<< HEAD
>>>>>>> origin/cursor/fix-netlify-build-and-merge-to-main-9f58
import React from \'react\'; import Head from \'next/head\'; export default function HomePage() { return ( <div className=\"min-h-screen\"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name=\"description\" content=\"AI services,IT solutions,and micro SaaS products by Zion Tech Group.\" /> <link rel=\"canonical\" href=\""https\": </Head> <main className=\"max-w-5xl mx-auto p-6\"> <h1 className=\"text-3xl font-bold\">Zion Tech Group</h1> <p className=\"mt-4 text-gray-700\">AI services,IT solutions,and micro SaaS products.</p> <ul className=\"list-disc pl-6 mt-6 space-y-2\"> <li><a className=\"text-blue-600 \"hover\": underline\" href=\"/services.page\">Services</a></li> <li><a className=\"text-blue-600 hover:underline\" href=\"/ai-services.page\">AI Services</a></li> <li><a className=\"text-blue-600 hover:underline\" href=\"/contact.page\">Contact</a></li> </ul> </main> </div> )}
import _React from 'react'; import Head from 'next/head'; export default function HomePage() { return ( <div className="min-h-screen"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name="description" content="AI services,IT solutions,and micro SaaS products by Zion Tech Group." /> <link rel="canonical" href=""https": </Head> <main className="max-w-5xl mx-auto p-6"> <h1 className="text-3xl font-bold">Zion Tech Group</h1> <p className="mt-4 text-gray-700">AI services,IT solutions,and micro SaaS products.</p> <ul className="list-disc pl-6 mt-6 space-y-2"> <li><a className="text-blue-600 "hover": underline" href="/services.page">Services</a></li> <li><a className="text-blue-600 hover:underline" href="/ai-services.page">AI Services</a></li> <li><a className="text-blue-600 hover:underline" href="/contact.page">Contact</a></li> </ul> </main> </div> )}
import _React from 'react'; import Head from 'next/head'; export default function HomePage() { return ( <div className="min-h-screen"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name="description" content="AI services,IT solutions,and micro SaaS products by Zion Tech Group." /> <link rel="canonical" href=""https": </Head> <main className="max-w-5xl mx-auto p-6"> <h1 className="text-3xl font-bold">Zion Tech Group</h1> <p className="mt-4 text-gray-700">AI services,IT solutions,and micro SaaS products.</p> <ul className="list-disc pl-6 mt-6 space-y-2"> <li><a className="text-blue-600 "hover": underline" href="/services.page">Services</a></li> <li><a className="text-blue-600 hover:underline" href="/ai-services.page">AI Services</a></li> <li><a className="text-blue-600 hover:underline" href="/contact.page">Contact</a></li> </ul> </main> </div> )}
import _React from 'react'; import Head from 'next/head'; export default function HomePage() { return ( <div className="min-h-screen"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name="description" content="AI services,IT solutions,and micro SaaS products by Zion Tech Group." /> <link rel="canonical" href=""https": </Head> <main className="max-w-5xl mx-auto p-6"> <h1 className="text-3xl font-bold">Zion Tech Group</h1> <p className="mt-4 text-gray-700">AI services,IT solutions,and micro SaaS products.</p> <ul className="list-disc pl-6 mt-6 space-y-2"> <li><a className="text-blue-600 "hover": underline" href="/services.page">Services</a></li> <li><a className="text-blue-600 hover:underline" href="/ai-services.page">AI Services</a></li> <li><a className="text-blue-600 hover:underline" href="/contact.page">Contact</a></li> </ul> </main> </div> )}
<<<<<<< HEAD
=======
=======
<<<<<<< HEAD
<<<<<<< HEAD
import _React from 'react'; import Head from 'next/head'; export default function HomePage() { return ( <div className="min-h-screen"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name="description" content="AI services,IT solutions,and micro SaaS products by Zion Tech Group." /> <link rel="canonical" href=""https": </Head> <main className="max-w-5xl mx-auto p-6"> <h1 className="text-3xl font-bold">Zion Tech Group</h1> <p className="mt-4 text-gray-700">AI services,IT solutions,and micro SaaS products.</p> <ul className="list-disc pl-6 mt-6 space-y-2"> <li><a className="text-blue-600 "hover": underline" href="/services.page">Services</a></li> <li><a className="text-blue-600 hover:underline" href="/ai-services.page">AI Services</a></li> <li><a className="text-blue-600 hover:underline" href="/contact.page">Contact</a></li> </ul> </main> </div> )}
=======
>>>>>>> origin/cursor/fix-netlify-build-and-merge-to-main-9f58
import React from \'react\'; import Head from \'next/head\'; export default function HomePage() { return ( <div className=\"min-h-screen\"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name=\"description\" content=\"AI services,IT solutions,and micro SaaS products by Zion Tech Group.\" /> <link rel=\"canonical\" href=\""https\": </Head> <main className=\"max-w-5xl mx-auto p-6\"> <h1 className=\"text-3xl font-bold\">Zion Tech Group</h1> <p className=\"mt-4 text-gray-700\">AI services,IT solutions,and micro SaaS products.</p> <ul className=\"list-disc pl-6 mt-6 space-y-2\"> <li><a className=\"text-blue-600 \"hover\": underline\" href=\"/services.page\">Services</a></li> <li><a className=\"text-blue-600 hover:underline\" href=\"/ai-services.page\">AI Services</a></li> <li><a className=\"text-blue-600 hover:underline\" href=\"/contact.page\">Contact</a></li> </ul> </main> </div> )}
import _React from 'react'; import Head from 'next/head'; export default function HomePage() { return ( <div className="min-h-screen"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name="description" content="AI services,IT solutions,and micro SaaS products by Zion Tech Group." /> <link rel="canonical" href=""https": </Head> <main className="max-w-5xl mx-auto p-6"> <h1 className="text-3xl font-bold">Zion Tech Group</h1> <p className="mt-4 text-gray-700">AI services,IT solutions,and micro SaaS products.</p> <ul className="list-disc pl-6 mt-6 space-y-2"> <li><a className="text-blue-600 "hover": underline" href="/services.page">Services</a></li> <li><a className="text-blue-600 hover:underline" href="/ai-services.page">AI Services</a></li> <li><a className="text-blue-600 hover:underline" href="/contact.page">Contact</a></li> </ul> </main> </div> )}
import React from \'react\'; import Head from \'next/head\'; export default function HomePage() { return ( <div className=\"min-h-screen\"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name=\"description\" content=\"AI services,IT solutions,and micro SaaS products by Zion Tech Group.\" /> <link rel=\"canonical\" href=\""https\": </Head> <main className=\"max-w-5xl mx-auto p-6\"> <h1 className=\"text-3xl font-bold\">Zion Tech Group</h1> <p className=\"mt-4 text-gray-700\">AI services,IT solutions,and micro SaaS products.</p> <ul className=\"list-disc pl-6 mt-6 space-y-2\"> <li><a className=\"text-blue-600 \"hover\": underline\" href=\"/services.page\">Services</a></li> <li><a className=\"text-blue-600 hover:underline\" href=\"/ai-services.page\">AI Services</a></li> <li><a className=\"text-blue-600 hover:underline\" href=\"/contact.page\">Contact</a></li> </ul> </main> </div> )}



import React from \'react\'; import Head from \'next/head\'; export default function HomePage() { return ( <div className=\"min-h-screen\"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name=\"description\" content=\"AI services,IT solutions,and micro SaaS products by Zion Tech Group.\" /> <link rel=\"canonical\" href=\""https\": </Head> <main className=\"max-w-5xl mx-auto p-6\"> <h1 className=\"text-3xl font-bold\">Zion Tech Group</h1> <p className=\"mt-4 text-gray-700\">AI services,IT solutions,and micro SaaS products.</p> <ul className=\"list-disc pl-6 mt-6 space-y-2\"> <li><a className=\"text-blue-600 \"hover\": underline\" href=\"/services.page\">Services</a></li> <li><a className=\"text-blue-600 hover:underline\" href=\"/ai-services.page\">AI Services</a></li> <li><a className=\"text-blue-600 hover:underline\" href=\"/contact.page\">Contact</a></li> </ul> </main> </div> )}
import _React from 'react'; import Head from 'next/head'; export default function HomePage() { return ( <div className="min-h-screen"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name="description" content="AI services,IT solutions,and micro SaaS products by Zion Tech Group." /> <link rel="canonical" href=""https": </Head> <main className="max-w-5xl mx-auto p-6"> <h1 className="text-3xl font-bold">Zion Tech Group</h1> <p className="mt-4 text-gray-700">AI services,IT solutions,and micro SaaS products.</p> <ul className="list-disc pl-6 mt-6 space-y-2"> <li><a className="text-blue-600 "hover": underline" href="/services.page">Services</a></li> <li><a className="text-blue-600 hover:underline" href="/ai-services.page">AI Services</a></li> <li><a className="text-blue-600 hover:underline" href="/contact.page">Contact</a></li> </ul> </main> </div> )}
<<<<<<< HEAD
import _React from 'react'; import Head from 'next/head'; export default function HomePage() { return ( <div className="min-h-screen"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name="description" content="AI services,IT solutions,and micro SaaS products by Zion Tech Group." /> <link rel="canonical" href=""https": </Head> <main className="max-w-5xl mx-auto p-6"> <h1 className="text-3xl font-bold">Zion Tech Group</h1> <p className="mt-4 text-gray-700">AI services,IT solutions,and micro SaaS products.</p> <ul className="list-disc pl-6 mt-6 space-y-2"> <li><a className="text-blue-600 "hover": underline" href="/services.page">Services</a></li> <li><a className="text-blue-600 hover:underline" href="/ai-services.page">AI Services</a></li> <li><a className="text-blue-600 hover:underline" href="/contact.page">Contact</a></li> </ul> </main> </div> )}
origin/cursor/integrate-build-improve-and-re-verify-c7b5
import _React from 'react'; import Head from 'next/head'; export default function HomePage() { return ( <div className="min-h-screen"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name="description" content="AI services,IT solutions,and micro SaaS products by Zion Tech Group." /> <link rel="canonical" href=""https": </Head> <main className="max-w-5xl mx-auto p-6"> <h1 className="text-3xl font-bold">Zion Tech Group</h1> <p className="mt-4 text-gray-700">AI services,IT solutions,and micro SaaS products.</p> <ul className="list-disc pl-6 mt-6 space-y-2"> <li><a className="text-blue-600 "hover": underline" href="/services.page">Services</a></li> <li><a className="text-blue-600 hover:underline" href="/ai-services.page">AI Services</a></li> <li><a className="text-blue-600 hover:underline" href="/contact.page">Contact</a></li> </ul> </main> </div> )}
import _React from 'react'; import Head from 'next/head'; export default function HomePage() { return ( <div className="min-h-screen"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name="description" content="AI services,IT solutions,and micro SaaS products by Zion Tech Group." /> <link rel="canonical" href=""https": </Head> <main className="max-w-5xl mx-auto p-6"> <h1 className="text-3xl font-bold">Zion Tech Group</h1> <p className="mt-4 text-gray-700">AI services,IT solutions,and micro SaaS products.</p> <ul className="list-disc pl-6 mt-6 space-y-2"> <li><a className="text-blue-600 "hover": underline" href="/services.page">Services</a></li> <li><a className="text-blue-600 hover:underline" href="/ai-services.page">AI Services</a></li> <li><a className="text-blue-600 hover:underline" href="/contact.page">Contact</a></li> </ul> </main> </div> )}
import React from \'react\'; import Head from \'next/head\'; export default function HomePage() { return ( <div className=\"min-h-screen\"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name=\"description\" content=\"AI services,IT solutions,and micro SaaS products by Zion Tech Group.\" /> <link rel=\"canonical\" href=\""https\": </Head> <main className=\"max-w-5xl mx-auto p-6\"> <h1 className=\"text-3xl font-bold\">Zion Tech Group</h1> <p className=\"mt-4 text-gray-700\">AI services,IT solutions,and micro SaaS products.</p> <ul className=\"list-disc pl-6 mt-6 space-y-2\"> <li><a className=\"text-blue-600 \"hover\": underline\" href=\"/services.page\">Services</a></li> <li><a className=\"text-blue-600 hover:underline\" href=\"/ai-services.page\">AI Services</a></li> <li><a className=\"text-blue-600 hover:underline\" href=\"/contact.page\">Contact</a></li> </ul> </main> </div> )}
ursor/add-new-services-and-deploy-updates-0462
ursor/fix-syntax-push-and-merge-to-main-40de



import _React from 'react'; import Head from 'next/head'; export default function HomePage() { return ( <div className="min-h-screen"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name="description" content="AI services,IT solutions,and micro SaaS products by Zion Tech Group." /> <link rel="canonical" href=""https": </Head> <main className="max-w-5xl mx-auto p-6"> <h1 className="text-3xl font-bold">Zion Tech Group</h1> <p className="mt-4 text-gray-700">AI services,IT solutions,and micro SaaS products.</p> <ul className="list-disc pl-6 mt-6 space-y-2"> <li><a className="text-blue-600 "hover": underline" href="/services.page">Services</a></li> <li><a className="text-blue-600 hover:underline" href="/ai-services.page">AI Services</a></li> <li><a className="text-blue-600 hover:underline" href="/contact.page">Contact</a></li> </ul> </main> </div> )}

import React from \'react\'; import Head from \'next/head\'; export default function HomePage() { return ( <div className=\"min-h-screen\"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name=\"description\" content=\"AI services,IT solutions,and micro SaaS products by Zion Tech Group.\" /> <link rel=\"canonical\" href=\""https\": </Head> <main className=\"max-w-5xl mx-auto p-6\"> <h1 className=\"text-3xl font-bold\">Zion Tech Group</h1> <p className=\"mt-4 text-gray-700\">AI services,IT solutions,and micro SaaS products.</p> <ul className=\"list-disc pl-6 mt-6 space-y-2\"> <li><a className=\"text-blue-600 \"hover\": underline\" href=\"/services.page\">Services</a></li> <li><a className=\"text-blue-600 hover:underline\" href=\"/ai-services.page\">AI Services</a></li> <li><a className=\"text-blue-600 hover:underline\" href=\"/contact.page\">Contact</a></li> </ul> </main> </div> )}
import _React from 'react'; import Head from 'next/head'; export default function HomePage() { return ( <div className="min-h-screen"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name="description" content="AI services,IT solutions,and micro SaaS products by Zion Tech Group." /> <link rel="canonical" href=""https": </Head> <main className="max-w-5xl mx-auto p-6"> <h1 className="text-3xl font-bold">Zion Tech Group</h1> <p className="mt-4 text-gray-700">AI services,IT solutions,and micro SaaS products.</p> <ul className="list-disc pl-6 mt-6 space-y-2"> <li><a className="text-blue-600 "hover": underline" href="/services.page">Services</a></li> <li><a className="text-blue-600 hover:underline" href="/ai-services.page">AI Services</a></li> <li><a className="text-blue-600 hover:underline" href="/contact.page">Contact</a></li> </ul> </main> </div> )}


import _React from 'react'; import Head from 'next/head'; export default function HomePage() { return ( <div className="min-h-screen"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name="description" content="AI services,IT solutions,and micro SaaS products by Zion Tech Group." /> <link rel="canonical" href=""https": </Head> <main className="max-w-5xl mx-auto p-6"> <h1 className="text-3xl font-bold">Zion Tech Group</h1> <p className="mt-4 text-gray-700">AI services,IT solutions,and micro SaaS products.</p> <ul className="list-disc pl-6 mt-6 space-y-2"> <li><a className="text-blue-600 "hover": underline" href="/services.page">Services</a></li> <li><a className="text-blue-600 hover:underline" href="/ai-services.page">AI Services</a></li> <li><a className="text-blue-600 hover:underline" href="/contact.page">Contact</a></li> </ul> </main> </div> )}





import _React from 'react'; import Head from 'next/head'; export default function HomePage() { return ( <div className="min-h-screen"> <Head> <title>Zion Tech Group — AI,IT & Micro SaaS</title> <meta name="description" content="AI services,IT solutions,and micro SaaS products by Zion Tech Group." /> <link rel="canonical" href=""https": </Head> <main className="max-w-5xl mx-auto p-6"> <h1 className="text-3xl font-bold">Zion Tech Group</h1> <p className="mt-4 text-gray-700">AI services,IT solutions,and micro SaaS products.</p> <ul className="list-disc pl-6 mt-6 space-y-2"> <li><a className="text-blue-600 "hover": underline" href="/services.page">Services</a></li> <li><a className="text-blue-600 hover:underline" href="/ai-services.page">AI Services</a></li> <li><a className="text-blue-600 hover:underline" href="/contact.page">Contact</a></li> </ul> </main> </div> )}

=======
>>>>>>> d0b4cabda824e2db66cecb53192832d7e749a326
>>>>>>> f239ba8ab20235073506b800efb123c18d8bf440
>>>>>>> 3f460500b361cb7cf5c95e8c53ca967467908705
>>>>>>> origin/cursor/fix-netlify-build-and-merge-to-main-9f58
