import Head from 'next/head';

export default function Page() {
  return (
    <div className="min-h-screen bg-slate-950 text-white">
      <Head>
        <title>Case Study — Autonomous Reports</title>
        <meta name="description" content="Pragmatic case scenario inspired by live site signals." />
        <meta property="og:title" content="Case Study — Autonomous Reports" />
        <meta property="og:description" content="Pragmatic case scenario inspired by live site signals." />
        <meta name="twitter:card" content="summary_large_image" />
      </Head>
      <main className="container mx-auto px-6 py-12 prose prose-invert">
        <h1 className="text-3xl font-extrabold">Case Study — Autonomous Reports</h1>
        <p className="mt-6 text-white/60 text-sm">Auto-generated by Cloud Deep Research Factory.</p>
      </main>
    </div>
  );
}
