nodeLinker: node-modules
enableGlobalCache: false
enableNetwork: true
enableTelemetry: false
enableProgressBars: false
enableImmutableInstalls: false
networkTimeout: 60000
networkConcurrency: 1
ignoreEngines: true
ignorePlatform: true