nodeLinker: node-modules
<<<<<<< HEAD
enableGlobalCache: true
=======
enableGlobalCache: false
>>>>>>> origin/backup-main-20250924-182607
enableNetwork: true
enableTelemetry: false
enableProgressBars: false
networkConcurrency: 1

