import Head from 'next/head';

export default function Page() {
  return (
    <div className="min-h-screen bg-slate-950 text-white">
      <Head>
        <title>Guide — Techcrunch Pebble Implementation</title>
        <meta name="description" content="Step-by-step guidance derived from live research signals." />
        <meta property="og:title" content="Guide — Techcrunch Pebble Implementation" />
        <meta property="og:description" content="Step-by-step guidance derived from live research signals." />
        <meta name="twitter:card" content="summary_large_image" />
      </Head>
      <main className="container mx-auto px-6 py-12 prose prose-invert">
        <h1 className="text-3xl font-extrabold">Guide — Techcrunch Pebble Implementation</h1>
        <p className="mt-6 text-white/60 text-sm">Auto-generated by Cloud Deep Research Factory.</p>
      </main>
    </div>
  );
}
