'use client''''''
import { useState, useEffect} from 'react''''''
import { HardDrive } from 'lucide-react''''''
import { useState, useEffect } from 'react''''''
import { HardDrive } from 'lucide-react''''''
      lcpObserver.observe({ entryTypes: """""['largest-contentful-paint''''"'"}"'
      fidObserver.observe({ entryTypes: ['first-input'''"'"}"'"'
      clsObserver.observe({ entryTypes: ['layout-shift''"'"}"'"'"'
      fcpObserver.observe({ entryTypes: ['paint'"'"}"'"'"'"'
      navigationObserver.observe({ entryTypes: ['navigation'"}'"'"'"'"'
      if ('connection}'"'"'"'"'"'