<<<<<<< HEAD
import React from 'react',
=======
import React, { useState, useRef, useEffect } from 'react'; import { motion  } from 'framer-motion'; interface LazyImageProps {
 src: string; alt: string; className?: string; width?: number; height?: number; placeholder?: string; priority?: boolean; onLoad?: () => void; onError?: () => void;   
} export const LazyImage: Reac t.FC<LazyImageProps> = ({ src, alt, className = '', width, height, placeholder = 'data: imag e/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjZjNmNGY2Ii8+PC9zdmc+', priority = false, onLoad, onError }) => { const [isLoaded, setIsLoaded] = useState<any>(false); const [isInView, setIsInView] = useState<any>(priority); const [hasError, setHasError] = useState<any>(false); const imgRef = useRef<HTMLImageElement>(null); useEffect(() => { if(priority) return; const observer = new IntersectionObserver(([entry]) => { if(entry.isIntersecting) { setIsInView(true); observer.disconnect(); } }, { threshold: 0.1, rootMargin: '50px' } ); if(imgRef.current) { observer.observe(imgRef.current); } return () => observer.disconnect(); }, [priority]); const handleLoad = (props: any) => { setIsLoaded(true); onLoad?.(); }; const handleError = (props: any) => { setHasError(true); onError?.(); }; return (<div ref={imgRef} className={`relative overflow-hidden ${className}`} style={{ width, height }} > {} {!isLoaded && !hasError && ( <motion.div className="absolute inset-0 bg-gray-200 animate-pulse flex items-center justify-center" initial={{ opacity: 1   }} animate={{ opacity: isLoade d ? 0 : 1   }} transition={{ duration: 0.3   }} > <div className="w-8 h-8 border-2 border-gray-300 border-t-blue-500 rounded-full animate-spin"  /> </motion.div> )} {} {hasError && ( <div className="absolute inset-0 bg-gray-100 flex items-center justify-center"> <div className="text-center text-gray-500"> <svg className="w-12 h-12 mx-auto mb-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"> <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"  /> </svg> <p className="text-sm">Failed to load image</p> </div> </div> )} {} {isInView && !hasError && ( <motion.img src={src} alt={alt} className={`w-full h-full object-cover transition-opacity duration-300 ${isLoaded ? 'opacity-100' : 'opacity-0' }`} onLoad={handleLoad} onError={handleError} loading={priority ? 'eager' : 'lazy'} decoding="async" /> )} </div> ); };
>>>>>>> 9de841a86934bc4a418b22e98c02b56496dc2aa9

const LazyImage: React.FC = () => {,
  return (,
    <div className="p-6 bg-gradient-to-br from-blue-900 to-purple-900 text-white rounded-lg">,
      <h3 className="text-xl font-bold mb-4">LazyImage</h3>,
      <p className="text-gray-300">Revolutionary technology component</p>,
    </div>,
  ),};
export default LazyImage;