'use client";"
import Footer from './Footer";"
import React from 'react";"
import { Helmet } from 'react-helmet-async";"
import { ArrowRight, Brain } from 'lucide-react";"
import { CheckCircle, ArrowRight, Phone, Mail, MapPin, Zap, Shield, Brain, Globe } from 'lucide-react";"
import { Phone, Mail, ArrowRight } from 'lucide-react";"
const OptimizedImage: "React.FC<OptimizedImageProps> = ({ className = '"</OptimizedImageProps>;"
export default OptimizedImage;","
})'"