<<<<<<< HEAD
<<<<<<< HEAD
=======
import _React from 'react';'''; import { cn } from '@/lib/utils'; const Avatar = _React.forwardRef(({ className,...props },ref) => (; <div>Broken JSX</div> /> ));'; Avatar.displayName = 'Avatar';'; const AvatarImage = _React.forwardRef(''; ({ className,src,alt = ',...props },ref) => (; <div>Broken JSX</div> />'; )''; );'''; AvatarImage.displayName = 'AvatarImage'; const AvatarFallback = _React.forwardRef(({ className,...props },ref) => (; <div>Broken JSX</div> /> ));'; AvatarFallback.displayName = 'AvatarFallback'; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback };
>>>>>>> origin/cursor/fix-syntax-push-and-merge-to-main-8452
=======
import _React from 'react';'''; import { cn } from '@/lib/utils'; const Avatar = _React.forwardRef(({ className,...props },ref) => (<div>Broken JSX</div> /> ))'; Avatar.displayName = 'Avatar';'; const AvatarImage = _React.forwardRef(''; ({ className,src,alt = ',...props },ref) => (<div>Broken JSX</div> />'; )''; )'''; AvatarImage.displayName = 'AvatarImage'; const AvatarFallback = _React.forwardRef(({ className,...props },ref) => (<div>Broken JSX</div> /> ))'; AvatarFallback.displayName = 'AvatarFallback'; export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }import React from \'react\';\''\'; import { cn } from \'@/lib/utils\'; const Avatar = React && React.forwardRef(({ className,...props },ref) => (<div>Broken JSX</div> /> ))\'; Avatar && Avatar.displayName = \'Avatar\';\'; const AvatarImage = React && React.forwardRef(\''; ({ className,src,alt = \'',...props },ref) => (<div>Broken JSX</div> />\'; )\''; )\''\'; AvatarImage && AvatarImage.displayName = \'AvatarImage\'; const AvatarFallback = React && React.forwardRef(({ className,...props },ref) => (<div>Broken JSX</div> /> ))\'; AvatarFallback && AvatarFallback.displayName = \'AvatarFallback\'; export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }const React from "react";"""; import { cn } from "@/lib/utils"; const Avatar = React && React.forwardRef(({ className,.props },ref) => (<div>Broken JSX</div> /> ))"; Avatar && Avatar.displayName = "Avatar";"; const AvatarImage = React && React.forwardRef(""; ({ className,src,alt = "",.props },ref) => (<div>Broken JSX</div> />"; )""; )"""; AvatarImage && AvatarImage.displayName = "AvatarImage"; const AvatarFallback = React && React.forwardRef(({ className,.props },ref) => (<div>Broken JSX</div> /> ))"; AvatarFallback && AvatarFallback.displayName = "AvatarFallback"; export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }''";
ursor/automate-test-improve-and-merge-code-646c;
import React from \'react\';\''\'; import { cn } from \'@/lib/utils\'; const Avatar = React.forwardRef(({ className,...props },ref) => (<div>Broken JSX</div> /> ))\'; Avatar.displayName = \'Avatar\';\'; const AvatarImage = React.forwardRef(\''; ({ className,src,alt = \'',...props },ref) => (<div>Broken JSX</div> />\'; )\''; )\''\'; AvatarImage.displayName = \'AvatarImage\'; const AvatarFallback = React.forwardRef(({ className,...props },ref) => (<div>Broken JSX</div> /> ))\'; AvatarFallback.displayName = \'AvatarFallback\'; export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }const React from "react";"""; import { cn } from "@/lib/utils"; const Avatar = React.forwardRef(({ className,.props },ref) => (<div>Broken JSX</div> /> ))"; Avatar.displayName = "Avatar";"; const AvatarImage = React.forwardRef(""; ({ className,src,alt = "",.props },ref) => (<div>Broken JSX</div> />"; )""; )"""; AvatarImage.displayName = "AvatarImage"; const AvatarFallback = React.forwardRef(({ className,.props },ref) => (<div>Broken JSX</div> /> ))"; AvatarFallback.displayName = "AvatarFallback"; export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }''";
ursor/automate-test-improve-and-merge-code-646c;
const React from "react";"""; import { cn } from "@/lib/utils"; const Avatar = React.forwardRef(({ className,.props },ref) => (<div>Broken JSX</div> /> ))"; Avatar.displayName = "Avatar";"; const AvatarImage = React.forwardRef(""; ({ className,src,alt = "",.props },ref) => (<div>Broken JSX</div> />"; )""; )"""; AvatarImage.displayName = "AvatarImage"; const AvatarFallback = React.forwardRef(({ className,.props },ref) => (<div>Broken JSX</div> /> ))"; AvatarFallback.displayName = "AvatarFallback"; export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }export { Avatar,AvatarImage,AvatarFallback }''";
import _React from 'react';'''; import { cn } from '@/lib/utils'; const Avatar = _React.forwardRef(({ className,...props },ref) => (; <div>Broken JSX</div> /> ));'; Avatar.displayName = 'Avatar';'; const AvatarImage = _React.forwardRef(''; ({ className,src,alt = ',...props },ref) => (; <div>Broken JSX</div> />'; )''; );'''; AvatarImage.displayName = 'AvatarImage'; const AvatarFallback = _React.forwardRef(({ className,...props },ref) => (; <div>Broken JSX</div> /> ));'; AvatarFallback.displayName = 'AvatarFallback'; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback };
>>>>>>> origin/cursor/fix-netlify-build-and-merge-to-main-2a0c
import React from \'react\';\''\'; import { cn } from \'@/lib/utils\'; const Avatar = React && React.forwardRef(({ className,...props },ref) => (; <div>Broken JSX</div> /> ));\'; Avatar && Avatar.displayName = \'Avatar\';\'; const AvatarImage = React && React.forwardRef(\''; ({ className,src,alt = \'',...props },ref) => (; <div>Broken JSX</div> />\'; )\''; );\''\'; AvatarImage && AvatarImage.displayName = \'AvatarImage\'; const AvatarFallback = React && React.forwardRef(({ className,...props },ref) => (; <div>Broken JSX</div> /> ));\'; AvatarFallback && AvatarFallback.displayName = \'AvatarFallback\'; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback };
const React from "react";"""; import { cn } from "@/lib/utils"; const Avatar = React && React.forwardRef(({ className,.props },ref) => (; <div>Broken JSX</div> /> ));"; Avatar && Avatar.displayName = "Avatar";"; const AvatarImage = React && React.forwardRef(""; ({ className,src,alt = "",.props },ref) => (; <div>Broken JSX</div> />"; )""; );"""; AvatarImage && AvatarImage.displayName = "AvatarImage"; const AvatarFallback = React && React.forwardRef(({ className,.props },ref) => (; <div>Broken JSX</div> /> ));"; AvatarFallback && AvatarFallback.displayName = "AvatarFallback"; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback };''"

import _React from 'react';'''; import { cn } from '@/lib/utils'; const Avatar = _React && _React.forwardRef(({ className,...props },ref) => (; <div>Broken JSX</div> /> ));'; Avatar && Avatar.displayName = 'Avatar';'; const AvatarImage = _React && _React.forwardRef(''; ({ className,src,alt = ',...props },ref) => (; <div>Broken JSX</div> />'; )''; );'''; AvatarImage && AvatarImage.displayName = 'AvatarImage'; const AvatarFallback = _React && _React.forwardRef(({ className,...props },ref) => (; <div>Broken JSX</div> /> ));'; AvatarFallback && AvatarFallback.displayName = 'AvatarFallback'; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback };

<<<<<<< HEAD
<<<<<<< HEAD
=======
import _React from 'react';'''; import { cn } from '@/lib/utils'; const Avatar = _React.forwardRef(({ className,...props },ref) => (; <div>Broken JSX</div> /> ));'; Avatar.displayName = 'Avatar';'; const AvatarImage = _React.forwardRef(''; ({ className,src,alt = ',...props },ref) => (; <div>Broken JSX</div> />'; )''; );'''; AvatarImage.displayName = 'AvatarImage'; const AvatarFallback = _React.forwardRef(({ className,...props },ref) => (; <div>Broken JSX</div> /> ));'; AvatarFallback.displayName = 'AvatarFallback'; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback };
>>>>>>> origin/cursor/fix-syntax-push-and-merge-to-main-8452
=======
>>>>>>> origin/cursor/fix-netlify-build-and-merge-to-main-2a0c
import React from \'react\';\''\'; import { cn } from \'@/lib/utils\'; const Avatar = React.forwardRef(({ className,...props },ref) => (; <div>Broken JSX</div> /> ));\'; Avatar.displayName = \'Avatar\';\'; const AvatarImage = React.forwardRef(\''; ({ className,src,alt = \'',...props },ref) => (; <div>Broken JSX</div> />\'; )\''; );\''\'; AvatarImage.displayName = \'AvatarImage\'; const AvatarFallback = React.forwardRef(({ className,...props },ref) => (; <div>Broken JSX</div> /> ));\'; AvatarFallback.displayName = \'AvatarFallback\'; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback };
const React from "react";"""; import { cn } from "@/lib/utils"; const Avatar = React.forwardRef(({ className,.props },ref) => (; <div>Broken JSX</div> /> ));"; Avatar.displayName = "Avatar";"; const AvatarImage = React.forwardRef(""; ({ className,src,alt = "",.props },ref) => (; <div>Broken JSX</div> />"; )""; );"""; AvatarImage.displayName = "AvatarImage"; const AvatarFallback = React.forwardRef(({ className,.props },ref) => (; <div>Broken JSX</div> /> ));"; AvatarFallback.displayName = "AvatarFallback"; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback }; export { Avatar,AvatarImage,AvatarFallback };''"
