import Head from 'next/head';

export default function Page() {
  return (
    <div className="min-h-screen bg-slate-950 text-white">
      <Head>
        <title>Playbook — Autonomous Delivery</title>
        <meta name="description" content="A practical step-by-step playbook for reliable autonomous delivery." />
        <meta property="og:title" content="Playbook — Autonomous Delivery" />
        <meta property="og:description" content="A practical step-by-step playbook for reliable autonomous delivery." />
        <meta name="twitter:card" content="summary_large_image" />
      </Head>
      <main className="container mx-auto px-6 py-12 prose prose-invert">
        <h1 className="text-3xl font-extrabold">Playbook — Autonomous Delivery</h1>
        <div className="mt-4" dangerouslySetInnerHTML={{ __html: "<p>Signal source: <a class=\"text-cyan-300 underline\" href=\"https://ziontechgroup.com\" target=\"_blank\" rel=\"noopener\">https://ziontechgroup.com</a></p><h2>Purpose</h2><p>Operational steps to execute reliably with measurable outcomes.</p><h2>Checklist</h2><ol><li>Define objectives, KPIs, and guardrails.</li><li>Inventory data, models, tools, and constraints.</li><li>Design evaluation and feedback loops upfront.</li><li>Implement smallest viable slice with telemetry.</li><li>Iterate, measure, and harden for production.</li></ol><h2>Notes</h2><p class=\"text-white/75\"></p>" }} />
        <p className="mt-6 text-white/60 text-sm">Auto-generated by Cloud Playbook Factory.</p>
      </main>
    </div>
  );
}
