const WebDevelopment: NextPage = () => {
  return (;
    <Layout;
      title="Web Development Services - Zion Tech Group";
      description="Modern, responsive web applications built with cutting-edge technologies. Full-stack development, e-commerce, and custom web solutions.">;
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-blue-900 via-purple-900 to-indigo-900 text-white py-20">;
        <div className="container mx-auto px-4 text-center">;
          <h1 className="text-5xl md:text-6xl font-bold mb-6">;
            Web;
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-400"> Development</span>;
          </h1>;
          <p className="text-xl md:text-2xl mb-8 max-w-4xl mx-auto text-gray-200">;
            Modern, responsive web applications built with cutting-edge technologies. ;
            From simple websites to complex web applications, we deliver exceptional user experiences.;
          </p>;

          <div className="flex flex-col sm:flex-row justify-center gap-4">;
            <Link href="/contact" className="bg-blue-600 hover:bg-blue-700 text-white px-8 py-4 rounded-lg font-semibold transition-colors cursor-pointer inline-block text-lg">;
              Start Your Web Project;
            </Link>;
            <Link href="/services" className="bg-transparent border-2 border-white text-white hover:bg-white hover:text-blue-900 px-8 py-4 rounded-lg font-semibold transition-colors cursor-pointer inline-block text-lg">;
              View All Services;
            </Link>;
          </div>;
        </div>;
      </section>;

      {/* Web Development Services */}
      <section className="py-20 bg-white">;
        <div className="container mx-auto px-4">;
          <div className="text-center mb-16">;
            <h2 className="text-4xl font-bold text-gray-900 mb-4">Our Web Development Services</h2>;
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">;
              We create modern, scalable web applications that deliver exceptional user experiences ;
              and drive business growth across all industries.;
            </p>;
          </div>;

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">;
            <div className="bg-white rounded-lg p-8 shadow-lg hover:shadow-xl transition-shadow border border-gray-100">;
              <div className="w-16 h-16 bg-blue-100 rounded-lg flex items-center justify-center mb-6">;
                <Code className="w-8 h-8 text-blue-600" />;
              </div>;
              <h3 className="text-xl font-semibold mb-4">Frontend Development</h3>;
              <p className="text-gray-600 mb-4">;
                Modern, responsive user interfaces built with the latest frontend technologies.;
              </p>;
              <ul className="space-y-2">;
                <li className="flex items-center text-sm text-gray-600">;
                  <CheckCircle className="w-4 h-4 text-green-500 mr-2 flex-shrink-0" />;
                  React & Next.js;
                </li>;
                <li className="flex items-center text-sm text-gray-600">;
                  <CheckCircle className="w-4 h-4 text-green-500 mr-2 flex-shrink-0" />;
                  Vue.js & Nuxt.js;
                </li>;
                <li className="flex items-center text-sm text-gray-600">;
                  <CheckCircle className="w-4 h-4 text-green-500 mr-2 flex-shrink-0" />;
                  Angular & TypeScript;
                </li>;
              </ul>;
            </div>;

            <div className="bg-white rounded-lg p-8 shadow-lg hover:shadow-xl transition-shadow border border-gray-100">;
              <div className="w-16 h-16 bg-purple-100 rounded-lg flex items-center justify-center mb-6">;
                <Globe className="w-8 h-8 text-purple-600" />;
              </div>;
              <h3 className="text-xl font-semibold mb-4">Backend Development</h3>;
              <p className="text-gray-600 mb-4">;
                Robust server-side applications and APIs built for scalability and performance.;
              </p>;
              <ul className="space-y-2">;
                <li className="flex items-center text-sm text-gray-600">;
                  <CheckCircle className="w-4 h-4 text-green-500 mr-2 flex-shrink-0" />;
                  Node.js & Express;
                </li>;
                <li className="flex items-center text-sm text-gray-600">;
                  <CheckCircle className="w-4 h-4 text-green-500 mr-2 flex-shrink-0" />;
                  Python & Django;
                </li>;
                <li className="flex items-center text-sm text-gray-600">;
                  <CheckCircle className="w-4 h-4 text-green-500 mr-2 flex-shrink-0" />;
                  RESTful APIs;
                </li>;
              </ul>;
            </div>;

            <div className="bg-white rounded-lg p-8 shadow-lg hover:shadow-xl transition-shadow border border-gray-100">;
              <div className="w-16 h-16 bg-green-100 rounded-lg flex items-center justify-center mb-6">;
                <Smartphone className="w-8 h-8 text-green-600" />;
              </div>;
              <h3 className="text-xl font-semibold mb-4">Responsive Design</h3>;
              <p className="text-gray-600 mb-4">;
                Mobile-first, responsive designs that work perfectly on all devices and screen sizes.;
              </p>;
              <ul className="space-y-2">;
                <li className="flex items-center text-sm text-gray-600">;
                  <CheckCircle className="w-4 h-4 text-green-500 mr-2 flex-shrink-0" />;
                  Mobile-First Design;
                </li>;
                <li className="flex items-center text-sm text-gray-600">;
                  <CheckCircle className="w-4 h-4 text-green-500 mr-2 flex-shrink-0" />;
                  Cross-Browser Compatibility;
                </li>;
                <li className="flex items-center text-sm text-gray-600">;
                  <CheckCircle className="w-4 h-4 text-green-500 mr-2 flex-shrink-0" />;
                  Progressive Web Apps;
                </li>;
              </ul>;
            </div>;

            <div className="bg-white rounded-lg p-8 shadow-lg hover:shadow-xl transition-shadow border border-gray-100">;
              <div className="w-16 h-16 bg-orange-100 rounded-lg flex items-center justify-center mb-6">;
                <Zap className="w-8 h-8 text-orange-600" />;
              </div>;
              <h3 className="text-xl font-semibold mb-4">E-commerce Solutions</h3>;
              <p className="text-gray-600 mb-4">;
                Custom e-commerce platforms and online stores that drive sales and conversions.;
              </p>;
              <ul className="space-y-2">;
                <li className="flex items-center text-sm text-gray-600">;
                  <CheckCircle className="w-4 h-4 text-green-500 mr-2 flex-shrink-0" />;
                  Custom E-commerce;
                </li>;
                <li className="flex items-center text-sm text-gray-600">;
                  <CheckCircle className="w-4 h-4 text-green-500 mr-2 flex-shrink-0" />;
                  Payment Integration;
                </li>;
                <li className="flex items-center text-sm text-gray-600">;
                  <CheckCircle className="w-4 h-4 text-green-500 mr-2 flex-shrink-0" />;
                  Inventory Management;
                </li>;
              </ul>;
            </div>;

            <div className="bg-white rounded-lg p-8 shadow-lg hover:shadow-xl transition-shadow border border-gray-100">;
              <div className="w-16 h-16 bg-red-100 rounded-lg flex items-center justify-center mb-6">;
                <Shield className="w-8 h-8 text-red-600" />;
              </div>;
              <h3 className="text-xl font-semibold mb-4">Web Security</h3>;
              <p className="text-gray-600 mb-4">;
                Comprehensive security measures to protect your web applications and user data.;
              </p>;
              <ul className="space-y-2">;
                <li className="flex items-center text-sm text-gray-600">;
                  <CheckCircle className="w-4 h-4 text-green-500 mr-2 flex-shrink-0" />;
                  SSL/TLS Certificates;
                </li>;
                <li className="flex items-center text-sm text-gray-600">;
                  <CheckCircle className="w-4 h-4 text-green-500 mr-2 flex-shrink-0" />;
                  Authentication & Authorization;
                </li>;
                <li className="flex items-center text-sm text-gray-600">;
                  <CheckCircle className="w-4 h-4 text-green-500 mr-2 flex-shrink-0" />;
                  Security Audits;
                </li>;
              </ul>;
            </div>;

            <div className="bg-white rounded-lg p-8 shadow-lg hover:shadow-xl transition-shadow border border-gray-100">;
              <div className="w-16 h-16 bg-indigo-100 rounded-lg flex items-center justify-center mb-6">;
                <Award className="w-8 h-8 text-indigo-600" />;
              </div>;
              <h3 className="text-xl font-semibold mb-4">Performance Optimization</h3>;
              <p className="text-gray-600 mb-4">;
                Optimized web applications that load fast and provide excellent user experiences.;
              </p>;
              <ul className="space-y-2">;
                <li className="flex items-center text-sm text-gray-600">;
                  <CheckCircle className="w-4 h-4 text-green-500 mr-2 flex-shrink-0" />;
                  Speed Optimization;
                </li>;
                <li className="flex items-center text-sm text-gray-600">;
                  <CheckCircle className="w-4 h-4 text-green-500 mr-2 flex-shrink-0" />;
                  SEO Optimization;
                </li>;
                <li className="flex items-center text-sm text-gray-600">;
                  <CheckCircle className="w-4 h-4 text-green-500 mr-2 flex-shrink-0" />;
                  Core Web Vitals;
                </li>;
              </ul>;
            </div>;
          </div>;
        </div>;
      </section>;