import Head from 'next/head';

export default function Page(){
  return (
    <div className="min-h-screen bg-slate-950 text-white">
      <Head>
        <title>Reference Architecture — Autonomous Content Mesh</title>
        <meta name="description" content="High-level blueprint for an autonomous content mesh with evaluation-in-the-loop." />
        <meta property="og:title" content="Reference Architecture — Autonomous Content Mesh" />
        <meta property="og:description" content="High-level blueprint for an autonomous content mesh with evaluation-in-the-loop." />
        <meta name="twitter:card" content="summary_large_image" />
      </Head>
      <main className="container mx-auto px-6 py-12 prose prose-invert">
        <h1 className="text-3xl font-extrabold">Reference Architecture — Autonomous Content Mesh</h1>
        <div className="mt-4" dangerouslySetInnerHTML={{ __html: `${body}` }} />
        <p className="mt-6 text-white/60 text-sm">Auto-generated by Cloud Blueprint Factory.</p>
      </main>
    </div>
  );
}
