<<<<<<< HEAD
import { NextApiRequest, NextApiResponse } from 'next';
import { ApiScope } from '../../../utils/devportal/types';
=======
<<<<<<< HEAD
import { NextApiRequest, NextApiResponse  } from 'next';
import { ApiScope  } from '../../../utils/devportal/types';
=======
import { NextApiRequest, NextApiResponse } from 'next';
import { ApiScope } from '../../../utils/devportal/types';
>>>>>>> 24132684af15a4d83201b2a91ee50324edfabedc
>>>>>>> origin/resolved-merge-conflicts
import { { createApiKey, getUserIdFromRequest }, { generateApiToken } } from '../../../utils/devportal/auth';
import { getApiKeys, saveApiKeys } from '../../../utils/devportal/storage';
export default function handler('req': NextApiRequest, 'res': NextApiResponse) {
  const userId = getUserIdFromRequest(req);
  if (req.method === 'GET') {
    const keys = getApiKeys().filter((k) => k.userId === userId && !k.revokedAt);
    return res.status(200).json({ data: keys })}
  if (req.method === 'POST') {
    const { name, scopes, autoApprove } = req.body || {};
    const 'parsedScopes': ApiScope[] = Array.isArray(scopes) ? scopes : [];
    const { key, token } = createApiKey(userId, name || 'My API Key', parsedScopes, !!autoApprove);
    return res.status(201).json({ 'data': { key, token } })}
  if (req.method === 'PUT') {
    const { id, action, scopes } = req.body || {};
    const keys = getApiKeys();
    const idx = keys.findIndex((k) => k.id === id && k.userId === userId);
    if (idx
export default function KeysPage() {
  return (
    < 0) return res.status(404).json({ 'error': { code: 'not_found', 'message': 'Key not found' } });
    if (action === 'regenerate') {
      const { token, hash } = generateApiToken();
      keys[idx].tokenHash = hash;
      saveApiKeys(keys);
      return res.status(200).json({ 'data': { key: keys[idx], token } })}
    if (action === 'update_scopes') {
      keys[idx].scopes = Array.isArray(scopes) ? scopes : keys[idx].scopes;
      saveApiKeys(keys);
      return res.status(200).json({ 'data': keys[idx] })}
    if (action === 'revoke') {
      keys[idx].revokedAt = new Date().toISOString();
      saveApiKeys(keys);
      return res.status(200).json({ "data": keys[idx] })}
<<<<<<< HEAD

=======
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
>>>>>>> 24132684af15a4d83201b2a91ee50324edfabedc
>>>>>>> origin/resolved-merge-conflicts
>>>>>>> origin/cursor/delete-old-data-records-6bba
import { getApiKeys, saveApiKeys  } from '../../../utils/devportal/storage';
export default function handler() {const userId  = getUserIdFromRequest(req)if (req && req.method === 'GET') {const keys = getApiKeys().filter((k) => k && k.userId === userId && !k && k.revokedAt)return res && res.status(200).json({ data: keys })}
  if (req && req.method === 'POST') {const { name, scopes, autoApprove } = req && req.body || {}const 'parsedScopes': ApiScope[] = Array && Array.isArray(scopes) ? scopes : [];
    const { key, token } = createApiKey(userId, name || 'My API Key', parsedScopes, !!autoApprove)return res && res.status(201).json({ 'data': { key, token } })}
  if (req && req.method === 'PUT') {const { id, action, scopes } = req && req.body || {}const keys = getApiKeys()const idx = keys && keys.findIndex((k) => k && k.id === id && k && k.userId === userId)if (idx;
export default function KeysPage() {return (< 0) return res && res.status(404).json({ 'error': { code: 'not_found', 'message': 'Key not found' } })ursor/automate-test-improve-and-merge-code-646c;
  if (req.method === 'GET') {const keys = getApiKeys().filter((k) => k.userId === userId && !k.revokedAt)return res.status(200).json({ data: keys })}
  if (req.method === 'POST') {const { name, scopes, autoApprove } = req.body || {}const 'parsedScopes': ApiScope[] = Array.isArray(scopes) ? scopes : [];
    const { key, token } = createApiKey(userId, name || 'My API Key', parsedScopes, !!autoApprove)return res.status(201).json({ 'data': { key, token } })}
  if (req.method === 'PUT') {const { id, action, scopes } = req.body || {}const keys = getApiKeys()const idx = keys.findIndex((k) => k.id === id && k.userId === userId)if (idx;
export default function KeysPage() {return (< 0) return res.status(404).json({ 'error': { code: 'not_found', 'message': 'Key not found' } })if (req && req.method === 'GET') {const keys = getApiKeys().filter((k) => k && k.userId === userId && !k && k.revokedAt)return res && res.status(200).json({ data: keys })}
  if (req && req.method === 'POST') {const { name, scopes, autoApprove } = req && req.body || {}const 'parsedScopes': ApiScope[] = Array && Array.isArray(scopes) ? scopes : [];
    const { key, token } = createApiKey(userId, name || 'My API Key', parsedScopes, !!autoApprove)return res && res.status(201).json({ 'data': { key, token } })}
  if (req && req.method === 'PUT') {const { id, action, scopes } = req && req.body || {}const keys = getApiKeys()const idx = keys && keys.findIndex((k) => k && k.id === id && k && k.userId === userId)if (idx;
export default function KeysPage() {return (< 0) return res && res.status(404).json({ 'error': { code: 'not_found', 'message': 'Key not found' } })ursor/automate-test-improve-and-merge-code-646c;
    if (action === 'regenerate') {const { token, hash } = generateApiToken()keys[idx].tokenHash = hash;
      saveApiKeys(keys)return res.status(200).json({ 'data': { key: keys[idx], token } })}
    if (action === 'update_scopes') {keys[idx].scopes = Array.isArray(scopes) ? scopes : keys[idx].scopes;
      saveApiKeys(keys)return res.status(200).json({ "data": keys[idx] })}
    if (action === 'revoke') {keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res.status(200).json({ "data": keys[idx] })}
<<<<<<< HEAD

=======
<<<<<<< HEAD
=======
<<<<<<< HEAD
    return res.status(400).json({ "error": { code: 'invalid_action', "message": 'Unknown action' } })}
  if (req.method === 'DELETE') {const { id } = req.query;
    const keys = getApiKeys()const idx = keys.findIndex((k) => k.id === id && k.userId === userId)if (idx < 0) return res.status(404).json({ "error": { code: 'not_found', "message": 'Key not found' } })keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res.status(200).json({ "data": keys[idx] })}
  return res.status(405).json({ "error": { code: 'method_not_allowed', "message": 'Method not allowed' } })}
  )}
import { NextApiRequest,NextApiResponse } from 'next'; import { ApiScope } from '../../../utils/devportal/types'; import { { createApiKey,getUserIdFromRequest },{ generateApiToken } } from '../../../utils/devportal/auth'; import { getApiKeys,saveApiKeys } from '../../../utils/devportal/storage'; export default function handler(req: 'NextApiRequest',res: NextApiResponse) { const userId = getUserIdFromRequest(req); if (req.method === 'GET') { const keys = getApiKeys().filter((k) => k.userId === userId && !k.revokedAt); return res.status(200).json({ data: keys })} if (req.method === 'POST') { const { name,scopes,autoApprove } = req.body || {}; const parsedScopes: ApiScope[] = Array.isArray(scopes) ? scopes : []; const { key,token } = createApiKey(userId,name || 'My API Key',parsedScopes,!!autoApprove); return res.status(201).json({ data: { key,token } })} if (req.method === 'PUT') { const { id,action,scopes } = req.body || {}; const keys = getApiKeys(); const idx = keys.findIndex((k) => k.id === id && k.userId === userId); if (idx export default function KeysPage() { return ( < 0) return res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } }); if (action === 'regenerate') { const { token,hash } = generateApiToken(); keys[idx].tokenHash = hash; saveApiKeys(keys); return res.status(200).json({ data: { key: keys[idx],token } })} if (action === 'update_scopes') { keys[idx].scopes = Array.isArray(scopes) ? scopes : keys[idx].scopes; saveApiKeys(keys); return res.status(200).json({ data: 'keys[idx]' })} if (action === 'revoke') { keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res.status(200).json({ data: 'keys[idx]' })} return res.status(400).json({ error: { code: 'invalid_action',message: 'Unknown action' } })} if (req.method === 'DELETE') { const { id } = req.query; const keys = getApiKeys(); const idx = keys.findIndex((k) => k.id === id && k.userId === userId); if (idx < 0) return res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } }); keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res.status(200).json({ data: 'keys[idx]' })} return res.status(405).json({ error: { code: 'method_not_allowed',message: 'Method not allowed' } })} )}
import { NextApiRequest,NextApiResponse } from 'next'; import { ApiScope } from '../../../utils/devportal/types'; import { { createApiKey,getUserIdFromRequest },{ generateApiToken } } from '../../../utils/devportal/auth'; import { getApiKeys,saveApiKeys } from '../../../utils/devportal/storage'; export default function handler(req: NextApiRequest,res: NextApiResponse) { const userId = getUserIdFromRequest(req); if (req.method === 'GET') { const keys = getApiKeys().filter((k) => k.userId === userId && !k.revokedAt); return res.status(200).json({ data: keys })} if (req.method === 'POST') { const { name,scopes,autoApprove } = req.body || {}; const parsedScopes: ApiScope[] = Array.isArray(scopes) ? scopes : []; const { key,token } = createApiKey(userId,name || 'My API Key',parsedScopes,!!autoApprove); return res.status(201).json({ data: { key,token } })} if (req.method === 'PUT') { const { id,action,scopes } = req.body || {}; const keys = getApiKeys(); const idx = keys.findIndex((k) => k.id === id && k.userId === userId); if (idx export default function KeysPage() { return ( < 0) return res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } }); if (action === 'regenerate') { const { token,hash } = generateApiToken(); keys[idx].tokenHash = hash; saveApiKeys(keys); return res.status(200).json({ data: { key: keys[idx],token } })} if (action === 'update_scopes') { keys[idx].scopes = Array.isArray(scopes) ? scopes : keys[idx].scopes; saveApiKeys(keys); return res.status(200).json({ data: keys[idx] })} if (action === 'revoke') { keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res.status(200).json({ data: keys[idx] })} return res.status(400).json({ error: { code: 'invalid_action',message: 'Unknown action' } })} if (req.method === 'DELETE') { const { id } = req.query; const keys = getApiKeys(); const idx = keys.findIndex((k) => k.id === id && k.userId === userId); if (idx < 0) return res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } }); keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res.status(200).json({ data: keys[idx] })} return res.status(405).json({ error: { code: 'method_not_allowed',message: 'Method not allowed' } })} )}
      return res && res.status(200).json({ "data": { key: keys[idx], token } })}
    if (action === 'update_scopes') {
      keys[idx].scopes = Array && Array.isArray(scopes) ? scopes : keys[idx].scopes;
      saveApiKeys(keys);
      return res && res.status(200).json({ "data": keys[idx] })}
    if (action === 'revoke') {
      keys[idx].revokedAt = new Date().toISOString();
      saveApiKeys(keys);
      return res && res.status(200).json({ "data": keys[idx] })}
import { NextApiRequest,NextApiResponse } from 'next'; import { ApiScope } from '../../../utils/devportal/types'; import { { createApiKey,getUserIdFromRequest },{ generateApiToken } } from '../../../utils/devportal/auth'; import { getApiKeys,saveApiKeys } from '../../../utils/devportal/storage'; export default function handler(req: 'NextApiRequest',res: NextApiResponse) { const userId = getUserIdFromRequest(req)if (req.method === 'GET') { const keys = getApiKeys().filter((k) => k.userId === userId && !k.revokedAt)return res.status(200).json({ data: keys })} if (req.method === 'POST') { const { name,scopes,autoApprove } = req.body || {}const parsedScopes: ApiScope[] = Array.isArray(scopes) ? scopes : []; const { key,token } = createApiKey(userId,name || 'My API Key',parsedScopes,!!autoApprove)return res.status(201).json({ data: { key,token } })} if (req.method === 'PUT') { const { id,action,scopes } = req.body || {}const keys = getApiKeys()const idx = keys.findIndex((k) => k.id === id && k.userId === userId)if (idx export default function KeysPage() { return ( < 0) return res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } })if (action === 'regenerate') { const { token,hash } = generateApiToken()keys[idx].tokenHash = hash; saveApiKeys(keys)return res.status(200).json({ data: { key: keys[idx],token } })} if (action === 'update_scopes') { keys[idx].scopes = Array.isArray(scopes) ? scopes : keys[idx].scopes; saveApiKeys(keys)return res.status(200).json({ data: 'keys[idx]' })} if (action === 'revoke') { keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res.status(200).json({ data: 'keys[idx]' })} return res.status(400).json({ error: { code: 'invalid_action',message: 'Unknown action' } })} if (req.method === 'DELETE') { const { id } = req.query; const keys = getApiKeys()const idx = keys.findIndex((k) => k.id === id && k.userId === userId)if (idx < 0) return res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } })keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res.status(200).json({ data: 'keys[idx]' })} return res.status(405).json({ error: { code: 'method_not_allowed',message: 'Method not allowed' } })} )}
import { NextApiRequest,NextApiResponse } from 'next'; import { ApiScope } from '../../../utils/devportal/types'; import { { createApiKey,getUserIdFromRequest },{ generateApiToken } } from '../../../utils/devportal/auth'; import { getApiKeys,saveApiKeys } from '../../../utils/devportal/storage'; export default function handler(req: NextApiRequest,res: NextApiResponse) { const userId = getUserIdFromRequest(req)if (req.method === 'GET') { const keys = getApiKeys().filter((k) => k.userId === userId && !k.revokedAt)return res.status(200).json({ data: keys })} if (req.method === 'POST') { const { name,scopes,autoApprove } = req.body || {}const parsedScopes: ApiScope[] = Array.isArray(scopes) ? scopes : []; const { key,token } = createApiKey(userId,name || 'My API Key',parsedScopes,!!autoApprove)return res.status(201).json({ data: { key,token } })} if (req.method === 'PUT') { const { id,action,scopes } = req.body || {}const keys = getApiKeys()const idx = keys.findIndex((k) => k.id === id && k.userId === userId)if (idx export default function KeysPage() { return ( < 0) return res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } })if (action === 'regenerate') { const { token,hash } = generateApiToken()keys[idx].tokenHash = hash; saveApiKeys(keys)return res.status(200).json({ data: { key: keys[idx],token } })} if (action === 'update_scopes') { keys[idx].scopes = Array.isArray(scopes) ? scopes : keys[idx].scopes; saveApiKeys(keys)return res.status(200).json({ data: keys[idx] })} if (action === 'revoke') { keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res.status(200).json({ data: keys[idx] })} return res.status(400).json({ error: { code: 'invalid_action',message: 'Unknown action' } })} if (req.method === 'DELETE') { const { id } = req.query; const keys = getApiKeys()const idx = keys.findIndex((k) => k.id === id && k.userId === userId)if (idx < 0) return res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } })keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res.status(200).json({ data: keys[idx] })} return res.status(405).json({ error: { code: 'method_not_allowed',message: 'Method not allowed' } })} )}return res && res.status(200).json({ "data": { key: keys[idx], token } })}
    if (action === 'update_scopes') {keys[idx].scopes = Array && Array.isArray(scopes) ? scopes : keys[idx].scopes;
      saveApiKeys(keys)return res && res.status(200).json({ "data": keys[idx] })}
    if (action === 'revoke') {keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res && res.status(200).json({ "data": keys[idx] })}
    return res && res.status(400).json({ "error": { code: 'invalid_action', "message": 'Unknown action' } })}
  if (req && req.method === 'DELETE') {const { id } = req && req.query;
    const keys = getApiKeys()const idx = keys && keys.findIndex((k) => k && k.id === id && k && k.userId === userId)if (idx < 0) return res && res.status(404).json({ "error": { code: 'not_found', "message": 'Key not found' } })keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res && res.status(200).json({ "data": keys[idx] })}
  return res && res.status(405).json({ "error": { code: 'method_not_allowed', "message": 'Method not allowed' } })}
  )}


=======
>>>>>>> origin/resolved-merge-conflicts
>>>>>>> merged-prs-20250907-203621
>>>>>>> origin/cursor/delete-old-data-records-6bba
    return res.status(400).json({ "error": { code: 'invalid_action', "message": 'Unknown action' } })}
  if (req.method === 'DELETE') {
    const { id } = req.query;
    const keys = getApiKeys();
    const idx = keys.findIndex((k) => k.id === id && k.userId === userId);
    if (idx < 0) return res.status(404).json({ "error": { code: 'not_found', "message": 'Key not found' } });
    keys[idx].revokedAt = new Date().toISOString();
    saveApiKeys(keys);
    return res.status(200).json({ "data": keys[idx] })}
  return res.status(405).json({ "error": { code: 'method_not_allowed', "message": 'Method not allowed' } })}
  )}
import { NextApiRequest,NextApiResponse } from 'next'; import { ApiScope } from '../../../utils/devportal/types'; import { { createApiKey,getUserIdFromRequest },{ generateApiToken } } from '../../../utils/devportal/auth'; import { getApiKeys,saveApiKeys } from '../../../utils/devportal/storage'; export default function handler(req: 'NextApiRequest',res: NextApiResponse) { const userId = getUserIdFromRequest(req); if (req.method === 'GET') { const keys = getApiKeys().filter((k) => k.userId === userId && !k.revokedAt); return res.status(200).json({ data: keys })} if (req.method === 'POST') { const { name,scopes,autoApprove } = req.body || {}; const parsedScopes: ApiScope[] = Array.isArray(scopes) ? scopes : []; const { key,token } = createApiKey(userId,name || 'My API Key',parsedScopes,!!autoApprove); return res.status(201).json({ data: { key,token } })} if (req.method === 'PUT') { const { id,action,scopes } = req.body || {}; const keys = getApiKeys(); const idx = keys.findIndex((k) => k.id === id && k.userId === userId); if (idx export default function KeysPage() { return ( < 0) return res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } }); if (action === 'regenerate') { const { token,hash } = generateApiToken(); keys[idx].tokenHash = hash; saveApiKeys(keys); return res.status(200).json({ data: { key: keys[idx],token } })} if (action === 'update_scopes') { keys[idx].scopes = Array.isArray(scopes) ? scopes : keys[idx].scopes; saveApiKeys(keys); return res.status(200).json({ data: 'keys[idx]' })} if (action === 'revoke') { keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res.status(200).json({ data: 'keys[idx]' })} return res.status(400).json({ error: { code: 'invalid_action',message: 'Unknown action' } })} if (req.method === 'DELETE') { const { id } = req.query; const keys = getApiKeys(); const idx = keys.findIndex((k) => k.id === id && k.userId === userId); if (idx < 0) return res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } }); keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res.status(200).json({ data: 'keys[idx]' })} return res.status(405).json({ error: { code: 'method_not_allowed',message: 'Method not allowed' } })} )}

import { NextApiRequest,NextApiResponse } from 'next'; import { ApiScope } from '../../../utils/devportal/types'; import { { createApiKey,getUserIdFromRequest },{ generateApiToken } } from '../../../utils/devportal/auth'; import { getApiKeys,saveApiKeys } from '../../../utils/devportal/storage'; export default function handler(req: NextApiRequest,res: NextApiResponse) { const userId = getUserIdFromRequest(req); if (req.method === 'GET') { const keys = getApiKeys().filter((k) => k.userId === userId && !k.revokedAt); return res.status(200).json({ data: keys })} if (req.method === 'POST') { const { name,scopes,autoApprove } = req.body || {}; const parsedScopes: ApiScope[] = Array.isArray(scopes) ? scopes : []; const { key,token } = createApiKey(userId,name || 'My API Key',parsedScopes,!!autoApprove); return res.status(201).json({ data: { key,token } })} if (req.method === 'PUT') { const { id,action,scopes } = req.body || {}; const keys = getApiKeys(); const idx = keys.findIndex((k) => k.id === id && k.userId === userId); if (idx export default function KeysPage() { return ( < 0) return res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } }); if (action === 'regenerate') { const { token,hash } = generateApiToken(); keys[idx].tokenHash = hash; saveApiKeys(keys); return res.status(200).json({ data: { key: keys[idx],token } })} if (action === 'update_scopes') { keys[idx].scopes = Array.isArray(scopes) ? scopes : keys[idx].scopes; saveApiKeys(keys); return res.status(200).json({ data: keys[idx] })} if (action === 'revoke') { keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res.status(200).json({ data: keys[idx] })} return res.status(400).json({ error: { code: 'invalid_action',message: 'Unknown action' } })} if (req.method === 'DELETE') { const { id } = req.query; const keys = getApiKeys(); const idx = keys.findIndex((k) => k.id === id && k.userId === userId); if (idx < 0) return res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } }); keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res.status(200).json({ data: keys[idx] })} return res.status(405).json({ error: { code: 'method_not_allowed',message: 'Method not allowed' } })} )}
      return res && res.status(200).json({ 'data': { key: keys[idx], token } })}
    if (action === 'update_scopes') {
      keys[idx].scopes = Array && Array.isArray(scopes) ? scopes : keys[idx].scopes;
      saveApiKeys(keys);
      return res && res.status(200).json({ 'data': keys[idx] })}
    if (action === 'revoke') {
      keys[idx].revokedAt = new Date().toISOString();
      saveApiKeys(keys);
      return res && res.status(200).json({ "data": keys[idx] })}
import { NextApiRequest,NextApiResponse } from 'next'; import { ApiScope } from '../../../utils/devportal/types'; import { { createApiKey,getUserIdFromRequest },{ generateApiToken } } from '../../../utils/devportal/auth'; import { getApiKeys,saveApiKeys } from '../../../utils/devportal/storage'; export default function handler(req: 'NextApiRequest',res: NextApiResponse) { const userId = getUserIdFromRequest(req)if (req.method === 'GET') { const keys = getApiKeys().filter((k) => k.userId === userId && !k.revokedAt)return res.status(200).json({ data: keys })} if (req.method === 'POST') { const { name,scopes,autoApprove } = req.body || {}const parsedScopes: ApiScope[] = Array.isArray(scopes) ? scopes : []; const { key,token } = createApiKey(userId,name || 'My API Key',parsedScopes,!!autoApprove)return res.status(201).json({ data: { key,token } })} if (req.method === 'PUT') { const { id,action,scopes } = req.body || {}const keys = getApiKeys()const idx = keys.findIndex((k) => k.id === id && k.userId === userId)if (idx export default function KeysPage() { return ( < 0) return res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } })if (action === 'regenerate') { const { token,hash } = generateApiToken()keys[idx].tokenHash = hash; saveApiKeys(keys)return res.status(200).json({ data: { key: keys[idx],token } })} if (action === 'update_scopes') { keys[idx].scopes = Array.isArray(scopes) ? scopes : keys[idx].scopes; saveApiKeys(keys)return res.status(200).json({ data: 'keys[idx]' })} if (action === 'revoke') { keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res.status(200).json({ data: 'keys[idx]' })} return res.status(400).json({ error: { code: 'invalid_action',message: 'Unknown action' } })} if (req.method === 'DELETE') { const { id } = req.query; const keys = getApiKeys()const idx = keys.findIndex((k) => k.id === id && k.userId === userId)if (idx < 0) return res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } })keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res.status(200).json({ data: 'keys[idx]' })} return res.status(405).json({ error: { code: 'method_not_allowed',message: 'Method not allowed' } })} )}
import { NextApiRequest,NextApiResponse } from 'next'; import { ApiScope } from '../../../utils/devportal/types'; import { { createApiKey,getUserIdFromRequest },{ generateApiToken } } from '../../../utils/devportal/auth'; import { getApiKeys,saveApiKeys } from '../../../utils/devportal/storage'; export default function handler(req: NextApiRequest,res: NextApiResponse) { const userId = getUserIdFromRequest(req)if (req.method === 'GET') { const keys = getApiKeys().filter((k) => k.userId === userId && !k.revokedAt)return res.status(200).json({ data: keys })} if (req.method === 'POST') { const { name,scopes,autoApprove } = req.body || {}const parsedScopes: ApiScope[] = Array.isArray(scopes) ? scopes : []; const { key,token } = createApiKey(userId,name || 'My API Key',parsedScopes,!!autoApprove)return res.status(201).json({ data: { key,token } })} if (req.method === 'PUT') { const { id,action,scopes } = req.body || {}const keys = getApiKeys()const idx = keys.findIndex((k) => k.id === id && k.userId === userId)if (idx export default function KeysPage() { return ( < 0) return res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } })if (action === 'regenerate') { const { token,hash } = generateApiToken()keys[idx].tokenHash = hash; saveApiKeys(keys)return res.status(200).json({ data: { key: keys[idx],token } })} if (action === 'update_scopes') { keys[idx].scopes = Array.isArray(scopes) ? scopes : keys[idx].scopes; saveApiKeys(keys)return res.status(200).json({ data: keys[idx] })} if (action === 'revoke') { keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res.status(200).json({ data: keys[idx] })} return res.status(400).json({ error: { code: 'invalid_action',message: 'Unknown action' } })} if (req.method === 'DELETE') { const { id } = req.query; const keys = getApiKeys()const idx = keys.findIndex((k) => k.id === id && k.userId === userId)if (idx < 0) return res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } })keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res.status(200).json({ data: keys[idx] })} return res.status(405).json({ error: { code: 'method_not_allowed',message: 'Method not allowed' } })} )}return res && res.status(200).json({ 'data': { key: keys[idx], token } })}
    if (action === 'update_scopes') {keys[idx].scopes = Array && Array.isArray(scopes) ? scopes : keys[idx].scopes;
      saveApiKeys(keys)return res && res.status(200).json({ "data": keys[idx] })}
    if (action === 'revoke') {keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res && res.status(200).json({ "data": keys[idx] })}
    return res && res.status(400).json({ "error": { code: 'invalid_action', "message": 'Unknown action' } })}
  if (req && req.method === 'DELETE') {const { id } = req && req.query;
    const keys = getApiKeys()const idx = keys && keys.findIndex((k) => k && k.id === id && k && k.userId === userId)if (idx < 0) return res && res.status(404).json({ "error": { code: 'not_found', "message": 'Key not found' } })keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res && res.status(200).json({ "data": keys[idx] })}
  return res && res.status(405).json({ "error": { code: 'method_not_allowed', "message": 'Method not allowed' } })}
import { getApiKeys, saveApiKeys  } from ../../../utils/devportal/storage';
export default function handler() {const userId  = getUserIdFromRequest(req)if (req && req.method === 'GET) {const keys = getApiKeys().filter((k) => k && k.userId === userId && !k && k.revokedAt)return res && res.status(200).json({ data: keys })}
  if (req && req.method === POST') {const { name, scopes, autoApprove } = req && req.body || {}const "parsedScopes: ApiScope[] = Array && Array.isArray(scopes) ? scopes : [];
    const { key, token } = createApiKey(userId, name || 'My API Key, parsedScopes, !!autoApprove)return res && res.status(201).json({ data": { key, token } })}
  if (req && req.method === PUT') {const { id, action, scopes } = req && req.body || {}const keys = getApiKeys()const idx = keys && keys.findIndex((k) => k && k.id === id && k && k.userId === userId)if (idx;
export default function KeysPage() {return (< 0) return res && res.status(404).json({ "error: { code: 'not_found, message": Key not found' } })ursor/automate-test-improve-and-merge-code-646c;
  if (req.method === 'GET) {const keys = getApiKeys().filter((k) => k.userId === userId && !k.revokedAt)return res.status(200).json({ data: keys })}
  if (req.method === POST') {const { name, scopes, autoApprove } = req.body || {}const "parsedScopes: ApiScope[] = Array.isArray(scopes) ? scopes : [];
    const { key, token } = createApiKey(userId, name || 'My API Key, parsedScopes, !!autoApprove)return res.status(201).json({ data": { key, token } })}
  if (req.method === PUT') {const { id, action, scopes } = req.body || {}const keys = getApiKeys()const idx = keys.findIndex((k) => k.id === id && k.userId === userId)if (idx;
export default function KeysPage() {return (< 0) return res.status(404).json({ "error: { code: 'not_found, message": Key not found' } })if (req && req.method === 'GET) {const keys = getApiKeys().filter((k) => k && k.userId === userId && !k && k.revokedAt)return res && res.status(200).json({ data: keys })}
  if (req && req.method === POST') {const { name, scopes, autoApprove } = req && req.body || {}const "parsedScopes: ApiScope[] = Array && Array.isArray(scopes) ? scopes : [];
  if (req && req.method === PUT') {const { id, action, scopes } = req && req.body || {}const keys = getApiKeys()const idx = keys && keys.findIndex((k) => k && k.id === id && k && k.userId === userId)if (idx;
export default function KeysPage() {return (< 0) return res && res.status(404).json({ "error: { code: 'not_found, message": Key not found' } })ursor/automate-test-improve-and-merge-code-646c;
    if (action === 'regenerate) {const { token, hash } = generateApiToken()keys[idx].tokenHash = hash;
      saveApiKeys(keys)return res.status(200).json({ "data: { key: keys[idx], token } })}
    if (action === update_scopes') {keys[idx].scopes = Array.isArray(scopes) ? scopes : keys[idx].scopes;
      saveApiKeys(keys)return res.status(200).json({ data": keys[idx] })}
    if (action === 'revoke) {keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res.status(200).json({ "data: keys[idx] })}

    return res.status(400).json({ error": { code: invalid_action', "message: 'Unknown action } })}
  if (req.method === DELETE') {const { id } = req.query;
    const keys = getApiKeys()const idx = keys.findIndex((k) => k.id === id && k.userId === userId)if (idx < 0) return res.status(404).json({ error": { code: 'not_found, "message: Key not found' } })keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res.status(200).json({ data": keys[idx] })}
  return res.status(405).json({ "error: { code: 'method_not_allowed, message": Method not allowed' } })}
  )}

import { NextApiRequest,NextApiResponse } from 'next; import { ApiScope } from ../../../utils/devportal/types'; import { { createApiKey,getUserIdFromRequest },{ generateApiToken } } from '../../../utils/devportal/auth; import { getApiKeys,saveApiKeys } from ../../../utils/devportal/storage'; export default function handler(req: 'NextApiRequest,res: NextApiResponse) { const userId = getUserIdFromRequest(req)if (req.method === GET') { const keys = getApiKeys().filter((k) => k.userId === userId && !k.revokedAt)return res.status(200).json({ data: keys })} if (req.method === 'POST) { const { name,scopes,autoApprove } = req.body || {}const parsedScopes: ApiScope[] = Array.isArray(scopes) ? scopes : []; const { key,token } = createApiKey(userId,name || My API Key',parsedScopes,!!autoApprove)return res.status(201).json({ data: { key,token } })} if (req.method === 'PUT) { const { id,action,scopes } = req.body || {}const keys = getApiKeys()const idx = keys.findIndex((k) => k.id === id && k.userId === userId)if (idx export default function KeysPage() { return ( < 0) return res.status(404).json({ error: { code: not_found',message: 'Key not found } })if (action === regenerate') { const { token,hash } = generateApiToken()keys[idx].tokenHash = hash; saveApiKeys(keys)return res.status(200).json({ data: { key: keys[idx],token } })} if (action === 'update_scopes) { keys[idx].scopes = Array.isArray(scopes) ? scopes : keys[idx].scopes; saveApiKeys(keys)return res.status(200).json({ data: keys[idx]' })} if (action === 'revoke) { keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res.status(200).json({ data: keys[idx]' })} return res.status(400).json({ error: { code: 'invalid_action,message: Unknown action' } })} if (req.method === 'DELETE) { const { id } = req.query; const keys = getApiKeys()const idx = keys.findIndex((k) => k.id === id && k.userId === userId)if (idx < 0) return res.status(404).json({ error: { code: not_found',message: 'Key not found } })keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res.status(200).json({ data: keys[idx]' })} return res.status(405).json({ error: { code: 'method_not_allowed,message: Method not allowed' } })} )}
import { NextApiRequest,NextApiResponse } from 'next; import { ApiScope } from ../../../utils/devportal/types'; import { { createApiKey,getUserIdFromRequest },{ generateApiToken } } from '../../../utils/devportal/auth; import { getApiKeys,saveApiKeys } from ../../../utils/devportal/storage'; export default function handler(req: NextApiRequest,res: NextApiResponse) { const userId = getUserIdFromRequest(req)if (req.method === 'GET) { const keys = getApiKeys().filter((k) => k.userId === userId && !k.revokedAt)return res.status(200).json({ data: keys })} if (req.method === POST') { const { name,scopes,autoApprove } = req.body || {}const parsedScopes: ApiScope[] = Array.isArray(scopes) ? scopes : []; const { key,token } = createApiKey(userId,name || 'My API Key,parsedScopes,!!autoApprove)return res.status(201).json({ data: { key,token } })} if (req.method === PUT') { const { id,action,scopes } = req.body || {}const keys = getApiKeys()const idx = keys.findIndex((k) => k.id === id && k.userId === userId)if (idx export default function KeysPage() { return ( < 0) return res.status(404).json({ error: { code: 'not_found,message: Key not found' } })if (action === 'regenerate) { const { token,hash } = generateApiToken()keys[idx].tokenHash = hash; saveApiKeys(keys)return res.status(200).json({ data: { key: keys[idx],token } })} if (action === update_scopes') { keys[idx].scopes = Array.isArray(scopes) ? scopes : keys[idx].scopes; saveApiKeys(keys)return res.status(200).json({ data: keys[idx] })} if (action === 'revoke) { keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res.status(200).json({ data: keys[idx] })} return res.status(400).json({ error: { code: invalid_action',message: 'Unknown action } })} if (req.method === DELETE') { const { id } = req.query; const keys = getApiKeys()const idx = keys.findIndex((k) => k.id === id && k.userId === userId)if (idx < 0) return res.status(404).json({ error: { code: 'not_found,message: Key not found' } })keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res.status(200).json({ data: keys[idx] })} return res.status(405).json({ error: { code: 'method_not_allowed,message: Method not allowed' } })} )}return res && res.status(200).json({ "data: { key: keys[idx], token } })}
    if (action === 'update_scopes) {keys[idx].scopes = Array && Array.isArray(scopes) ? scopes : keys[idx].scopes;
      saveApiKeys(keys)return res && res.status(200).json({ data": keys[idx] })}
    if (action === revoke') {keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res && res.status(200).json({ "data: keys[idx] })}

    return res && res.status(400).json({ error": { code: 'invalid_action, "message: Unknown action' } })}
  if (req && req.method === 'DELETE) {const { id } = req && req.query;
    const keys = getApiKeys()const idx = keys && keys.findIndex((k) => k && k.id === id && k && k.userId === userId)if (idx < 0) return res && res.status(404).json({ error": { code: not_found', "message: 'Key not found } })keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res && res.status(200).json({ data": keys[idx] })}
  return res && res.status(405).json({ "error: { code: method_not_allowed', message": 'Method not allowed } })}
  )}


import { NextApiRequest,NextApiResponse } from next'; import { ApiScope } from '../../../utils/devportal/types; import { { createApiKey,getUserIdFromRequest },{ generateApiToken } } from ../../../utils/devportal/auth'; import { getApiKeys,saveApiKeys } from '../../../utils/devportal/storage; export default function handler(req: NextApiRequest',res: NextApiResponse) { const userId = getUserIdFromRequest(req); if (req && req.method === 'GET) { const keys = getApiKeys().filter((k) => k && k.userId === userId && !k && k.revokedAt); return res && res.status(200).json({ data: keys })} if (req && req.method === POST') { const { name,scopes,autoApprove } = req && req.body || {} const parsedScopes: ApiScope[] = Array && Array.isArray(scopes) ? scopes : []; const { key,token } = createApiKey(userId,name || 'My API Key,parsedScopes,!!autoApprove); return res && res.status(201).json({ data: { key,token } })} if (req && req.method === PUT') { const { id,action,scopes } = req && req.body || {} const keys = getApiKeys(); const idx = keys && keys.findIndex((k) => k && k.id === id && k && k.userId === userId); if (idx export default function KeysPage() { return ( < 0) return res && res.status(404).json({ error: { code: 'not_found,message: Key not found' } }); if (action === 'regenerate) { const { token,hash } = generateApiToken(); keys[idx].tokenHash = hash; saveApiKeys(keys); return res && res.status(200).json({ data: { key: keys[idx],token } })} if (action === update_scopes') { keys[idx].scopes = Array && Array.isArray(scopes) ? scopes : keys[idx].scopes; saveApiKeys(keys); return res && res.status(200).json({ data: 'keys[idx] })} if (action === revoke') { keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res && res.status(200).json({ data: 'keys[idx] })} return res && res.status(400).json({ error: { code: invalid_action',message: 'Unknown action } })} if (req && req.method === DELETE') { const { id } = req && req.query; const keys = getApiKeys(); const idx = keys && keys.findIndex((k) => k && k.id === id && k && k.userId === userId); if (idx < 0) return res && res.status(404).json({ error: { code: 'not_found,message: Key not found' } }); keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res && res.status(200).json({ data: 'keys[idx] })} return res && res.status(405).json({ error: { code: method_not_allowed',message: 'Method not allowed } })} )}
import { NextApiRequest,NextApiResponse } from next'; import { ApiScope } from '../../../utils/devportal/types; import { { createApiKey,getUserIdFromRequest },{ generateApiToken } } from ../../../utils/devportal/auth'; import { getApiKeys,saveApiKeys } from '../../../utils/devportal/storage; export default function handler(req: NextApiRequest,res: NextApiResponse) { const userId = getUserIdFromRequest(req); if (req && req.method === GET') { const keys = getApiKeys().filter((k) => k && k.userId === userId && !k && k.revokedAt); return res && res.status(200).json({ data: keys })} if (req && req.method === 'POST) { const { name,scopes,autoApprove } = req && req.body || {} const parsedScopes: ApiScope[] = Array && Array.isArray(scopes) ? scopes : []; const { key,token } = createApiKey(userId,name || My API Key',parsedScopes,!!autoApprove); return res && res.status(201).json({ data: { key,token } })} if (req && req.method === 'PUT) { const { id,action,scopes } = req && req.body || {} const keys = getApiKeys(); const idx = keys && keys.findIndex((k) => k && k.id === id && k && k.userId === userId); if (idx export default function KeysPage() { return ( < 0) return res && res.status(404).json({ error: { code: not_found',message: 'Key not found } }); if (action === regenerate') { const { token,hash } = generateApiToken(); keys[idx].tokenHash = hash; saveApiKeys(keys); return res && res.status(200).json({ data: { key: keys[idx],token } })} if (action === 'update_scopes) { keys[idx].scopes = Array && Array.isArray(scopes) ? scopes : keys[idx].scopes; saveApiKeys(keys); return res && res.status(200).json({ data: keys[idx] })} if (action === revoke') { keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res && res.status(200).json({ data: keys[idx] })} return res && res.status(400).json({ error: { code: 'invalid_action,message: Unknown action' } })} if (req && req.method === 'DELETE) { const { id } = req && req.query; const keys = getApiKeys(); const idx = keys && keys.findIndex((k) => k && k.id === id && k && k.userId === userId); if (idx < 0) return res && res.status(404).json({ error: { code: not_found',message: 'Key not found } }); keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res && res.status(200).json({ data: keys[idx] })} return res && res.status(405).json({ error: { code: method_not_allowed',message: 'Method not allowed } })} )}
<<<<<<< HEAD
=======
>>>>>>> 24132684af15a4d83201b2a91ee50324edfabedc
>>>>>>> origin/resolved-merge-conflicts


import { NextApiRequest,NextApiResponse } from next'; import { ApiScope } from '../../../utils/devportal/types; import { { createApiKey,getUserIdFromRequest },{ generateApiToken } } from ../../../utils/devportal/auth'; import { getApiKeys,saveApiKeys } from '../../../utils/devportal/storage; export default function handler(req: NextApiRequest,res: NextApiResponse) { const userId = getUserIdFromRequest(req); if (req.method === GET') { const keys = getApiKeys().filter((k) => k.userId === userId && !k.revokedAt); return res.status(200).json({ data: keys })} if (req.method === 'POST) { const { name,scopes,autoApprove } = req.body || {} const parsedScopes: ApiScope[] = Array.isArray(scopes) ? scopes : []; const { key,token } = createApiKey(userId,name || My API Key',parsedScopes,!!autoApprove); return res.status(201).json({ data: { key,token } })} if (req.method === 'PUT) { const { id,action,scopes } = req.body || {} const keys = getApiKeys(); const idx = keys.findIndex((k) => k.id === id && k.userId === userId); if (idx export default function KeysPage() { return ( < 0) return res.status(404).json({ error: { code: not_found',message: 'Key not found } }); if (action === regenerate') { const { token,hash } = generateApiToken(); keys[idx].tokenHash = hash; saveApiKeys(keys); return res.status(200).json({ data: { key: keys[idx],token } })} if (action === 'update_scopes) { keys[idx].scopes = Array.isArray(scopes) ? scopes : keys[idx].scopes; saveApiKeys(keys); return res.status(200).json({ data: keys[idx] })} if (action === revoke') { keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res.status(200).json({ data: keys[idx] })} return res.status(400).json({ error: { code: 'invalid_action,message: Unknown action' } })} if (req.method === 'DELETE) { const { id } = req.query; const keys = getApiKeys(); const idx = keys.findIndex((k) => k.id === id && k.userId === userId); if (idx < 0) return res.status(404).json({ error: { code: not_found',message: 'Key not found } }); keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res.status(200).json({ data: keys[idx] })} return res.status(405).json({ error: { code: method_not_allowed',message: 'Method not allowed } })} )}
ursor/add-new-services-and-deploy-updates-0462
ursor/fix-syntax-push-and-merge-to-main-40de
<<<<<<< HEAD
=======
<<<<<<< HEAD
import { NextApiRequest,NextApiResponse } from 'next'; import { ApiScope } from '../../../utils/devportal/types'; import { { createApiKey,getUserIdFromRequest },{ generateApiToken } } from '../../../utils/devportal/auth'; import { getApiKeys,saveApiKeys } from '../../../utils/devportal/storage'; export default function handler(req: 'NextApiRequest',res: NextApiResponse) { const userId = getUserIdFromRequest(req); if (req && req.method === 'GET') { const keys = getApiKeys().filter((k) => k && k.userId === userId && !k && k.revokedAt); return res && res.status(200).json({ data: keys })} if (req && req.method === 'POST') { const { name,scopes,autoApprove } = req && req.body || {}; const parsedScopes: ApiScope[] = Array && Array.isArray(scopes) ? scopes : []; const { key,token } = createApiKey(userId,name || 'My API Key',parsedScopes,!!autoApprove); return res && res.status(201).json({ data: { key,token } })} if (req && req.method === 'PUT') { const { id,action,scopes } = req && req.body || {}; const keys = getApiKeys(); const idx = keys && keys.findIndex((k) => k && k.id === id && k && k.userId === userId); if (idx export default function KeysPage() { return ( < 0) return res && res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } }); if (action === 'regenerate') { const { token,hash } = generateApiToken(); keys[idx].tokenHash = hash; saveApiKeys(keys); return res && res.status(200).json({ data: { key: keys[idx],token } })} if (action === 'update_scopes') { keys[idx].scopes = Array && Array.isArray(scopes) ? scopes : keys[idx].scopes; saveApiKeys(keys); return res && res.status(200).json({ data: 'keys[idx]' })} if (action === 'revoke') { keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res && res.status(200).json({ data: 'keys[idx]' })} return res && res.status(400).json({ error: { code: 'invalid_action',message: 'Unknown action' } })} if (req && req.method === 'DELETE') { const { id } = req && req.query; const keys = getApiKeys(); const idx = keys && keys.findIndex((k) => k && k.id === id && k && k.userId === userId); if (idx < 0) return res && res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } }); keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res && res.status(200).json({ data: 'keys[idx]' })} return res && res.status(405).json({ error: { code: 'method_not_allowed',message: 'Method not allowed' } })} )}
import { NextApiRequest,NextApiResponse } from 'next'; import { ApiScope } from '../../../utils/devportal/types'; import { { createApiKey,getUserIdFromRequest },{ generateApiToken } } from '../../../utils/devportal/auth'; import { getApiKeys,saveApiKeys } from '../../../utils/devportal/storage'; export default function handler(req: NextApiRequest,res: NextApiResponse) { const userId = getUserIdFromRequest(req); if (req && req.method === 'GET') { const keys = getApiKeys().filter((k) => k && k.userId === userId && !k && k.revokedAt); return res && res.status(200).json({ data: keys })} if (req && req.method === 'POST') { const { name,scopes,autoApprove } = req && req.body || {}; const parsedScopes: ApiScope[] = Array && Array.isArray(scopes) ? scopes : []; const { key,token } = createApiKey(userId,name || 'My API Key',parsedScopes,!!autoApprove); return res && res.status(201).json({ data: { key,token } })} if (req && req.method === 'PUT') { const { id,action,scopes } = req && req.body || {}; const keys = getApiKeys(); const idx = keys && keys.findIndex((k) => k && k.id === id && k && k.userId === userId); if (idx export default function KeysPage() { return ( < 0) return res && res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } }); if (action === 'regenerate') { const { token,hash } = generateApiToken(); keys[idx].tokenHash = hash; saveApiKeys(keys); return res && res.status(200).json({ data: { key: keys[idx],token } })} if (action === 'update_scopes') { keys[idx].scopes = Array && Array.isArray(scopes) ? scopes : keys[idx].scopes; saveApiKeys(keys); return res && res.status(200).json({ data: keys[idx] })} if (action === 'revoke') { keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res && res.status(200).json({ data: keys[idx] })} return res && res.status(400).json({ error: { code: 'invalid_action',message: 'Unknown action' } })} if (req && req.method === 'DELETE') { const { id } = req && req.query; const keys = getApiKeys(); const idx = keys && keys.findIndex((k) => k && k.id === id && k && k.userId === userId); if (idx < 0) return res && res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } }); keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res && res.status(200).json({ data: keys[idx] })} return res && res.status(405).json({ error: { code: 'method_not_allowed',message: 'Method not allowed' } })} )}
>>>>>>> origin/resolved-merge-conflicts


      return res.status(200).json({ 'data': { key: keys[idx], token } })}
    if (action === 'update_scopes') {keys[idx].scopes = Array.isArray(scopes) ? scopes : keys[idx].scopes;
<<<<<<< HEAD
      saveApiKeys(keys)return res.status(200).json({ 'data': keys[idx] })}
    if (action === 'revoke') {keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res.status(200).json({ 'data': keys[idx] })}
    return res.status(400).json({ 'error': { code: 'invalid_action', 'message': 'Unknown action' } })}
=======
      saveApiKeys(keys)return res.status(200).json({ "data": keys[idx] })}
    if (action === 'revoke') {keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res.status(200).json({ "data": keys[idx] })}
    return res.status(400).json({ "error": { code: 'invalid_action', "message": 'Unknown action' } })}
  if (req.method === 'DELETE') {const { id } = req.query;
    const keys = getApiKeys()const idx = keys.findIndex((k) => k.id === id && k.userId === userId)if (idx < 0) return res.status(404).json({ "error": { code: 'not_found', "message": 'Key not found' } })keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res.status(200).json({ "data": keys[idx] })}
  return res.status(405).json({ "error": { code: 'method_not_allowed', "message": 'Method not allowed' } })}
  )}
import { NextApiRequest,NextApiResponse } from 'next'; import { ApiScope } from '../../../utils/devportal/types'; import { { createApiKey,getUserIdFromRequest },{ generateApiToken } } from '../../../utils/devportal/auth'; import { getApiKeys,saveApiKeys } from '../../../utils/devportal/storage'; export default function handler(req: 'NextApiRequest',res: NextApiResponse) { const userId = getUserIdFromRequest(req); if (req.method === 'GET') { const keys = getApiKeys().filter((k) => k.userId === userId && !k.revokedAt); return res.status(200).json({ data: keys })} if (req.method === 'POST') { const { name,scopes,autoApprove } = req.body || {}; const parsedScopes: ApiScope[] = Array.isArray(scopes) ? scopes : []; const { key,token } = createApiKey(userId,name || 'My API Key',parsedScopes,!!autoApprove); return res.status(201).json({ data: { key,token } })} if (req.method === 'PUT') { const { id,action,scopes } = req.body || {}; const keys = getApiKeys(); const idx = keys.findIndex((k) => k.id === id && k.userId === userId); if (idx export default function KeysPage() { return ( < 0) return res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } }); if (action === 'regenerate') { const { token,hash } = generateApiToken(); keys[idx].tokenHash = hash; saveApiKeys(keys); return res.status(200).json({ data: { key: keys[idx],token } })} if (action === 'update_scopes') { keys[idx].scopes = Array.isArray(scopes) ? scopes : keys[idx].scopes; saveApiKeys(keys); return res.status(200).json({ data: 'keys[idx]' })} if (action === 'revoke') { keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res.status(200).json({ data: 'keys[idx]' })} return res.status(400).json({ error: { code: 'invalid_action',message: 'Unknown action' } })} if (req.method === 'DELETE') { const { id } = req.query; const keys = getApiKeys(); const idx = keys.findIndex((k) => k.id === id && k.userId === userId); if (idx < 0) return res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } }); keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res.status(200).json({ data: 'keys[idx]' })} return res.status(405).json({ error: { code: 'method_not_allowed',message: 'Method not allowed' } })} )}
import { NextApiRequest,NextApiResponse } from 'next'; import { ApiScope } from '../../../utils/devportal/types'; import { { createApiKey,getUserIdFromRequest },{ generateApiToken } } from '../../../utils/devportal/auth'; import { getApiKeys,saveApiKeys } from '../../../utils/devportal/storage'; export default function handler(req: NextApiRequest,res: NextApiResponse) { const userId = getUserIdFromRequest(req); if (req.method === 'GET') { const keys = getApiKeys().filter((k) => k.userId === userId && !k.revokedAt); return res.status(200).json({ data: keys })} if (req.method === 'POST') { const { name,scopes,autoApprove } = req.body || {}; const parsedScopes: ApiScope[] = Array.isArray(scopes) ? scopes : []; const { key,token } = createApiKey(userId,name || 'My API Key',parsedScopes,!!autoApprove); return res.status(201).json({ data: { key,token } })} if (req.method === 'PUT') { const { id,action,scopes } = req.body || {}; const keys = getApiKeys(); const idx = keys.findIndex((k) => k.id === id && k.userId === userId); if (idx export default function KeysPage() { return ( < 0) return res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } }); if (action === 'regenerate') { const { token,hash } = generateApiToken(); keys[idx].tokenHash = hash; saveApiKeys(keys); return res.status(200).json({ data: { key: keys[idx],token } })} if (action === 'update_scopes') { keys[idx].scopes = Array.isArray(scopes) ? scopes : keys[idx].scopes; saveApiKeys(keys); return res.status(200).json({ data: keys[idx] })} if (action === 'revoke') { keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res.status(200).json({ data: keys[idx] })} return res.status(400).json({ error: { code: 'invalid_action',message: 'Unknown action' } })} if (req.method === 'DELETE') { const { id } = req.query; const keys = getApiKeys(); const idx = keys.findIndex((k) => k.id === id && k.userId === userId); if (idx < 0) return res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } }); keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res.status(200).json({ data: keys[idx] })} return res.status(405).json({ error: { code: 'method_not_allowed',message: 'Method not allowed' } })} )}
  )}ursor/automate-test-improve-and-merge-code-646c;
=======


      return res.status(200).json({ "data": { key: keys[idx], token } })}
    if (action === 'update_scopes') {keys[idx].scopes = Array.isArray(scopes) ? scopes : keys[idx].scopes;
      saveApiKeys(keys)return res.status(200).json({ "data": keys[idx] })}
    if (action === 'revoke') {keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res.status(200).json({ "data": keys[idx] })}
    return res.status(400).json({ "error": { code: 'invalid_action', "message": 'Unknown action' } })}
>>>>>>> origin/resolved-merge-conflicts
  if (req.method === 'DELETE') {const { id } = req.query;
    const keys = getApiKeys()const idx = keys.findIndex((k) => k.id === id && k.userId === userId)if (idx < 0) return res.status(404).json({ "error": { code: 'not_found', "message": 'Key not found' } })keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res.status(200).json({ "data": keys[idx] })}
  return res.status(405).json({ "error": { code: 'method_not_allowed', "message": 'Method not allowed' } })}
  )}
import { NextApiRequest,NextApiResponse } from 'next'; import { ApiScope } from '../../../utils/devportal/types'; import { { createApiKey,getUserIdFromRequest },{ generateApiToken } } from '../../../utils/devportal/auth'; import { getApiKeys,saveApiKeys } from '../../../utils/devportal/storage'; export default function handler(req: 'NextApiRequest',res: NextApiResponse) { const userId = getUserIdFromRequest(req); if (req.method === 'GET') { const keys = getApiKeys().filter((k) => k.userId === userId && !k.revokedAt); return res.status(200).json({ data: keys })} if (req.method === 'POST') { const { name,scopes,autoApprove } = req.body || {}; const parsedScopes: ApiScope[] = Array.isArray(scopes) ? scopes : []; const { key,token } = createApiKey(userId,name || 'My API Key',parsedScopes,!!autoApprove); return res.status(201).json({ data: { key,token } })} if (req.method === 'PUT') { const { id,action,scopes } = req.body || {}; const keys = getApiKeys(); const idx = keys.findIndex((k) => k.id === id && k.userId === userId); if (idx export default function KeysPage() { return ( < 0) return res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } }); if (action === 'regenerate') { const { token,hash } = generateApiToken(); keys[idx].tokenHash = hash; saveApiKeys(keys); return res.status(200).json({ data: { key: keys[idx],token } })} if (action === 'update_scopes') { keys[idx].scopes = Array.isArray(scopes) ? scopes : keys[idx].scopes; saveApiKeys(keys); return res.status(200).json({ data: 'keys[idx]' })} if (action === 'revoke') { keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res.status(200).json({ data: 'keys[idx]' })} return res.status(400).json({ error: { code: 'invalid_action',message: 'Unknown action' } })} if (req.method === 'DELETE') { const { id } = req.query; const keys = getApiKeys(); const idx = keys.findIndex((k) => k.id === id && k.userId === userId); if (idx < 0) return res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } }); keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res.status(200).json({ data: 'keys[idx]' })} return res.status(405).json({ error: { code: 'method_not_allowed',message: 'Method not allowed' } })} )}
import { NextApiRequest,NextApiResponse } from 'next'; import { ApiScope } from '../../../utils/devportal/types'; import { { createApiKey,getUserIdFromRequest },{ generateApiToken } } from '../../../utils/devportal/auth'; import { getApiKeys,saveApiKeys } from '../../../utils/devportal/storage'; export default function handler(req: NextApiRequest,res: NextApiResponse) { const userId = getUserIdFromRequest(req); if (req.method === 'GET') { const keys = getApiKeys().filter((k) => k.userId === userId && !k.revokedAt); return res.status(200).json({ data: keys })} if (req.method === 'POST') { const { name,scopes,autoApprove } = req.body || {}; const parsedScopes: ApiScope[] = Array.isArray(scopes) ? scopes : []; const { key,token } = createApiKey(userId,name || 'My API Key',parsedScopes,!!autoApprove); return res.status(201).json({ data: { key,token } })} if (req.method === 'PUT') { const { id,action,scopes } = req.body || {}; const keys = getApiKeys(); const idx = keys.findIndex((k) => k.id === id && k.userId === userId); if (idx export default function KeysPage() { return ( < 0) return res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } }); if (action === 'regenerate') { const { token,hash } = generateApiToken(); keys[idx].tokenHash = hash; saveApiKeys(keys); return res.status(200).json({ data: { key: keys[idx],token } })} if (action === 'update_scopes') { keys[idx].scopes = Array.isArray(scopes) ? scopes : keys[idx].scopes; saveApiKeys(keys); return res.status(200).json({ data: keys[idx] })} if (action === 'revoke') { keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res.status(200).json({ data: keys[idx] })} return res.status(400).json({ error: { code: 'invalid_action',message: 'Unknown action' } })} if (req.method === 'DELETE') { const { id } = req.query; const keys = getApiKeys(); const idx = keys.findIndex((k) => k.id === id && k.userId === userId); if (idx < 0) return res.status(404).json({ error: { code: 'not_found',message: 'Key not found' } }); keys[idx].revokedAt = new Date().toISOString(); saveApiKeys(keys); return res.status(200).json({ data: keys[idx] })} return res.status(405).json({ error: { code: 'method_not_allowed',message: 'Method not allowed' } })} )}
  )}ursor/automate-test-improve-and-merge-code-646c;
ursor/automate-test-improve-and-merge-code-646c;
import { NextApiRequest,NextApiResponse } from next'; import { ApiScope } from '../../../utils/devportal/types; import { { createApiKey,getUserIdFromRequest },{ generateApiToken } } from ../../../utils/devportal/auth'; import { getApiKeys,saveApiKeys } from '../../../utils/devportal/storage; export default function handler(req: NextApiRequest',res: NextApiResponse) { const userId = getUserIdFromRequest(req)if (req && req.method === 'GET) { const keys = getApiKeys().filter((k) => k && k.userId === userId && !k && k.revokedAt)return res && res.status(200).json({ data: keys })} if (req && req.method === POST') { const { name,scopes,autoApprove } = req && req.body || {}const parsedScopes: ApiScope[] = Array && Array.isArray(scopes) ? scopes : []; const { key,token } = createApiKey(userId,name || 'My API Key,parsedScopes,!!autoApprove)return res && res.status(201).json({ data: { key,token } })} if (req && req.method === PUT') { const { id,action,scopes } = req && req.body || {}const keys = getApiKeys()const idx = keys && keys.findIndex((k) => k && k.id === id && k && k.userId === userId)if (idx export default function KeysPage() { return ( < 0) return res && res.status(404).json({ error: { code: 'not_found,message: Key not found' } })if (action === 'regenerate) { const { token,hash } = generateApiToken()keys[idx].tokenHash = hash; saveApiKeys(keys)return res && res.status(200).json({ data: { key: keys[idx],token } })} if (action === update_scopes') { keys[idx].scopes = Array && Array.isArray(scopes) ? scopes : keys[idx].scopes; saveApiKeys(keys)return res && res.status(200).json({ data: 'keys[idx] })} if (action === revoke') { keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res && res.status(200).json({ data: 'keys[idx] })} return res && res.status(400).json({ error: { code: invalid_action',message: 'Unknown action } })} if (req && req.method === DELETE') { const { id } = req && req.query; const keys = getApiKeys()const idx = keys && keys.findIndex((k) => k && k.id === id && k && k.userId === userId)if (idx < 0) return res && res.status(404).json({ error: { code: 'not_found,message: Key not found' } })keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res && res.status(200).json({ data: 'keys[idx] })} return res && res.status(405).json({ error: { code: method_not_allowed',message: 'Method not allowed } })} )}
import { NextApiRequest,NextApiResponse } from next'; import { ApiScope } from '../../../utils/devportal/types; import { { createApiKey,getUserIdFromRequest },{ generateApiToken } } from ../../../utils/devportal/auth'; import { getApiKeys,saveApiKeys } from '../../../utils/devportal/storage; export default function handler(req: NextApiRequest,res: NextApiResponse) { const userId = getUserIdFromRequest(req)if (req && req.method === GET') { const keys = getApiKeys().filter((k) => k && k.userId === userId && !k && k.revokedAt)return res && res.status(200).json({ data: keys })} if (req && req.method === 'POST) { const { name,scopes,autoApprove } = req && req.body || {}const parsedScopes: ApiScope[] = Array && Array.isArray(scopes) ? scopes : []; const { key,token } = createApiKey(userId,name || My API Key',parsedScopes,!!autoApprove)return res && res.status(201).json({ data: { key,token } })} if (req && req.method === 'PUT) { const { id,action,scopes } = req && req.body || {}const keys = getApiKeys()const idx = keys && keys.findIndex((k) => k && k.id === id && k && k.userId === userId)if (idx export default function KeysPage() { return ( < 0) return res && res.status(404).json({ error: { code: not_found',message: 'Key not found } })if (action === regenerate') { const { token,hash } = generateApiToken()keys[idx].tokenHash = hash; saveApiKeys(keys)return res && res.status(200).json({ data: { key: keys[idx],token } })} if (action === 'update_scopes) { keys[idx].scopes = Array && Array.isArray(scopes) ? scopes : keys[idx].scopes; saveApiKeys(keys)return res && res.status(200).json({ data: keys[idx] })} if (action === revoke') { keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res && res.status(200).json({ data: keys[idx] })} return res && res.status(400).json({ error: { code: 'invalid_action,message: Unknown action' } })} if (req && req.method === 'DELETE) { const { id } = req && req.query; const keys = getApiKeys()const idx = keys && keys.findIndex((k) => k && k.id === id && k && k.userId === userId)if (idx < 0) return res && res.status(404).json({ error: { code: not_found',message: 'Key not found } })keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res && res.status(200).json({ data: keys[idx] })} return res && res.status(405).json({ error: { code: method_not_allowed',message: 'Method not allowed } })} )}ursor/add-new-services-and-deploy-updates-0462;
ursor/fix-syntax-push-and-merge-to-main-40de;
ursor/fix-website-loading-errors-and-merge-6662;






ursor/add-new-services-and-deploy-updates-0462
ursor/fix-syntax-push-and-merge-to-main-40de



      return res.status(200).json({ "data: { key: keys[idx], token } })}
    if (action === update_scopes') {keys[idx].scopes = Array.isArray(scopes) ? scopes : keys[idx].scopes;
      saveApiKeys(keys)return res.status(200).json({ data": keys[idx] })}
    if (action === 'revoke) {keys[idx].revokedAt = new Date().toISOString()saveApiKeys(keys)return res.status(200).json({ "data: keys[idx] })}
    return res.status(400).json({ error": { code: invalid_action', "message: 'Unknown action } })}
  if (req.method === DELETE') {const { id } = req.query;
  return res.status(405).json({ "error: { code: 'method_not_allowed, message": Method not allowed' } })}

  )}ursor/automate-test-improve-and-merge-code-646c;
<<<<<<< HEAD

=======
>>>>>>> merged-prs-20250907-203621
<<<<<<< HEAD
=======
>>>>>>> 24132684af15a4d83201b2a91ee50324edfabedc
>>>>>>> origin/resolved-merge-conflicts
>>>>>>> origin/cursor/delete-old-data-records-6bba
