<<<<<<< HEAD
<<<<<<< HEAD
import React from \'react\'; export function BlogSection () {}; return null} import { Link } from \'react-router-dom\'; ,; {}; {blogPosts && blogPosts.map((post) => (<article key={post && post.id} className=\"bg-white/10 backdrop-blur-sm rounded-lg p-6\">\"; <h3 className=\"text-xl font-semibold text-white mb-3\">\"; <Link to={`/blog/${post && post.id}`} className=\""hover\": text-zion-cyan\"> {post && post.title} ></div> </h3>\"; <p className=\"text-zion-slate-light mb-4\">{post && post.excerpt}</p>\"; <div className=\"flex justify-between text-sm text-zion-slate-light\"> <span>{post && post.date}></div> <span>{post && post.readTime}></div> ></div> </article>) ) } ></div> ></div> </section>)} \'"`}
const React from "react"; export function BlogSection() { return; }; return null} import { Link } from "react-router-dom"; ,; {}; {blogPosts && blogPosts.map((post) => (<article key={post && post.id} className="bg-white/10 backdrop-blur-sm rounded-lg p-6">"; <h3 className="text-xl font-semibold text-white mb-3">"; <Link to={`/blog/${post && post.id}`} className="hover: text-zion-cyan"> {post && post.title} ></div> </h3>"; <p className="text-zion-slate-light mb-4">{post && post.excerpt}</p>"; <div className="flex justify-between text-sm text-zion-slate-light"> <span>{post && post.date}></div> <span>{post && post.readTime}></div> ></div> </article>) ) } ></div> ></div> </section>)} ""`}""`"`

import _React from 'react'; export function BlogSection () {}; return null} import { Link } from 'react-router-dom'; ,; {}; {blogPosts && blogPosts.map((post) => (<article key={post && post.id} className="bg-white/10 backdrop-blur-sm rounded-lg p-6">"; <h3 className="text-xl font-semibold text-white mb-3">"; <Link to={`/blog/${post && post.id}`} className=""hover": text-zion-cyan"> {post && post.title} ></div> </h3>"; <p className="text-zion-slate-light mb-4">{post && post.excerpt}</p>"; <div className="flex justify-between text-sm text-zion-slate-light"> <span>{post && post.date}></div> <span>{post && post.readTime}></div> ></div> </article>) ) } ></div> ></div> </section>)} '"`}

=======
import React from \'react\'; export function BlogSection () {}; return null} import { Link } from \'react-router-dom\'; ,; {}; {blogPosts.map((post) => (<article key={post.id} className=\"bg-white/10 backdrop-blur-sm rounded-lg p-6\">\"; <h3 className=\"text-xl font-semibold text-white mb-3\">\"; <Link to={`/blog/${post.id}`} className=\""hover\": text-zion-cyan\"> {post.title} ></div> </h3>\"; <p className=\"text-zion-slate-light mb-4\">{post.excerpt}</p>\"; <div className=\"flex justify-between text-sm text-zion-slate-light\"> <span>{post.date}></div> <span>{post.readTime}></div> ></div> </article>) ) } ></div> ></div> </section>)} \'"`}
const React from "react"; export function BlogSection() { return; }; return null} import { Link } from "react-router-dom"; ,; {}; {blogPosts.map((post) => (<article key={post.id} className="bg-white/10 backdrop-blur-sm rounded-lg p-6">"; <h3 className="text-xl font-semibold text-white mb-3">"; <Link to={`/blog/${post.id}`} className="hover: text-zion-cyan"> {post.title} ></div> </h3>"; <p className="text-zion-slate-light mb-4">{post.excerpt}</p>"; <div className="flex justify-between text-sm text-zion-slate-light"> <span>{post.date}></div> <span>{post.readTime}></div> ></div> </article>) ) } ></div> ></div> </section>)} ""`}""`"`
import _React from 'react'; export function BlogSection () {}; return null} import { Link } from 'react-router-dom'; ,; {}; {blogPosts.map((post) => (<article key={post.id} className="bg-white/10 backdrop-blur-sm rounded-lg p-6">"; <h3 className="text-xl font-semibold text-white mb-3">"; <Link to={`/blog/${post.id}`} className=""hover": text-zion-cyan"> {post.title} ></div> </h3>"; <p className="text-zion-slate-light mb-4">{post.excerpt}</p>"; <div className="flex justify-between text-sm text-zion-slate-light"> <span>{post.date}></div> <span>{post.readTime}></div> ></div> </article>) ) } ></div> ></div> </section>)} '"`}
>>>>>>> 99482a9199aaf93c62fadf06056b12429832a7df
=======
>>>>>>> f8e9d8204b854980b1ebe0327134be4447b2409a
