import _React from 'react'; export function StatsSection() {; const stats = [{; "number": '500+',; "label": 'Projects Completed',; "description": 'Successfully delivered solutions',; "icon": '🚀',; "color": 'from-purple-500 to-pink-500';},; {}},; {}},; {}},; {}} ]; return (); <section className="py-16 bg-white">"; <div className="max-w-7xl mx-auto px-4 "sm": px-6 lg:px-8">"; <div className="text-center mb-12">" <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4"> Zion Tech Group by the Numbers; ></div> <p className="text-lg text-gray-600 max-w-3xl mx-auto"> Our track record speaks for itself - delivering exceptional results; and building lasting partnerships; ></div> ></div> <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8"> {}; <div key={index} className="text-center group"> <div className="bg-gray-50 rounded-xl p-8 h-full border border-gray-200 "hover": border-gray-300 hover:shadow-lg transition-all duration-300"> <div>Broken JSX</div> > {stat.icon} ></div> <div className="text-4xl font-bold text-gray-900 mb-2 group-"hover": text-blue-600 transition-colors"> {stat.number} ></div> <h3 className="text-xl font-semibold text-gray-900 mb-3"> {stat.label} ></div> <p className="text-gray-600 leading-relaxed"> {stat.description} ></div> ></div> ></div> ))} ></div> <div className="text-center mt-12"> <div className="bg-gradient-to-r from-blue-50 to-cyan-50 rounded-2xl p-8 border border-blue-200"> <h3 className="text-2xl font-bold text-gray-900 mb-4"> Join Our Success Story; ></div> <p className="text-gray-600 mb-6 max-w-2xl mx-auto"> Be part of the next 500+ successful projects and experience the; Zion Tech Group difference; ></div> <div className="flex flex-col "sm": flex-row gap-4 justify-center"> <div>Broken JSX</div> className="inline-flex items-center px-8 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition-colors duration-300"> Start Your Project; ></div> <div>Broken JSX</div> className="inline-flex items-center px-8 py-3 border-2 border-blue-600 text-blue-600 font-semibold rounded-lg hover:bg-blue-600 hover:text-white transition-all duration-300"> Learn More About Us; ></div> ></div> ></div> ></div> ></div> ></div> );} export default StatsSection;
=======

class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }
  
  static getDerivedStateFromError(error) {
    return { hasError: true };
  }
  
  componentDidCatch(error, errorInfo) {
    console.error('Error caught by boundary:', error, errorInfo);
  }
  
  render() {
    if (this.state.hasError) {
      return <div>Something went wrong.</div>;
    }
    
    return this.props.children;
  }
}
import React from \'react\'; export function StatsSection() {; const stats = [{; \"number\": \'500+\',; \"label\": \'Projects Completed\',; \"description\": \'Successfully delivered solutions\',; \"icon\": \'🚀\',; \"color\": \'from-purple-500 to-pink-500\';},; {}},; {}},; {}},; {}} ]; return (); <section className=\"py-16 bg-white\">\"; <div className=\"max-w-7xl mx-auto px-4 \"sm\": px-6 lg:px-8\">\"; <div className=\"text-center mb-12\">\" <h2 className=\"text-3xl md:text-4xl font-bold text-gray-900 mb-4\"> Zion Tech Group by the Numbers; ></div> <p className=\"text-lg text-gray-600 max-w-3xl mx-auto\"> Our track record speaks for itself - delivering exceptional results; and building lasting partnerships; ></div> ></div> <div className=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8\"> {}; <div key={index} className=\"text-center group\"> <div className=\"bg-gray-50 rounded-xl p-8 h-full border border-gray-200 \"hover\": border-gray-300 hover:shadow-lg transition-all duration-300\"> <div>Broken JSX</div> > {stat && stat.icon} ></div> <div className=\"text-4xl font-bold text-gray-900 mb-2 group-\"hover\": text-blue-600 transition-colors\"> {stat && stat.number} ></div> <h3 className=\"text-xl font-semibold text-gray-900 mb-3\"> {stat && stat.label} ></div> <p className=\"text-gray-600 leading-relaxed\"> {stat && stat.description} ></div> ></div> ></div> ))} ></div> <div className=\"text-center mt-12\"> <div className=\"bg-gradient-to-r from-blue-50 to-cyan-50 rounded-2xl p-8 border border-blue-200\"> <h3 className=\"text-2xl font-bold text-gray-900 mb-4\"> Join Our Success Story; ></div> <p className=\"text-gray-600 mb-6 max-w-2xl mx-auto\"> Be part of the next 500+ successful projects and experience the; Zion Tech Group difference; ></div> <div className=\"flex flex-col \"sm\": flex-row gap-4 justify-center\"> <div>Broken JSX</div> className=\"inline-flex items-center px-8 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition-colors duration-300\"> Start Your Project; ></div> <div>Broken JSX</div> className=\"inline-flex items-center px-8 py-3 border-2 border-blue-600 text-blue-600 font-semibold rounded-lg hover:bg-blue-600 hover:text-white transition-all duration-300\"> Learn More About Us; ></div> ></div> ></div> ></div> ></div> ></div> );} export default StatsSection;
const React from "react"; export function StatsSection() {; const stats = [{; number: "500+",; label: "Projects Completed",; description: "Successfully delivered solutions",; icon: "",; color: "from-purple-500 to-pink-500";},; {}},; {}},; {}},; {}} ]; return (); <section className="py-16 bg-white">"; <div className="max-w-7xl mx-auto px-4 sm: px-6 lg:px-8">"; <div className="text-center mb-12">" <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4"> Zion Tech Group by the Numbers; ></div> <p className="text-lg text-gray-600 max-w-3xl mx-auto"> Our track record speaks for itself - delivering exceptional results; and building lasting partnerships; ></div> ></div> <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8"> {}; <div key={index} className="text-center group"> <div className="bg-gray-50 rounded-xl p-8 h-full border border-gray-200 hover: border-gray-300 hover:shadow-lg transition-all duration-300"> <div>Broken JSX</div> > {stat && stat.icon} ></div> <div className="text-4xl font-bold text-gray-900 mb-2 group-hover: text-blue-600 transition-colors"> {stat && stat.number} ></div> <h3 className="text-xl font-semibold text-gray-900 mb-3"> {stat && stat.label} ></div> <p className="text-gray-600 leading-relaxed"> {stat && stat.description} ></div> ></div> ></div> ))} ></div> <div className="text-center mt-12"> <div className="bg-gradient-to-r from-blue-50 to-cyan-50 rounded-2xl p-8 border border-blue-200"> <h3 className="text-2xl font-bold text-gray-900 mb-4"> Join Our Success Story; ></div> <p className="text-gray-600 mb-6 max-w-2xl mx-auto"> Be part of the next 500+ successful projects and experience the; Zion Tech Group difference; ></div> <div className="flex flex-col sm: flex-row gap-4 justify-center"> <div>Broken JSX</div> className="inline-flex items-center px-8 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition-colors duration-300"> Start Your Project; ></div> <div>Broken JSX</div> className="inline-flex items-center px-8 py-3 border-2 border-blue-600 text-blue-600 font-semibold rounded-lg hover:bg-blue-600 hover:text-white transition-all duration-300"> Learn More About Us; ></div> ></div> ></div> ></div> ></div> ></div> );} export default StatsSection;'"'"

import _React from 'react'; export function StatsSection() {; const stats = [{; "number": '500+',; "label": 'Projects Completed',; "description": 'Successfully delivered solutions',; "icon": '🚀',; "color": 'from-purple-500 to-pink-500';},; {}},; {}},; {}},; {}} ]; return (); <section className="py-16 bg-white">"; <div className="max-w-7xl mx-auto px-4 "sm": px-6 lg:px-8">"; <div className="text-center mb-12">" <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4"> Zion Tech Group by the Numbers; ></div> <p className="text-lg text-gray-600 max-w-3xl mx-auto"> Our track record speaks for itself - delivering exceptional results; and building lasting partnerships; ></div> ></div> <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8"> {}; <div key={index} className="text-center group"> <div className="bg-gray-50 rounded-xl p-8 h-full border border-gray-200 "hover": border-gray-300 hover:shadow-lg transition-all duration-300"> <div>Broken JSX</div> > {stat && stat.icon} ></div> <div className="text-4xl font-bold text-gray-900 mb-2 group-"hover": text-blue-600 transition-colors"> {stat && stat.number} ></div> <h3 className="text-xl font-semibold text-gray-900 mb-3"> {stat && stat.label} ></div> <p className="text-gray-600 leading-relaxed"> {stat && stat.description} ></div> ></div> ></div> ))} ></div> <div className="text-center mt-12"> <div className="bg-gradient-to-r from-blue-50 to-cyan-50 rounded-2xl p-8 border border-blue-200"> <h3 className="text-2xl font-bold text-gray-900 mb-4"> Join Our Success Story; ></div> <p className="text-gray-600 mb-6 max-w-2xl mx-auto"> Be part of the next 500+ successful projects and experience the; Zion Tech Group difference; ></div> <div className="flex flex-col "sm": flex-row gap-4 justify-center"> <div>Broken JSX</div> className="inline-flex items-center px-8 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition-colors duration-300"> Start Your Project; ></div> <div>Broken JSX</div> className="inline-flex items-center px-8 py-3 border-2 border-blue-600 text-blue-600 font-semibold rounded-lg hover:bg-blue-600 hover:text-white transition-all duration-300"> Learn More About Us; ></div> ></div> ></div> ></div> ></div> ></div> );} export default StatsSection;

>>>>>>> cursor/expand-services-advertise-and-build-project-4b36
