import React from 'react'
import Link from 'next/link'
import { servicesCatalog } from '../../data/services'
      {' '
        {' '
          {' '
          </h3>{' '
            {' '
            ))}{' '
          </ul>{' '
        </div>{' '
          {' '
          </h3>{' '
            {' '
                {' '
                  {' '
                  {svc.title}{' '
                </Link>{' '
            ))}{' '
          </ul>{' '
        </div>{' '
      </div>{' '
cursor/fix-lint-push-and-merge-to-main-f3c1
