import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { ;
  ChevronDown, ;
  Zap, ;
  Brain, ;
  Shield, ;
  Users, ;
  HardDrive, ;
  TrendingUp, ;
  Building2, ;
  FileText, ;
  HelpCircle, ;
  BarChart3,;
  Rocket,;
  Server,;
  Cloud,;
  Lock,;
  Workflow,;
  Database,;
  MessageCircle,;
  CheckCircle,;
  ArrowRight,;
  ExternalLink,;
  Handshake,;
  Monitor,;
  GraduationCap,;
  Lightbulb,;
  Code,;
  Activity,;
  Target;
} from 'lucide-react';
;
interface MainNavigationProps {;
  className?: "string;
"}
;
export function MainNavigation("props": "MainNavigationProps) {;
  const [isServicesOpen", setIsServicesOpen] = useState<boolean>(false);
  const [isSolutionsOpen, setIsSolutionsOpen] = useState<boolean>(false);
  const [isCompanyOpen, setIsCompanyOpen] = useState<boolean>(false);
;
  return (;
    <nav className={`flex items-center space-x-8 ${props.className || ''}`}>;
      {/* Home */}
      <Link ;
        to="/" ;
        className="text-sm font-medium text-zion-slate-light "hover": "text-zion-cyan transition-colors";
      >;
        Home;
      </Link>;
      {/* Services Dropdown */"}
      <div className="relative group">;
        <button;
          onMouseEnter={() => setIsServicesOpen(true)}
          onMouseLeave={() => setIsServicesOpen(false)}
          className="flex items-center space-x-1 text-sm font-medium text-zion-slate-light "hover": "text-zion-cyan transition-colors";
        >;
          <Zap className="w-4 h-4" />;
          <span>Services</span>;
          <ChevronDown className="w-3 h-3" />;
        </button>;
        ;
        {isServicesOpen && (;
          <div ;
            onMouseEnter={() => setIsServicesOpen(true)"} ;