
 * Dynamic component imports - reduces initial bundle size
 * Auto-generated by performance optimizer
 */
import dynamic from 'next/
    React.createElement('div', { className: any
    React.createElement('div', { className: any
   () => import('../components/charts/
   () => import('../components/pdf/
   () => import('../components/video/
   () => import('../components/ar/
   () => import('../components/editor/
 Replace: import Chart from '../components/charts/Chart';// With: import { DynamicChart as Chart } from '@/utils/
 With: import { DynamicChart as Chart } from '@/utils/
 Usage examples: any
 With: import { DynamicChart as Chart } from '@/utils/
 Replace: import Chart from '../components / charts / Chart';// With: import { DynamicChart as Chart } from '@/utils /
 With: import { DynamicChart as Chart } from '@/utils /
 Usage examples: any
 With: import { DynamicChart as Chart } from '@/utils /