/**
 * Dynamic component imports - reduces initial bundle size
 * Auto-generated by performance optimizer
 */
import React from 'react';
import dynamic from 'next/dynamic';
const LoadingSpinner = null;