/**
 * Dynamic component imports - reduces initial bundle size
 * Auto-generated by performance optimizer
 */
import React from 'react';
import dynamic from 'next/dynamic';

const _LoadingSpinner = () => React.createElement('div', 
  {_className: "flex items-center justify-center p-8"},
  React.createElement('div', {_className: "animate-spin rounded-full h-8 w-8 border-b-2 border-primary"})
);

const _LoadingSkeleton = () => React.createElement('div',
  {_className: "animate-pulse space-y-4"},
  React.createElement('div', {_className: "h-4 bg-gray-200 rounded w-3/4"}),
  React.createElement('div', {_className: "h-4 bg-gray-200 rounded w-1/2"}),
  React.createElement('div', {_className: "h-32 bg-gray-200 rounded"})
);

// Chart components (heavy - only load when needed)
// TODO: Uncomment when Chart component is available
// export const _DynamicChart = dynamic(_//   () => import('../components/charts/Chart'),
//   {_//     loading: LoadingSkeleton, _//     ssr: false 
//}
// );

export const _DynamicPieChart = dynamic(_() => import('recharts').then(mod => ({_default: mod.PieChart})),
  {_loading: LoadingSkeleton, _ssr: false}
);

export const _DynamicBarChart = dynamic(_() => import('recharts').then(mod => ({_default: mod.BarChart})),
  {_loading: LoadingSkeleton, _ssr: false}
);

// TODO: Uncomment when these components are available
// export const _DynamicPDFGenerator = dynamic(_//   () => import('../components/pdf/PDFGenerator'),
//   {_//     loading: LoadingSpinner, _//     ssr: false 
//}
// );

// export const _DynamicVideoPlayer = dynamic(_//   () => import('../components/video/VideoPlayer'),
//   {_//     loading: LoadingSkeleton, _//     ssr: false 
//}
// );

// export const _DynamicModelViewer = dynamic(_//   () => import('../components/ar/ModelViewer'),
//   {_//     loading: LoadingSpinner, _//     ssr: false 
//}
// );

// export const _DynamicRichEditor = dynamic(_//   () => import('../components/editor/RichTextEditor'),
//   {_//     loading: LoadingSpinner, _//     ssr: false 
//}
// );

// Virtual list for large datasets
export const _DynamicVirtualList = dynamic(_() => import('react-window').then(mod => ({_default: mod.FixedSizeList})),
  {_loading: LoadingSkeleton, _ssr: false}
);

// Usage examples:
// Replace: import Chart from '../components/charts/Chart';
// With: import {_DynamicChart as Chart} from '@/utils/dynamicComponents';
