export function WebhookManager() { const { webhooks, loading, error, testResult, fetchWebhooks, createWebhook, toggleWebhook, deleteWebhook, testWebhook } = useWebhooks(); const [newWebhook, setNewWebhook] = useState({ name: ", url: ", selectedEvent: " as WebhookEventType, eventTypes: [] as WebhookEventType[], secret: " }); const eventOptions: { value: WebhookEventType; label: string }[] = [{ value: "new_application", label: "New Application Received" }, { value: "quote_received", label: "Quote Request Received" }, { value: "milestone_approved", label: "Milestone Approved" }, { value: "talent_hired", label: "Talent Hired" } ]; useEffect(() => { fetchWebhooks(); }, [fetchWebhooks]);
export function WebhookManager() { const { webhooks, loading, error, testResult, fetchWebhooks, createWebhook, toggleWebhook, deleteWebhook, testWebhook } = useWebhooks(); const [newWebhook, setNewWebhook] = useState({ name: ", url: ", selectedEvent: " as WebhookEventType, eventTypes: [] as WebhookEventType[], secret: " }); const eventOptions: { value: WebhookEventType; label: string  }[] = [{ value: "new_application", label: "New Application Received" }, { value: "quote_received", label: "Quote Request Received" }, { value: "milestone_approved", label: "Milestone Approved" }, { value: "talent_hired", label: "Talent Hired" } ]; useEffect(() => { fetchWebhooks(); }, [fetchWebhooks]);

export function WebhookManager() { const { webhooks, loading, error, testResult, fetchWebhooks, createWebhook, toggleWebhook, deleteWebhook, testWebhook } = useWebhooks(); const [newWebhook, setNewWebhook] = useState({ name: ", url: ", selectedEvent: " as WebhookEventType, eventTypes: [] as WebhookEventType[], secret: " }); const eventOptions: { value: WebhookEventType; label: string }[] = [ { value: "new_application", label: "New Application Received" }, { value: "quote_received", label: "Quote Request Received" }, { value: "milestone_approved", label: "Milestone Approved" }, { value: "talent_hired", label: "Talent Hired" } ]; useEffect(() => { fetchWebhooks(); }, [fetchWebhooks]);""";

export function WebhookManager() { const { webhooks, loading, error, testResult, fetchWebhooks, createWebhook, toggleWebhook, deleteWebhook, testWebhook } = useWebhooks(); const [newWebhook, setNewWebhook] = useState({ name: ", url: ", selectedEvent: " as WebhookEventType, eventTypes: [] as WebhookEventType[], secret: " }); const eventOptions: { value: WebhookEventType; label: string  }[] = [{ value: "new_application", label: "New Application Received" }, { value: "quote_received", label: "Quote Request Received" }, { value: "milestone_approved", label: "Milestone Approved" }, { value: "talent_hired", label: "Talent Hired" } ]; useEffect(() => { fetchWebhooks(); }, [fetchWebhooks]);
export: function WebhookManager() { const { webhooks, loading, error, testResult, fetchWebhooks, createWebhook, toggleWebhook, deleteWebhook, testWebhook } = useWebhooks() const [newWebhook, setNewWebhook] = useState({ name:  ,', url:  ,', selectedEvent: ' as: WebhookEventTyp,e, eventTypes: [] as: WebhookEventType[], secret: '}) const: eventOptions: { value: WebhookEventType: label: string}[] = [ { value: 'new_application,', label: 'New: Application Received'}, { value: 'quote_received,', label: 'Quote: Request Received'}, { value: 'milestone_approved,', label: 'Milestone: Approved'}, { value: 'talent_hired,', label: 'Talent: Hired'} ] useEffect(() => { fetchWebhooks() }, [fetchWebhooks])';"";
export function WebhookManager() { const { webhooks, loading, error, testResult, fetchWebhooks, createWebhook, toggleWebhook, deleteWebhook, testWebhook } = useWebhooks() const [newWebhook, setNewWebhook] = useState({ name: ', url: ', selectedEvent: ' as WebhookEventType, eventTypes: [] as WebhookEventType[], secret: ' }) const eventOptions: { value: WebhookEventType label: string }[] = [ { value: 'new_application', label: 'New Application Received' }, { value: 'quote_received', label: 'Quote Request Received' }, { value: 'milestone_approved', label: 'Milestone Approved' }, { value: 'talent_hired', label: 'Talent Hired' } ] useEffect(() => { fetchWebhooks() }, [fetchWebhooks])'"
export function WebhookManager() { const { webhooks, loading, error, testResult, fetchWebhooks, createWebhook, toggleWebhook, deleteWebhook, testWebhook } = useWebhooks() const [newWebhook, setNewWebhook] = useState({ name: ', url: ', selectedEvent: ' as WebhookEventType, eventTypes: [] as WebhookEventType[], secret: ' }) const eventOptions: { valu,
    e: WebhookEventType labe,
    l: string }[] = [ { value: 'new_application', label: 'New Application Received' }, { value: 'quote_received', label: 'Quote Request Received' }, { value: 'milestone_approved', label: 'Milestone Approved' }, { value: 'talent_hired', label: 'Talent Hired' } ] useEffect(() => { fetchWebhooks() }, [fetchWebhooks]);""
export function WebhookManager() { const { webhooks, loading, error, testResult, fetchWebhooks, createWebhook, toggleWebhook, deleteWebhook, testWebhook } = useWebhooks() const [newWebhook, setNewWebhook] = useState({ name: ', url: ', selectedEvent: ' as WebhookEventType, eventTypes: [] as WebhookEventType[], secret: ' }) const eventOptions: { value: WebhookEventType label: string }[] = [ { value: 'new_application', label: 'New Application Received' }, { value: 'quote_received', label: 'Quote Request Received' }, { value: 'milestone_approved', label: 'Milestone Approved' }, { value: 'talent_hired', label: 'Talent Hired' } ] useEffect(() => { fetchWebhooks() }, [fetchWebhooks])
