<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> origin/cursor/integrate-build-improve-and-re-verify-7ffc
=======
import _React from "react"; "export { function };export default function PostCard({ post }) { return (); <div className="bg-white/10" backdrop-blur-sm rounded-lg p-4 mb-4">" <div className="flex" items-start space-x-4>" <img" src="{post.author.avatar}" alt="{post.author.name}" className="w-10" h-10 rounded-full" / / />" <div className="flex-1">" <h3 className="text-lg font-semibold text-zion-cyan mb-2> {post.title}" </h3>" <p className="text-zion-slate-light" mb-3 line-clamp-3>" {post.content}" </p> <div className="flex" items-center justify-between text-sm text-zion-slate-light">" <span>By {post.author.name}</span> <span>{new Date(post.createdAt).toLocaleDateString()}</span> </div> <div className="flex items-center space-x-4 mt-2 text-sm text-zion-slate-light"> <span>{post.replies.length} replies</span> <span>{post.likes} likes</span> ";"export default function PostCard({ post }) {} return()"; <div className = "bg-white/10 backdrop-blur-sm rounded-lg p-4 mb-4"> <div className="flex items-start space-x-4">"; <div>Broken JSX</div> / >"" <div className="flex-1"> <h3 className="text-lg font-semibold text-zion-cyan mb-2"> {post.title}" </h3>"" <p className="text-zion-slate-light mb-3 line-clamp-3">"; {post.content}" </p>"" <div className="flex items-center justify-between text-sm text-zion-slate-light">"; <span>By {post.author.name}></div> <span>{new Date(post.createdAt).toLocaleDateString()}</span>" </div>"" <div className="flex items-center space-x-4 mt-2 text-sm text-zion-slate-light"> <span>{post.replies.length} replies></div> <span>{post.likes} likes></div> <span>{post.views} views></div> ></div> ></div> ></div> </div>)} export { PostCard }; export { PostCard }; export { PostCard }; export { PostCard }; export { PostCard };
=======
=======
>>>>>>> 8e2e4d4581f20cdfc8804c591c8c2f9544e58358
<<<<<<< HEAD
>>>>>>> origin/cursor/automate-test-improve-and-merge-code-646c
=======
>>>>>>> 64929ba0aca90db53d3fc12fa49c90c7c2110f3c

=======
import _React from "react"; "export { function };export default function PostCard({ post }) { return (); <div className="bg-white/10" backdrop-blur-sm rounded-lg p-4 mb-4">" <div className="flex" items-start space-x-4>" <img" src="{post.author.avatar}" alt="{post.author.name}" className="w-10" h-10 rounded-full" / / />" <div className="flex-1">" <h3 className="text-lg font-semibold text-zion-cyan mb-2> {post.title}" </h3>" <p className="text-zion-slate-light" mb-3 line-clamp-3>" {post.content}" </p> <div className="flex" items-center justify-between text-sm text-zion-slate-light">" <span>By {post.author.name}</span> <span>{new Date(post.createdAt).toLocaleDateString()}</span> </div> <div className="flex items-center space-x-4 mt-2 text-sm text-zion-slate-light"> <span>{post.replies.length} replies</span> <span>{post.likes} likes</span> ";"export default function PostCard({ post }) {} return()"; <div className = "bg-white/10 backdrop-blur-sm rounded-lg p-4 mb-4"> <div className="flex items-start space-x-4">"; <div>Broken JSX</div> / >"" <div className="flex-1"> <h3 className="text-lg font-semibold text-zion-cyan mb-2"> {post.title}" </h3>"" <p className="text-zion-slate-light mb-3 line-clamp-3">"; {post.content}" </p>"" <div className="flex items-center justify-between text-sm text-zion-slate-light">"; <span>By {post.author.name}></div> <span>{new Date(post.createdAt).toLocaleDateString()}</span>" </div>"" <div className="flex items-center space-x-4 mt-2 text-sm text-zion-slate-light"> <span>{post.replies.length} replies></div> <span>{post.likes} likes></div> <span>{post.views} views></div> ></div> ></div> ></div> </div>)} export { PostCard }; export { PostCard }; export { PostCard }; export { PostCard }; export { PostCard };
>>>>>>> origin/cursor/fix-website-loading-errors-and-merge-8ae2
class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }
  
  static getDerivedStateFromError(error) {
    return { hasError: true };
  }
  
  componentDidCatch(error, errorInfo) {
    console.error('Error caught by boundary:', error, errorInfo);
  }
  
  render() {
    if (this.state.hasError) {
      return <div>Something went wrong.</div>;
    }
    
    return this.props.children;
  }
}
import React from \"react\"; \"export { function };export default function PostCard({ post }) { return (); <div className=\"bg-white/10\" backdrop-blur-sm rounded-lg p-4 mb-4\">\" <div className=\"flex\" items-start space-x-4>\" <img\" src=\"{post && post.author.avatar}\" alt=\"{post && post.author.name}\" className=\"w-10\" h-10 rounded-full\" / / />\" <div className=\"flex-1\">\" <h3 className=\"text-lg font-semibold text-zion-cyan mb-2> {post && post.title}\" </h3>\" <p className=\"text-zion-slate-light\" mb-3 line-clamp-3>\" {post && post.content}\" </p> <div className=\"flex\" items-center justify-between text-sm text-zion-slate-light\">\" <span>By {post && post.author.name}</span> <span>{new Date(post && post.createdAt).toLocaleDateString()}</span> </div> <div className=\"flex items-center space-x-4 mt-2 text-sm text-zion-slate-light\"> <span>{post && post.replies.length} replies</span> <span>{post && post.likes} likes</span> \";\"export default function PostCard({ post }) {} return ()\"; <div className = \"bg-white/10 backdrop-blur-sm rounded-lg p-4 mb-4\"> <div className=\"flex items-start space-x-4\">\"; <div>Broken JSX</div> / >\"" <div className=\"flex-1\"> <h3 className=\"text-lg font-semibold text-zion-cyan mb-2\"> {post && post.title}\" </h3>\"" <p className=\"text-zion-slate-light mb-3 line-clamp-3\">\"; {post && post.content}\" </p>\"" <div className=\"flex items-center justify-between text-sm text-zion-slate-light\">\"; <span>By {post && post.author.name}></div> <span>{new Date(post && post.createdAt).toLocaleDateString()}</span>\" </div>\"" <div className=\"flex items-center space-x-4 mt-2 text-sm text-zion-slate-light\"> <span>{post && post.replies.length} replies></div> <span>{post && post.likes} likes></div> <span>{post && post.views} views></div> ></div> ></div> ></div> </div>)} export { PostCard }; export { PostCard }; export { PostCard }; export { PostCard }; export { PostCard };
const React from "react"; "export { function };export default function PostCard({ post }) { return (); <div className="bg-white/10" backdrop-blur-sm rounded-lg p-4 mb-4">" <div className="flex" items-start space-x-4>" <img" src="{post && post.author.avatar}" alt="{post && post.author.name}" className="w-10" h-10 rounded-full" / / />" <div className="flex-1">" <h3 className="text-lg font-semibold text-zion-cyan mb-2> {post && post.title}" </h3>" <p className="text-zion-slate-light" mb-3 line-clamp-3>" {post && post.content}" </p> <div className="flex" items-center justify-between text-sm text-zion-slate-light">" <span>By {post && post.author.name}</span> <span>{new Date(post && post.createdAt).toLocaleDateString()}</span> </div> <div className="flex items-center space-x-4 mt-2 text-sm text-zion-slate-light"> <span>{post && post.replies.length} replies</span> <span>{post && post.likes} likes</span> ";"export default function PostCard({ post }) {} return ()"; <div className = "bg-white/10 backdrop-blur-sm rounded-lg p-4 mb-4"> <div className="flex items-start space-x-4">"; <div>Broken JSX</div> / >"" <div className="flex-1"> <h3 className="text-lg font-semibold text-zion-cyan mb-2"> {post && post.title}" </h3>"" <p className="text-zion-slate-light mb-3 line-clamp-3">"; {post && post.content}" </p>"" <div className="flex items-center justify-between text-sm text-zion-slate-light">"; <span>By {post && post.author.name}></div> <span>{new Date(post && post.createdAt).toLocaleDateString()}</span>" </div>"" <div className="flex items-center space-x-4 mt-2 text-sm text-zion-slate-light"> <span>{post && post.replies.length} replies></div> <span>{post && post.likes} likes></div> <span>{post && post.views} views></div> ></div> ></div> ></div> </div>)} export { PostCard }; export { PostCard }; export { PostCard }; export { PostCard }; export { PostCard };""

import _React from "react"; "export { function };export default function PostCard({ post }) { return (); <div className="bg-white/10" backdrop-blur-sm rounded-lg p-4 mb-4">" <div className="flex" items-start space-x-4>" <img" src="{post && post.author.avatar}" alt="{post && post.author.name}" className="w-10" h-10 rounded-full" / / />" <div className="flex-1">" <h3 className="text-lg font-semibold text-zion-cyan mb-2> {post && post.title}" </h3>" <p className="text-zion-slate-light" mb-3 line-clamp-3>" {post && post.content}" </p> <div className="flex" items-center justify-between text-sm text-zion-slate-light">" <span>By {post && post.author.name}</span> <span>{new Date(post && post.createdAt).toLocaleDateString()}</span> </div> <div className="flex items-center space-x-4 mt-2 text-sm text-zion-slate-light"> <span>{post && post.replies.length} replies</span> <span>{post && post.likes} likes</span> ";"export default function PostCard({ post }) {} return ()"; <div className = "bg-white/10 backdrop-blur-sm rounded-lg p-4 mb-4"> <div className="flex items-start space-x-4">"; <div>Broken JSX</div> / >"" <div className="flex-1"> <h3 className="text-lg font-semibold text-zion-cyan mb-2"> {post && post.title}" </h3>"" <p className="text-zion-slate-light mb-3 line-clamp-3">"; {post && post.content}" </p>"" <div className="flex items-center justify-between text-sm text-zion-slate-light">"; <span>By {post && post.author.name}></div> <span>{new Date(post && post.createdAt).toLocaleDateString()}</span>" </div>"" <div className="flex items-center space-x-4 mt-2 text-sm text-zion-slate-light"> <span>{post && post.replies.length} replies></div> <span>{post && post.likes} likes></div> <span>{post && post.views} views></div> ></div> ></div> ></div> </div>)} export { PostCard }; export { PostCard }; export { PostCard }; export { PostCard }; export { PostCard };

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> c56320a4e91ebfd91859a6eed8c13818d8c9efd6
>>>>>>> origin/cursor/automate-test-improve-and-merge-code-646c
=======
=======
import _React from "react"; "export { function };export default function PostCard({ post }) { return (); <div className="bg-white/10" backdrop-blur-sm rounded-lg p-4 mb-4">" <div className="flex" items-start space-x-4>" <img" src="{post.author.avatar}" alt="{post.author.name}" className="w-10" h-10 rounded-full" / / />" <div className="flex-1">" <h3 className="text-lg font-semibold text-zion-cyan mb-2> {post.title}" </h3>" <p className="text-zion-slate-light" mb-3 line-clamp-3>" {post.content}" </p> <div className="flex" items-center justify-between text-sm text-zion-slate-light">" <span>By {post.author.name}</span> <span>{new Date(post.createdAt).toLocaleDateString()}</span> </div> <div className="flex items-center space-x-4 mt-2 text-sm text-zion-slate-light"> <span>{post.replies.length} replies</span> <span>{post.likes} likes</span> ";"export default function PostCard({ post }) {} return()"; <div className = "bg-white/10 backdrop-blur-sm rounded-lg p-4 mb-4"> <div className="flex items-start space-x-4">"; <div>Broken JSX</div> / >"" <div className="flex-1"> <h3 className="text-lg font-semibold text-zion-cyan mb-2"> {post.title}" </h3>"" <p className="text-zion-slate-light mb-3 line-clamp-3">"; {post.content}" </p>"" <div className="flex items-center justify-between text-sm text-zion-slate-light">"; <span>By {post.author.name}></div> <span>{new Date(post.createdAt).toLocaleDateString()}</span>" </div>"" <div className="flex items-center space-x-4 mt-2 text-sm text-zion-slate-light"> <span>{post.replies.length} replies></div> <span>{post.likes} likes></div> <span>{post.views} views></div> ></div> ></div> ></div> </div>)} export { PostCard }; export { PostCard }; export { PostCard }; export { PostCard }; export { PostCard };
>>>>>>> main
>>>>>>> 8e2e4d4581f20cdfc8804c591c8c2f9544e58358
=======
import React from \"react\"; \"export { function };export default function PostCard({ post }) { return (); <div className=\"bg-white/10\" backdrop-blur-sm rounded-lg p-4 mb-4\">\" <div className=\"flex\" items-start space-x-4>\" <img\" src=\"{post.author.avatar}\" alt=\"{post.author.name}\" className=\"w-10\" h-10 rounded-full\" / / />\" <div className=\"flex-1\">\" <h3 className=\"text-lg font-semibold text-zion-cyan mb-2> {post.title}\" </h3>\" <p className=\"text-zion-slate-light\" mb-3 line-clamp-3>\" {post.content}\" </p> <div className=\"flex\" items-center justify-between text-sm text-zion-slate-light\">\" <span>By {post.author.name}</span> <span>{new Date(post.createdAt).toLocaleDateString()}</span> </div> <div className=\"flex items-center space-x-4 mt-2 text-sm text-zion-slate-light\"> <span>{post.replies.length} replies</span> <span>{post.likes} likes</span> \";\"export default function PostCard({ post }) {} return()\"; <div className = \"bg-white/10 backdrop-blur-sm rounded-lg p-4 mb-4\"> <div className=\"flex items-start space-x-4\">\"; <div>Broken JSX</div> / >\"" <div className=\"flex-1\"> <h3 className=\"text-lg font-semibold text-zion-cyan mb-2\"> {post.title}\" </h3>\"" <p className=\"text-zion-slate-light mb-3 line-clamp-3\">\"; {post.content}\" </p>\"" <div className=\"flex items-center justify-between text-sm text-zion-slate-light\">\"; <span>By {post.author.name}></div> <span>{new Date(post.createdAt).toLocaleDateString()}</span>\" </div>\"" <div className=\"flex items-center space-x-4 mt-2 text-sm text-zion-slate-light\"> <span>{post.replies.length} replies></div> <span>{post.likes} likes></div> <span>{post.views} views></div> ></div> ></div> ></div> </div>)} export { PostCard }; export { PostCard }; export { PostCard }; export { PostCard }; export { PostCard };
const React from "react"; "export { function };export default function PostCard({ post }) { return (); <div className="bg-white/10" backdrop-blur-sm rounded-lg p-4 mb-4">" <div className="flex" items-start space-x-4>" <img" src="{post.author.avatar}" alt="{post.author.name}" className="w-10" h-10 rounded-full" / / />" <div className="flex-1">" <h3 className="text-lg font-semibold text-zion-cyan mb-2> {post.title}" </h3>" <p className="text-zion-slate-light" mb-3 line-clamp-3>" {post.content}" </p> <div className="flex" items-center justify-between text-sm text-zion-slate-light">" <span>By {post.author.name}</span> <span>{new Date(post.createdAt).toLocaleDateString()}</span> </div> <div className="flex items-center space-x-4 mt-2 text-sm text-zion-slate-light"> <span>{post.replies.length} replies</span> <span>{post.likes} likes</span> ";"export default function PostCard({ post }) {} return()"; <div className = "bg-white/10 backdrop-blur-sm rounded-lg p-4 mb-4"> <div className="flex items-start space-x-4">"; <div>Broken JSX</div> / >"" <div className="flex-1"> <h3 className="text-lg font-semibold text-zion-cyan mb-2"> {post.title}" </h3>"" <p className="text-zion-slate-light mb-3 line-clamp-3">"; {post.content}" </p>"" <div className="flex items-center justify-between text-sm text-zion-slate-light">"; <span>By {post.author.name}></div> <span>{new Date(post.createdAt).toLocaleDateString()}</span>" </div>"" <div className="flex items-center space-x-4 mt-2 text-sm text-zion-slate-light"> <span>{post.replies.length} replies></div> <span>{post.likes} likes></div> <span>{post.views} views></div> ></div> ></div> ></div> </div>)} export { PostCard }; export { PostCard }; export { PostCard }; export { PostCard }; export { PostCard };""
import _React from "react"; "export { function };export default function PostCard({ post }) { return (); <div className="bg-white/10" backdrop-blur-sm rounded-lg p-4 mb-4">" <div className="flex" items-start space-x-4>" <img" src="{post.author.avatar}" alt="{post.author.name}" className="w-10" h-10 rounded-full" / / />" <div className="flex-1">" <h3 className="text-lg font-semibold text-zion-cyan mb-2> {post.title}" </h3>" <p className="text-zion-slate-light" mb-3 line-clamp-3>" {post.content}" </p> <div className="flex" items-center justify-between text-sm text-zion-slate-light">" <span>By {post.author.name}</span> <span>{new Date(post.createdAt).toLocaleDateString()}</span> </div> <div className="flex items-center space-x-4 mt-2 text-sm text-zion-slate-light"> <span>{post.replies.length} replies</span> <span>{post.likes} likes</span> ";"export default function PostCard({ post }) {} return()"; <div className = "bg-white/10 backdrop-blur-sm rounded-lg p-4 mb-4"> <div className="flex items-start space-x-4">"; <div>Broken JSX</div> / >"" <div className="flex-1"> <h3 className="text-lg font-semibold text-zion-cyan mb-2"> {post.title}" </h3>"" <p className="text-zion-slate-light mb-3 line-clamp-3">"; {post.content}" </p>"" <div className="flex items-center justify-between text-sm text-zion-slate-light">"; <span>By {post.author.name}></div> <span>{new Date(post.createdAt).toLocaleDateString()}</span>" </div>"" <div className="flex items-center space-x-4 mt-2 text-sm text-zion-slate-light"> <span>{post.replies.length} replies></div> <span>{post.likes} likes></div> <span>{post.views} views></div> ></div> ></div> ></div> </div>)} export { PostCard }; export { PostCard }; export { PostCard }; export { PostCard }; export { PostCard };
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> d0b4cabda824e2db66cecb53192832d7e749a326
=======
>>>>>>> 99482a9199aaf93c62fadf06056b12429832a7df
=======
>>>>>>> f8e9d8204b854980b1ebe0327134be4447b2409a
>>>>>>> c56320a4e91ebfd91859a6eed8c13818d8c9efd6
=======
>>>>>>> 99482a9199aaf93c62fadf06056b12429832a7df
=======
>>>>>>> f8e9d8204b854980b1ebe0327134be4447b2409a
=======
>>>>>>> d0b4cabda824e2db66cecb53192832d7e749a326
>>>>>>> main
<<<<<<< HEAD
>>>>>>> origin/cursor/integrate-build-improve-and-re-verify-7ffc
=======
>>>>>>> 8e2e4d4581f20cdfc8804c591c8c2f9544e58358
>>>>>>> origin/cursor/automate-test-improve-and-merge-code-646c
=======
>>>>>>> origin/cursor/fix-website-loading-errors-and-merge-8ae2
=======
import React from \"react\"; \"export { function };export default function PostCard({ post }) { return (); <div className=\"bg-white/10\" backdrop-blur-sm rounded-lg p-4 mb-4\">\" <div className=\"flex\" items-start space-x-4>\" <img\" src=\"{post.author.avatar}\" alt=\"{post.author.name}\" className=\"w-10\" h-10 rounded-full\" / / />\" <div className=\"flex-1\">\" <h3 className=\"text-lg font-semibold text-zion-cyan mb-2> {post.title}\" </h3>\" <p className=\"text-zion-slate-light\" mb-3 line-clamp-3>\" {post.content}\" </p> <div className=\"flex\" items-center justify-between text-sm text-zion-slate-light\">\" <span>By {post.author.name}</span> <span>{new Date(post.createdAt).toLocaleDateString()}</span> </div> <div className=\"flex items-center space-x-4 mt-2 text-sm text-zion-slate-light\"> <span>{post.replies.length} replies</span> <span>{post.likes} likes</span> \";\"export default function PostCard({ post }) {} return()\"; <div className = \"bg-white/10 backdrop-blur-sm rounded-lg p-4 mb-4\"> <div className=\"flex items-start space-x-4\">\"; <div>Broken JSX</div> / >\"" <div className=\"flex-1\"> <h3 className=\"text-lg font-semibold text-zion-cyan mb-2\"> {post.title}\" </h3>\"" <p className=\"text-zion-slate-light mb-3 line-clamp-3\">\"; {post.content}\" </p>\"" <div className=\"flex items-center justify-between text-sm text-zion-slate-light\">\"; <span>By {post.author.name}></div> <span>{new Date(post.createdAt).toLocaleDateString()}</span>\" </div>\"" <div className=\"flex items-center space-x-4 mt-2 text-sm text-zion-slate-light\"> <span>{post.replies.length} replies></div> <span>{post.likes} likes></div> <span>{post.views} views></div> ></div> ></div> ></div> </div>)} export { PostCard }; export { PostCard }; export { PostCard }; export { PostCard }; export { PostCard };
const React from "react"; "export { function };export default function PostCard({ post }) { return (); <div className="bg-white/10" backdrop-blur-sm rounded-lg p-4 mb-4">" <div className="flex" items-start space-x-4>" <img" src="{post.author.avatar}" alt="{post.author.name}" className="w-10" h-10 rounded-full" / / />" <div className="flex-1">" <h3 className="text-lg font-semibold text-zion-cyan mb-2> {post.title}" </h3>" <p className="text-zion-slate-light" mb-3 line-clamp-3>" {post.content}" </p> <div className="flex" items-center justify-between text-sm text-zion-slate-light">" <span>By {post.author.name}</span> <span>{new Date(post.createdAt).toLocaleDateString()}</span> </div> <div className="flex items-center space-x-4 mt-2 text-sm text-zion-slate-light"> <span>{post.replies.length} replies</span> <span>{post.likes} likes</span> ";"export default function PostCard({ post }) {} return()"; <div className = "bg-white/10 backdrop-blur-sm rounded-lg p-4 mb-4"> <div className="flex items-start space-x-4">"; <div>Broken JSX</div> / >"" <div className="flex-1"> <h3 className="text-lg font-semibold text-zion-cyan mb-2"> {post.title}" </h3>"" <p className="text-zion-slate-light mb-3 line-clamp-3">"; {post.content}" </p>"" <div className="flex items-center justify-between text-sm text-zion-slate-light">"; <span>By {post.author.name}></div> <span>{new Date(post.createdAt).toLocaleDateString()}</span>" </div>"" <div className="flex items-center space-x-4 mt-2 text-sm text-zion-slate-light"> <span>{post.replies.length} replies></div> <span>{post.likes} likes></div> <span>{post.views} views></div> ></div> ></div> ></div> </div>)} export { PostCard }; export { PostCard }; export { PostCard }; export { PostCard }; export { PostCard };""
import _React from "react"; "export { function };export default function PostCard({ post }) { return (); <div className="bg-white/10" backdrop-blur-sm rounded-lg p-4 mb-4">" <div className="flex" items-start space-x-4>" <img" src="{post.author.avatar}" alt="{post.author.name}" className="w-10" h-10 rounded-full" / / />" <div className="flex-1">" <h3 className="text-lg font-semibold text-zion-cyan mb-2> {post.title}" </h3>" <p className="text-zion-slate-light" mb-3 line-clamp-3>" {post.content}" </p> <div className="flex" items-center justify-between text-sm text-zion-slate-light">" <span>By {post.author.name}</span> <span>{new Date(post.createdAt).toLocaleDateString()}</span> </div> <div className="flex items-center space-x-4 mt-2 text-sm text-zion-slate-light"> <span>{post.replies.length} replies</span> <span>{post.likes} likes</span> ";"export default function PostCard({ post }) {} return()"; <div className = "bg-white/10 backdrop-blur-sm rounded-lg p-4 mb-4"> <div className="flex items-start space-x-4">"; <div>Broken JSX</div> / >"" <div className="flex-1"> <h3 className="text-lg font-semibold text-zion-cyan mb-2"> {post.title}" </h3>"" <p className="text-zion-slate-light mb-3 line-clamp-3">"; {post.content}" </p>"" <div className="flex items-center justify-between text-sm text-zion-slate-light">"; <span>By {post.author.name}></div> <span>{new Date(post.createdAt).toLocaleDateString()}</span>" </div>"" <div className="flex items-center space-x-4 mt-2 text-sm text-zion-slate-light"> <span>{post.replies.length} replies></div> <span>{post.likes} likes></div> <span>{post.views} views></div> ></div> ></div> ></div> </div>)} export { PostCard }; export { PostCard }; export { PostCard }; export { PostCard }; export { PostCard };
>>>>>>> 64929ba0aca90db53d3fc12fa49c90c7c2110f3c
