///usr/bin/env node#!/usr/bin/env node
const fs = require('fs')
const path = require('path')
console.log('🔒 Running security audit...')
console.log('✅ Security audit completed')
///usr/bin/env node

const { execSync } = require('child_process')

console.log('🔒 Starting Security Audit...')
class SecurityAuditor {
class AutoGeneratedClass {
  constructor($2) {
    this.reportFile = path.join(__dirname, '..', 'security-audit-report.json')
    this.results = {
      timestamp: new Date().toISOString(),
      npmAudit: null,
      dependencyCheck: null,
      filePermissions: null,
      environmentVariables: null,
      overall: { status: 'unknown', score: 0 }
    }
  async runCommand(command, description) {
    try {
      console.log(`🔍 ${description}...`)
      const result = execSync(command, {
        encoding: 'utf8',
        stdio: 'pipe',
        cwd: path.join(__dirname, '..')
      })
      console.log(`✅ ${description} - Success`)
      return { success: true, result }
    } catch (error) {
      console.log(`❌ ${description} - Failed: ${error.message}`)
      return { success: false, error: error.message }
  async runNpmAudit() {
    const result = await this.runCommand('npm audit --json', 'NPM Security Audit')
    this.results.npmAudit = result
  async checkDependencies() {
    const result = await this.runCommand('npm ls --depth=0', 'Dependency Check')
    this.results.dependencyCheck = result
  async checkFilePermissions() {
    try {
      const criticalFiles = [
        'package.json',
        'next.config.js',
        'middleware.ts',
        '.env.local',
        '.env.production'
      ]
      const permissions = {}
  for($2) {
        try {
          const stats = fs.statSync(file)
          permissions[file] = {
            exists: true,
            mode: stats.mode.toString(8),
            readable: true,
            writable: true
          }
        } catch (error) {
          permissions[file] = {
            exists: false,
            error: error.message
          }
      this.results.filePermissions = { success: true, permissions }
      console.log('✅ File Permissions Check - Success')
    } catch (error) {
      this.results.filePermissions = { success: false, error: error.message }
      console.log(`❌ File Permissions Check - Failed: ${error.message}`)
  async checkEnvironmentVariables() {
    const envVars = {
      NODE_ENV: process.env.NODE_ENV,
      NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
      SUPABASE_URL: process.env.SUPABASE_URL,
      STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY ? '***HIDDEN***' : undefined
    }
    this.results.environmentVariables = {
      success: true,
      variables: envVars,
      count: Object.keys(envVars).length
    }
    console.log('✅ Environment Variables Check - Success')
  calculateOverallScore($2) {
    let totalScore = 0
    let maxScore = 0
    // NPM Audit (40% weight)
  if($2) {
      totalScore += 100 * 0.4
    maxScore += 100 * 0.4
    // Dependency Check (20% weight)
  if($2) {
      totalScore += 100 * 0.2
    maxScore += 100 * 0.2
    // File Permissions (20% weight)
  if($2) {
      totalScore += 100 * 0.2
    maxScore += 100 * 0.2
    // Environment Variables (20% weight)
  if($2) {
      totalScore += 100 * 0.2
    maxScore += 100 * 0.2
    const finalScore = Math.round((totalScore / maxScore) * 100)
    this.results.overall.score = finalScore
    this.results.overall.status = finalScore >= 80 ? 'excellent' :
                                 finalScore >= 60 ? 'good' :
                                 finalScore >= 40 ? 'fair' : 'poor'
    return finalScore
  async generateReport() {
    const score = this.calculateOverallScore()
    fs.writeFileSync(this.reportFile, JSON.stringify(this.results, null, 2))
    console.log(`📊 Security audit report saved to: ${this.reportFile}`)
    console.log(`🎯 Overall Security Score: ${score}/100 (${this.results.overall.status})`)
  async run() {
    try {
      console.log('🚀 Starting comprehensive security audit...')
      await this.runNpmAudit()
      await this.checkDependencies()
      await this.checkFilePermissions()
      await this.checkEnvironmentVariables()
      await this.generateReport()
      console.log('🎉 Security audit completed successfully!')
    } catch (error) {
      console.log(`❌ Security audit failed: ${error.message}`)
      process.exit(1)
///usr/bin/env node

const { execSync } = require('child_process')
console.log('🔍 Security Audit Starting...')
const securityChecks = [
  {
    name: 'NPM Audit',
    command: 'npm audit --audit-level moderate',
    critical: true
  },
  {
    name: 'Dependency Check',
    check: () => {
      const packageJson = JSON.parse(fs.readFileSync('package.json', 'utf8'))
      const deps = { ...packageJson.dependencies, ...packageJson.devDependencies }
      // Check for known vulnerable packages
      const vulnerablePackages = [
        'lodash',
        'moment',
        'jquery'
      ]
      const foundVulnerable = vulnerablePackages.filter(pkg => deps[pkg])
  if($2) {
        console.log(`⚠️  Potentially vulnerable packages found: ${foundVulnerable.join(', ')}`)
        return false
      return true
  },
  {
    name: 'Environment Variables Check',
    check: () => {
      const envFile = '.env.local'
      if (fs.existsSync(envFile)) {
        const content = fs.readFileSync(envFile, 'utf8')
        const hasSecrets = content.includes('SECRET') || content.includes('KEY') || content.includes('PASSWORD')
  if($2) {
          console.log('⚠️  Environment file contains potential secrets')
          return false
      return true
  },
  {
    name: 'File Permissions Check',
    check: () => {
      const sensitiveFiles = [
        'package.json',
        'package-lock.json',
        'tsconfig.json'
      ]
      let allSecure = true
      sensitiveFiles.forEach(file => {
        if (fs.existsSync(file)) {
          const stats = fs.statSync(file)
          const mode = stats.mode & parseInt('777', 8)
          if (mode > parseInt('644', 8)) {
            console.log(`⚠️  File ${file} has overly permissive permissions`)
            allSecure = false
      })
      return allSecure
// Run the security auditor
const auditor = new SecurityAuditor()
auditor.checkDependencies()
auditor.checkEnvironmentVariables()
const report = auditor.generateReport()
fs.writeFileSync('security-audit-report.json', JSON.stringify(report, null, 2))
console.log('Security audit completed')
///usr/bin/env node

console.log('🔒 Running security audit...')
console.log('✅ Security audit completed')
  if($2) {
  const auditor = new SecurityAuditor()
  auditor.run().catch(console.error)
module.exports = SecurityAuditor
]
let passed = 0
let failed = 0
let criticalFailed = 0
securityChecks.forEach(check => {
  try {
  if($2) {
      console.log(`\n🔄 Running ${check.name}...`)
      execSync(check.command, { stdio: 'pipe' })
      console.log(`✅ ${check.name} passed`)
      passed++
    } else if (check.check()) {
      console.log(`✅ ${check.name}`)
      passed++
    } else {
      console.log(`❌ ${check.name}`)
      failed++
  if($2) {
        criticalFailed++
  } catch (error) {
    console.log(`❌ ${check.name} failed`)
    failed++
  if($2) {
      criticalFailed++
})
