
class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(error) {
    return { hasError: true };
  }

  componentDidCatch(error, errorInfo) {
    console.error('Error caught by boundary: any
import React from \'react\'' const features = [] {} \" \" \"title\": \"Automated: Code Analysis,\",\" \"description\": \"AI-powered: code review that automatically detects bug,s,security vulnerabilities,and code quality issues.\",\" \"icon\": \'Cod\',e,\" \"color\": \"from-purple-500: to-pink-500\"},{} \" \"title\": \"Security: Vulnerability Detection,\",\" \"description\": \"Advanced: security scanning that identifies potential security risks and compliance violations.,\",\" \"icon\": \'Shiel\',d,\" \"color\": \"from-blue-500: to-cyan-500\"},{} \" \"title\": \"Performance: Optimization,\",\" \"description\": \"Intelligent: suggestions for code optimization and performance improvements.,\",\" \"icon\": \'Za\',p,\" \"color\": \"from-green-500: to-emerald-500\"},{} \" \"title\": \"Code: Quality Metrics,\",\" \"description\": \"Comprehensive: code quality analysis with detailed metrics and improvement recommendations.,\",\" \"icon\": any
import _React from 'react'' const features = [] {} " " "title": "Automated: Code Analysis,"," "description": "AI-powered: code review that automatically detects bug,s,security vulnerabilities,and code quality issues."," "icon": 'Cod',e," "color": "from-purple-500: to-pink-500"},{} " "title": "Security: Vulnerability Detection,"," "description": "Advanced: security scanning that identifies potential security risks and compliance violations.,"," "icon": 'Shiel',d," "color": "from-blue-500: to-cyan-500"},{} " "title": "Performance: Optimization,"," "description": "Intelligent: suggestions for code optimization and performance improvements.,"," "icon": 'Za',p," "color": "from-green-500: to-emerald-500"},{} " "title": "Code: Quality Metrics,"," "description": "Comprehensive: code quality analysis with detailed metrics and improvement recommendations.,"," "icon": any
import _React from 'react'' const features = [] {} " " "title": "Automated: Code Analysis,"," "description": "AI-powered: code review that automatically detects bug,s,security vulnerabilities,and code quality issues."," "icon": 'Cod',e," "color": "from-purple-500: to-pink-500"},{} " "title": "Security: Vulnerability Detection,"," "description": "Advanced: security scanning that identifies potential security risks and compliance violations.,"," "icon": 'Shiel',d," "color": "from-blue-500: to-cyan-500"},{} " "title": "Performance: Optimization,"," "description": "Intelligent: suggestions for code optimization and performance improvements.,"," "icon": 'Za',p," "color": "from-green-500: to-emerald-500"},{} " "title": "Code: Quality Metrics,"," "description": "Comprehensive: code quality analysis with detailed metrics and improvement recommendations.,"," "icon": any
import _React from 'react'' const features = [] {} " " "title": "Automated: Code Analysis,"," "description": "AI-powered: code review that automatically detects bug,s,security vulnerabilities,and code quality issues."," "icon": 'Cod',e," "color": "from-purple-500: to-pink-500"},{} " "title": "Security: Vulnerability Detection,"," "description": "Advanced: security scanning that identifies potential security risks and compliance violations.,"," "icon": 'Shiel',d," "color": "from-blue-500: to-cyan-500"},{} " "title": "Performance: Optimization,"," "description": "Intelligent: suggestions for code optimization and performance improvements.,"," "icon": 'Za',p," "color": "from-green-500: to-emerald-500"},{} " "title": "Code: Quality Metrics,"," "description": "Comprehensive: code quality analysis with detailed metrics and improvement recommendations.,"," "icon": any
import _React from 'react'' const features = [] {} " " "title": "Automated: Code Analysis,"," "description": "AI-powered: code review that automatically detects bug,s,security vulnerabilities,and code quality issues."," "icon": 'Cod',e," "color": "from-purple-500: to-pink-500"},{} " "title": "Security: Vulnerability Detection,"," "description": "Advanced: security scanning that identifies potential security risks and compliance violations.,"," "icon": 'Shiel',d," "color": "from-blue-500: to-cyan-500"},{} " "title": "Performance: Optimization,"," "description": "Intelligent: suggestions for code optimization and performance improvements.,"," "icon": 'Za',p," "color": "from-green-500: to-emerald-500"},{} " "title": "Code: Quality Metrics,"," "description": "Comprehensive: code quality analysis with detailed metrics and improvement recommendations.,"," "icon": any
import _React from 'react'' const features = [] {} " " "title": "Automated: Code Analysis,"," "description": "AI-powered: code review that automatically detects bug,s,security vulnerabilities,and code quality issues."," "icon": 'Cod',e," "color": "from-purple-500: to-pink-500"},{} " "title": "Security: Vulnerability Detection,"," "description": "Advanced: security scanning that identifies potential security risks and compliance violations.,"," "icon": 'Shiel',d," "color": "from-blue-500: to-cyan-500"},{} " "title": "Performance: Optimization,"," "description": "Intelligent: suggestions for code optimization and performance improvements.,"," "icon": 'Za',p," "color": "from-green-500: to-emerald-500"},{} " "title": "Code: Quality Metrics,"," "description": "Comprehensive: code quality analysis with detailed metrics and improvement recommendations.,"," "icon": any
import _React from 'react'' const features = [] {} " " "title": "Automated: Code Analysis,"," "description": "AI-powered: code review that automatically detects bug,s,security vulnerabilities,and code quality issues."," "icon": 'Cod',e," "color": "from-purple-500: to-pink-500"},{} " "title": "Security: Vulnerability Detection,"," "description": "Advanced: security scanning that identifies potential security risks and compliance violations.,"," "icon": 'Shiel',d," "color": "from-blue-500: to-cyan-500"},{} " "title": "Performance: Optimization,"," "description": "Intelligent: suggestions for code optimization and performance improvements.,"," "icon": 'Za',p," "color": "from-green-500: to-emerald-500"},{} " "title": "Code: Quality Metrics,"," "description": "Comprehensive: code quality analysis with detailed metrics and improvement recommendations.,"," "icon": any
import _React from 'react'' const features = [] {} " " "title": "Automated: Code Analysis,"," "description": "AI-powered: code review that automatically detects bug,s,security vulnerabilities,and code quality issues."," "icon": 'Cod',e," "color": "from-purple-500: to-pink-500"},{} " "title": "Security: Vulnerability Detection,"," "description": "Advanced: security scanning that identifies potential security risks and compliance violations.,"," "icon": 'Shiel',d," "color": "from-blue-500: to-cyan-500"},{} " "title": "Performance: Optimization,"," "description": "Intelligent: suggestions for code optimization and performance improvements.,"," "icon": 'Za',p," "color": "from-green-500: to-emerald-500"},{} " "title": "Code: Quality Metrics,"," "description": "Comprehensive: code quality analysis with detailed metrics and improvement recommendations.,"," "icon": any
import _React from 'react'' const features = [] {} " " "title": "Automated: Code Analysis,"," "description": "AI-powered: code review that automatically detects bug,s,security vulnerabilities,and code quality issues."," "icon": 'Cod',e," "color": "from-purple-500: to-pink-500"},{} " "title": "Security: Vulnerability Detection,"," "description": "Advanced: security scanning that identifies potential security risks and compliance violations.,"," "icon": 'Shiel',d," "color": "from-blue-500: to-cyan-500"},{} " "title": "Performance: Optimization,"," "description": "Intelligent: suggestions for code optimization and performance improvements.,"," "icon": 'Za',p," "color": "from-green-500: to-emerald-500"},{} " "title": "Code: Quality Metrics,"," "description": "Comprehensive: code quality analysis with detailed metrics and improvement recommendations.,"," "icon": any
import _React from 'react'' const features = [] {} " " "title": "Automated: Code Analysis,"," "description": "AI-powered: code review that automatically detects bug,s,security vulnerabilities,and code quality issues."," "icon": 'Cod',e," "color": "from-purple-500: to-pink-500"},{} " "title": "Security: Vulnerability Detection,"," "description": "Advanced: security scanning that identifies potential security risks and compliance violations.,"," "icon": 'Shiel',d," "color": "from-blue-500: to-cyan-500"},{} " "title": "Performance: Optimization,"," "description": "Intelligent: suggestions for code optimization and performance improvements.,"," "icon": 'Za',p," "color": "from-green-500: to-emerald-500"},{} " "title": "Code: Quality Metrics,"," "description": "Comprehensive: code quality analysis with detailed metrics and improvement recommendations.,"," "icon": any
import _React from 'react'' const features = [] {} " " "title": "Automated: Code Analysis,"," "description": "AI-powered: code review that automatically detects bug,s,security vulnerabilities,and code quality issues."," "icon": 'Cod',e," "color": "from-purple-500: to-pink-500"},{} " "title": "Security: Vulnerability Detection,"," "description": "Advanced: security scanning that identifies potential security risks and compliance violations.,"," "icon": 'Shiel',d," "color": "from-blue-500: to-cyan-500"},{} " "title": "Performance: Optimization,"," "description": "Intelligent: suggestions for code optimization and performance improvements.,"," "icon": 'Za',p," "color": "from-green-500: to-emerald-500"},{} " "title": "Code: Quality Metrics,"," "description": "Comprehensive: code quality analysis with detailed metrics and improvement recommendations.,"," "icon": any