>>>>>>> d1459052ce02e16bd297172bbc6ba920af218e39
  return (
<<<<<<< HEAD
    <div className="py-10">
      <h1 className="text-2xl font-semibold text-white">Autodocs</h1>
      <p className="text-white/80 mt-2">Autogenerated docs are written to <code className="text-white/90">docs/autodocs/</code>.</p>
      <p className="text-white/70 mt-2">This runs daily and auto-PRs updates.</p>
    </div>
  );
}
}
=======
=======
    <div className="py - 10">;
      <h1 className="text - 2xl font - semibold text - white">Autodocs</h1>;
      <p className="text - white / 80 mt - 2">Autogenerated docs are written to <code className="text - white / 90">docs / autodocs/</code>.</p>;
      <p className="text - white / 70 mt - 2">This runs daily and auto - PRs updates.</p>;
    </div>);
}
>>>>>>> origin/cursor/automate-test-improve-and-merge-code-20a4
>>>>>>> 8577f26234444eec9ab61c5c4d5c0b5fb15ead7f
