<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
export default function AutodocsPage() {
>>>>>>> origin/cursor/integrate-build-improve-and-re-verify-2156
>>>>>>> d1459052ce02e16bd297172bbc6ba920af218e39
  return (
<<<<<<< HEAD
    <div className="py-10">;
      <h1 className="text-2xl font-semibold text-white">Autodocs</h1>;
      <p className="text-white/80 mt-2">Autogenerated docs are written to <code className="text-white/90">docs/autodocs/</code>.</p>;
      <p className="text-white/70 mt-2">This runs daily and auto-PRs updates.</p>;
    </div>;
  );
<<<<<<< HEAD
}
=======
}
>>>>>>> origin/cursor/integrate-build-improve-and-re-verify-2156
=======
    <div className="py - 10">;
      <h1 className="text - 2xl font - semibold text - white">Autodocs</h1>;
      <p className="text - white / 80 mt - 2">Autogenerated docs are written to <code className="text - white / 90">docs / autodocs/</code>.</p>;
      <p className="text - white / 70 mt - 2">This runs daily and auto - PRs updates.</p>;
    </div>);
}
>>>>>>> origin/cursor/automate-test-improve-and-merge-code-20a4
