<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
  return (
=======
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> origin/cursor/fix-syntax-push-and-merge-to-main-8452


  return (

}



}



  return (
    <div className="py-10">
      <h1 className="text-2xl font-semibold text-white">Autodocs</h1>
      <p className="text-white/80 mt-2">Autogenerated docs are written to <code className="text-white/90">docs/autodocs/</code>.</p>
      <p className="text-white/70 mt-2">This runs daily and auto-PRs updates.</p>
    </div>
  );
}
}
  return (
<<<<<<< HEAD
>>>>>>> f8e9d8204b854980b1ebe0327134be4447b2409a
>>>>>>> a252feedad80e14c11ed30f5695974c343534e8d
=======

>>>>>>> origin/cursor/automate-test-improve-and-merge-code-2533
=======
>>>>>>> origin/cursor/fix-syntax-push-and-merge-to-main-8452
