<<<<<<< HEAD

<<<<<<< HEAD
}
) )
}</ul> </section> <section>) )
}</ul> </section> </div>)
=======
import fs from 'fs';
import path from 'path';
import type { GetStaticProps } from 'next';
type Entry = { route: string, file: string },
interface Report { generatedAt: string, totalPages: number, bySection: Record<string, number>, pages: Entry[] }

type Props = { report: Report | null },
export const getStaticProps: GetStaticProps<Props> = async () => {
  try {
    const file = path.join(process.cwd(), 'publicautomationcontent-map.json');
    const raw = fs.readFileSync(file, 'utf8');
    const data = JSON.parse(raw);
    return { props: { report: data }, revalidate: 21600 }
  } catch {
    return { props: { report: null }, revalidate: 21600 }
  }
};

>>>>>>> origin/cursor/integrate-build-improve-and-re-verify-2156
export default function ContentMap({ report }: Props) {
  if (!report) return <div>No content map yet. Check back later.</div>;
  const sections = Object.entries(report.bySection).sort((a, b) => b[1] - a[1]);

  return (
    <div className="space-y-6">
      <header className="space-y-1">
        <h1 className="text-3xl font-bold">Content Map</h1>
        <p className="text-gray-600 dark:text-gray-300">Autogenerated coverage of site pages.</p>
      </header>
      <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="p-4 rounded-lg border border-gray-200 dark:border-gray-800"><div className="text-xs text-gray-500">Total Pages</div><div className="text-2xl font-semibold">{report.totalPages}</div></div>
        <div className="p-4 rounded-lg border border-gray-200 dark:border-gray-800"><div className="text-xs text-gray-500">Sections</div><div className="text-2xl font-semibold">{sections.length}</div></div>
      </div>
      <section>
        <h2 className="font-semibold mb-2">Pages by Section</h2>
        <ul className="text-sm space-y-1">
          {sections.map(([sec, n]) => (
            <li key={sec} className="flex justify-between"><span>{sec |'root'}</span><span className="text-gray-500">{n}</span></li>
=======
};
) ) ;
}</ul> </section> <section>) ) ;
}</ul> </section> </div>) ;
export default function ContentMap(): any ({ report }: Props) {;
  if (!report) return <div>No content map yet. Check back later.</div>;
  const sections = Object && Object.entries(report && report.bySection).sort((a, b) => b[1] - a[1]);
  return (
    <div className="space-y-6">;
      <header className="space-y-1">;
        <h1 className="text-3xl font-bold">Content Map</h1>;
        <p className="text-gray-600 dark:text-gray-300">Autogenerated coverage of site pages.</p>;
      </header>;
      <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">;
        <div className="p-4 rounded-lg border border-gray-200 dark:border-gray-800"><div className="text-xs text-gray-500">Total Pages</div><div className="text-2xl font-semibold">{report && report.totalPages}</div></div>;
        <div className="p-4 rounded-lg border border-gray-200 dark:border-gray-800"><div className="text-xs text-gray-500">Sections</div><div className="text-2xl font-semibold">{sections && sections.length}</div></div>;
      </div>;
      <section>;
        <h2 className="font-semibold mb-2">Pages by Section</h2>;
        <ul className="text-sm space-y-1">;
          {sections && sections.map(([sec, n]) => (;
            <li key={sec} className="flex justify-between"><span>{sec || 'root'}</span><span className="text-gray-500">{n}</span></li>;
>>>>>>> origin/cursor/automate-test-improve-and-merge-code-382a
          ))}
        </ul>;
      </section>;
      <section>;
        <h2 className="font-semibold mb-2">All Pages</h2>;
        <ul className="text-sm space-y-1 max-h-96 overflow-auto border rounded p-3 border-gray-200 dark:border-gray-800">;
          {report && report.pages.map((p, i) => (;
            <li key={i} className="flex justify-between gap-4"><span className="truncate">{p && p.route}</span><span className="text-gray-500 truncate">{p && p.file}</span></li>;
          ))}
<<<<<<< HEAD
        </ul>
      </section>
    </div>
);
}
=======
        </ul>;
      </section>;
    </div>;
  );
}
<<<<<<< HEAD
>>>>>>> origin/cursor/automate-test-improve-and-merge-code-382a
=======
>>>>>>> origin/cursor/integrate-build-improve-and-re-verify-2156
