export default function ContentMap({ report }: Props) {
  if (!report) return <div>No content map yet. Check back later.</div>;
  const sections = Object.entries(report.bySection).sort((a, b) => b[1] - a[1]);

}
) )
}</ul> </section> <section>) )
}</ul> </section> </div>)
=======
>>>>>>> f8e247744ae2f2b9a6ba0423164ce0dcdffb9f6a
};
) ) 
}</ul> </section> <section>) ) 
}</ul> </section> </div>)
export default function ContentMap({ report }: Props) {;
export default function ContentMap({ report }: Props) {
  if (!report) return <div>No content map yet. Check back later.</div>;
  const sections = Object.entries(report.bySection).sort((a, b) => b[1] - a[1]);

  return (
    <div className="space-y-6">
      <header className="space-y-1">
        <h1 className="text-3xl font-bold">Content Map</h1>
        <p className="text-gray-600 dark:text-gray-300">Autogenerated coverage of site pages.</p>
      </header>
      <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="p-4 rounded-lg border border-gray-200 dark:border-gray-800"><div className="text-xs text-gray-500">Total Pages</div><div className="text-2xl font-semibold">{report.totalPages}</div></div>
        <div className="p-4 rounded-lg border border-gray-200 dark:border-gray-800"><div className="text-xs text-gray-500">Sections</div><div className="text-2xl font-semibold">{sections.length}</div></div>
      </div>
      <section>
        <h2 className="font-semibold mb-2">Pages by Section</h2>
        <ul className="text-sm space-y-1">
          {sections.map(([sec, n]) => (
            <li key={sec} className="flex justify-between"><span>{sec |'root'}</span><span className="text-gray-500">{n}</span></li>
>>>>>>> cursor/expand-services-advertise-and-build-project-4b36
        </ul>;
      </section>;
    </div>;
  );
}
==============
        </ul>
      </section>
      <section>
        <h2 className="font-semibold mb-2">All Pages</h2>
        <ul className="text-sm space-y-1 max-h-96 overflow-auto border rounded p-3 border-gray-200 dark:border-gray-800">
          {report.pages.map((p, i) => (
            <li key={i} className="flex justify-between gap-4"><span className="truncate">{p.route}</span><span className="text-gray-500 truncate">{p.file}</span></li>
          ))}
        </ul>
      </section>
    </div>
);
}
  );
}

=======}
) );
}</ul> </section> <section>) );
}</ul> </section> </div>);
export default /**
 * ContentMap - Function description
 */
function ContentMap() {
  // Check condition
if (return <div > No content map yet. Check back later.</div>) {
  $2
}
  const sections = Object.entries (report.by_section).sort ((a, b) => b[1] - a[1]);
  return (
    <div className="space - y-6">;
      <header className="space - y-1">;
        <h1 className="text - 3xl font - bold">Content Map</h1>;
        <p className="text - gray - 600 dark:text - gray - 300">Autogenerated coverage of site pages.</p>;
      </header>;
      <div className="grid sm:grid - cols - 2 lg:grid - cols - 4 gap - 4">;
        <div className="p - 4 rounded - lg border border - gray - 200 dark:border - gray - 800"><div className="text - xs text - gray - 500">Total Pages</div><div className="text - 2xl font - semibold">{report.total_pages}</div></div>;
        <div className="p - 4 rounded - lg border border - gray - 200 dark:border - gray - 800"><div className="text - xs text - gray - 500">Sections</div><div className="text - 2xl font - semibold">{sections.length}</div></div>;
      </div>;
      <section>;
        <h2 className="font - semibold mb - 2">Pages by Section</h2>;
        <ul className="text - sm space - y-1">;
          {sections.map (([sec, n]) => (
            <li key={sec} className="flex justify - between"><span>{sec || 'root'}</span><span className="text - gray - 500">{n}</span></li>))}
        </ul>;
      </section>;
      <section>;
        <h2 className="font - semibold mb - 2">All Pages</h2>;
        <ul className="text - sm space - y-1 max - h-96 overflow - auto border rounded p - 3 border - gray - 200 dark:border - gray - 800">;
          {report.pages.map ((p, i) => (
            <li key={i} className="flex justify - between gap - 4"><span className="truncate">{p.route}</span><span className="text - gray - 500 truncate">{p.file}</span></li>))}
        </ul>;
      </section>;
    </div>);
  }
},

export default function ContentMap({ report }: Props) {
  if (!report) return <div>No content map yet. Check back later.</div>,
  const sections = Object.entries(report.bySection).sort((a, b) => b[1] - a[1]),
  return (
    <div className=&quot;space-y-6&quot;>
      <header className=&quot;space-y-1&quot;>
        <h1 className=&quot;text-3xl font-bold&quot;>Content Map</h1>
        <p className=&quot;text-gray-600 dark:text-gray-300&quot;>Autogenerated coverage of site pages.</p>
      </header>
      <div className=&quot;grid sm:grid-cols-2 lg:grid-cols-4 gap-4&quot;>
        <div className=&quot;p-4 rounded-lg border border-gray-200 dark:border-gray-800&quot;><div className=&quot;text-xs text-gray-500&quot;>Total Pages</div><div className=&quot;text-2xl font-semibold&quot;>{report.totalPages}</div></div>
        <div className=&quot;p-4 rounded-lg border border-gray-200 dark:border-gray-800&quot;><div className=&quot;text-xs text-gray-500&quot;>Sections</div><div className=&quot;text-2xl font-semibold&quot;>{sections.length}</div></div>
      </div>
      <section>
        <h2 className=&quot;font-semibold mb-2&quot;>Pages by Section</h2>
        <ul className=&quot;text-sm space-y-1&quot;>
          {sections.map(([sec, n]) => (
            <li key={sec} className=&quot;flex justify-between&quot;><span>{sec || 'root'}</span><span className=&quot;text-gray-500&quot;>{n}</span></li>
  );
}
);
}
  );
}
==============

  );
}
>>>>>>> cursor/expand-services-advertise-and-build-project-4b36
=======

>>>>>>> cursor/fix-website-loading-errors-and-merge-6662
>>>>>>> f8e247744ae2f2b9a6ba0423164ce0dcdffb9f6a
