
export default function Page() {

<<<<<<< HEAD
  return (
    <div className='min-h-screen bg-slate-950 text-white'>
      <Head>
        <title>Reference Architecture — Autonomous Content Mesh</title>
        <meta
          name='description'
          content='High-level blueprint for an autonomous content mesh with evaluation-in-the-loop.'
        />
        <meta
          property='og:title'
          content='Reference Architecture — Autonomous Content Mesh'
        />
        <meta
          property='og:description'
          content='High-level blueprint for an autonomous content mesh with evaluation-in-the-loop.'
        />
        <meta name='twitter:card' content='summary_large_image' />
      </Head>
      <main className='container mx-auto px-6 py-12 prose prose-invert'>
        <h1 className='text-3xl font-extrabold'>
          Reference Architecture — Autonomous Content Mesh
        </h1>
        <div className='mt-4' dangerouslySetInnerHTML={{ __html: `${body}` }} />
        <p className='mt-6 text-white/60 text-sm'>
          Auto-generated by Cloud Blueprint Factory.
        </p>
      </main>
    </div>;
  );
}/> <p className="mt-6 text-white/60 text-sm" >Auto-generated by Cloud Blueprint Factory.</p> </main> </div>)   return (
  return (
    <div className="min-h-screen bg-slate-950 text-white">
      <Head>
        <title>Reference Architecture — Autonomous Content Mesh</title>
        <meta name="description" content="High-level blueprint for an autonomous content mesh with evaluation-in-the-loop." />
        <meta property="og:title" content="Reference Architecture — Autonomous Content Mesh" />
        <meta property="og:description" content="High-level blueprint for an autonomous content mesh with evaluation-in-the-loop." />
        <meta name="twitter:card" content="summary_large_image" />
      </Head>
      <main className="container mx-auto px-6 py-12 prose prose-invert">
        <h1 className="text-3xl font-extrabold">Reference Architecture — Autonomous Content Mesh</h1>
        <div className="mt-4" dangerouslySetInnerHTML={{ __html: `${body}` }} />
        <p className="mt-6 text-white/60 text-sm">Auto-generated by Cloud Blueprint Factory.</p>
      </main>
    </div>
  );
}
  )
  } catch (error) {
    console.error("Error:", error);
    return res.status(500).json({ error: "Internal server error" });
  }
}
;
=======
>>>>>>> cursor/fix-website-loading-errors-and-merge-6662
>>>>>>> 0fbf271b1f2a86c928092eda22ad7978eb59d0ee
