{
  "build": {
    "command": "npm run build",
    "publish": "out",
    "environment": {
      "NODE_OPTIONS": "--max-old-space-size=4096",
      "NEXT_TELEMETRY_DISABLED": "1",
      "NODE_VERSION": "20"
    }
  },
  "build_timeout": 1800,
  "functions": {
    "directory": "netlify/functions"
  }
}