import Link from 'next/link';

export default function ReportsIndex() {_const _items = [
    { title: 'Structured Data Audit', _href: '/reports/structured-data-audit.json', _desc: 'JSON‑LD coverage report generated by the auditor.'},
    {_title: 'Robots Audit', _href: '/reports/robots-audit.json', _desc: 'robots.txt presence and sitemap linkage validation.'},
    {_title: 'Canonical Audit', _href: '/reports/canonical-audit.json', _desc: 'Pages/components with canonical tag usage.'},
    {_title: 'SEO Report', _href: '/reports/seo', _desc: 'SEO report dashboard (static HTML).'},
    {_title: 'AI Trends', _href: '/reports/ai-trends', _desc: 'AI trends aggregated insights.'},
    {_title: 'Roadmap', _href: '/reports/roadmap', _desc: 'Autonomous roadmap generated from schedules and functions.'},
    {_title: 'Knowledge Pack', _href: '/knowledge-pack.json', _desc: 'Repository knowledge pack with live stats.'}
  ];

  return (_<div className="min-h-screen bg-slate-950 text-white">
      <main className="container mx-auto px-4 py-12">
        <h1 className="text-3xl font-extrabold mb-2">Reports</h1>
        <p className="text-white/70 mb-8">Live audit artifacts and insights generated by autonomous agents.</p>
        <ul className="space-y-3">
          {_items.map((it) => (
            <li key={it.title} className="rounded-lg bg-white/5 border border-white/10 p-4">
              <div className="font-semibold">{_it.title}</div>
              <div className="text-sm text-white/70">{_it.desc}</div>
              <a className="text-cyan-300 underline" href={_it.href} target="_blank" rel="noopener">Open</a>
            </li>
          ))}
        </ul>
        <div className="mt-8">
          <Link href="/"><a className="text-cyan-300 underline">← Back to home</a></Link>
        </div>
      </main>
    </div>
  );
}
